composer/callbacks/callback_hparams.py, composer/callbacks/torch_profiler.py
Added the repeat argument to the hparams for the torch profiler callback
This makes it possible to profile only N times per epoch. Profiling slows down the training process significantly!
=> Added repeat to the torch profiler

composer/datasets/synthetic.py, composer/yamls/models/resnet101_synthetic.yaml, composer/yamls/models/resnet18_synthetic.yaml, composer/yamls/models/resnet50_synthetic.yaml, composer/yamls/models/resnet56_cifar10_synthetic.yaml, tests/algorithms/test_stochastic_depth.py, tests/callbacks/test_grad_monitor.py, tests/callbacks/test_memory_monitor.py, tests/datasets/__init__.py, tests/datasets/test_synthetic_data.py, tests/fixtures/dummy_fixtures.py, tests/fixtures/models.py, tests/test_dataset_registry.py, tests/test_load.py, tests/trainer/test_ddp.py, tests/utils/trainer_fit.py
Right now, `SyntheticDataset` can only represent an epoch that consists of a single batch. This change allows `SyntheticDataset` to emulate a dataset that consists of multiple batches. This functionality is useful for benchmarking workloads that use a `SyntheticDataset`.
Additionally, `SyntheticDataset` only supports classification labels. This PR adds functionality for custom label shapes so that `SyntheticDataset` can be used for tasks such as image segmentation and NLP.
=> Additional`SyntheticDataset` Customization

composer/core/logging/logger.py, pyproject.toml, setup.py, tests/callbacks/test_memory_monitor.py, tests/conftest.py, tests/test_load.py
1. Fixed settings for coverage reports so source code can be included
2. Fixed package_data so yaml files are properly included. 
3. Added `py.typed` to indicate that the repository has typing annotations
4. Printing the `pillow-simd` warning in setup.py to stderr so it does not interfere with `setup.py --version` and other CLI args
5. Logging at the debug level when running tests
6. Increasing timeout for `test_load`, since that sometimes takes longer than 2 seconds.
7. Only bundling the `composer` package in setup.py so the `tests/` folder isn't included as well
=> Fix Tests and setup.py

composer/algorithms/algorithm_hparams.py, composer/trainer/trainer_hparams.py, tests/test_amp.py, tests/test_hparams.py
When using preset models or algorithms (e.g. via `load_model` or `load_algorithms`), CLI args were also being read, which lead to runtime errors in Colab (where the CLI arguments it was started with conflicted with the CLI arguments for the mosaic trainer. Instead, this change disables parsing of CLI arguments when using `load_model` and `load_algorithms`.
=> Added explicit cli_args=False for `load_model` and `load_algorithms`

examples/run_mosaic_trainer.py
simple comment fix so that example will run out of the box. It may be useful to have a sane default alpha set for label smoothing in the future.
=> label smoothing will not work without alpha set

composer/core/engine.py
* For the INIT event, run the callbacks first to initialize the loggers.
* For other events, run the algorithms first, so the callbacks have the state  after algorithms modify it.
=> Running callbacks befor algorithms for the INIT event in the engine

setup.py
Argparse is included in the stdlib for python 3.2+, so no need to install from pip. It generates a warning when using colab that you need to restart the runtime.
=> Remove argparse from setup.py

composer/datasets/synthetic.py
Torch.memory_format cannot be attached to datasets that are passed into dataloaders, as they are not pickleable. Instaed, storing the enum until it is ready to be used
=> Fixed pickling of torch.memory_format objects

composer/optim/pytorch_future.py, composer/optim/scheduler.py, composer/trainer/trainer_hparams.py, tests/trainer/test_scheduler.py
BERT models need a linear decay in the learning rate. This PR serves to add that.
See [this](https://wandb.ai/mosaic-ml/bert/runs/tq9oxvb3?workspace=user-moin-mosaic) WandB project to show that it is working.
=> Add a linear learning rate decay

composer/algorithms/channels_last/channels_last.py
Channels last should be applied BEFORE ddp. DDP wrapping of the module happens after init but before training start.
=> Apply channels last on init

composer/callbacks/run_directory_uploader.py, composer/loggers/wandb_logger.py, composer/utils/run_directory.py, tests/conftest.py, tests/test_amp.py, tests/test_logger.py, tests/trainer/test_checkpoint.py, tests/trainer/test_ddp.py
Ensuring that the run directory is not being modified while wandb is uploading artifacts.
Hopefully closes #90
=> Guard artifact uploading in wandb with ddp barriers

README.md, composer/cli/launcher.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, docs/source/getting_started/using_composer.rst, examples/composer.ipynb, examples/run_mosaic_trainer.py
1. Moved the `datadir` onto trainer hparams to avoid an UnusedArgumentWarning
2. Setting the default loglevel to warning
3. Cleaned up warnings to not print a useless extra second line showing the source code of the warning.warn call
4. Cleaned up the launch script to be not-very-verbose by default; but added a -v option for verbosity.
5. If `run_mosaic_trainer.py` is run without args, then the help is printed.
Closes #88, #128
=> Print help on `run_mosaic_trainer.py`, cleaned up verbosity.

composer/core/state.py, composer/trainer/checkpoint.py, composer/trainer/trainer.py, tests/callbacks/test_run_directory_uploader.py, tests/trainer/test_checkpoint.py
This change addresses issue #12 and introduces the following:
- Even when the user provides a seed, each process will have a different seed which is `user_provided_seed + global_rank`. The reason for this is that for algorithms like mixup which modify training batches, we want the modifications to be different on batches on different processes.
- When checkpointing, we store and load seeds using all processes, not just the seed from rank 0.
Test Plan:
- The existing distributed checkpointing tests cover the new code paths introduced here.
=> DDP Seeding Across Processes

composer/callbacks/run_directory_uploader.py, composer/utils/run_directory.py, tests/callbacks/test_run_directory_uploader.py
The issue was introduced in #162 with how the run directory was monkeypatched for the tests. This monkeypatching did not apply to subprocessing. Changed uploading to use UUIDs when copying to the staging directory to avoid conflicts.
Closes #176
=> Fixed the run directory uploader test

tests/callbacks/test_run_directory_uploader.py, tests/test_logger.py
* The wandb test should be skipped as wandb is installed with mosaicml[logging]
* The run directory uploader test should be skipped as libcloud is installed with mosaicml[logging]
=> Conditionally skip tests when installed with mosaicml[dev]

composer/cli/launcher.py
The launcher script suppressed processes that were terminated with sigkill, which meant that tests that OOM'ed were reported as passing. This was a relic from when we used DDP spawn and we deliberately sigkilled child processes. This change ensures that sigkilled error codes are propagated.
=> Propagate processes that were sigkilled

composer/core/state.py, composer/datasets/hparams.py, composer/optim/pytorch_future.py, composer/trainer/checkpoint.py, composer/trainer/checkpoint_hparams.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, tests/trainer/test_checkpoint.py
This pull request enables the ability to load a checkpoint without loading the associated state. It does so via the following YAML changes:
1. Introduces a `CheckpointLoaderHparams` object, with three fields: `checkpoint_filepath`, `load_weights_only`, and `strict`. 
2. If `load_weights_only = False`, then nothing changes and the previous codepaths are used. The `strict` value isn't considered if `load_weights_only = False`, since restoring a checkpoint with state should ensure that the model exactly matches up. YAML validation ensures that the `strict` value cannot be set without `load_weights_only = True`.
3. If `load_weights_only = True`, then it loads the checkpoint and avoids recovering the state via a new codepath. If `strict = False`, it also prints the keys that did not match up …
=> Add the ability to load a checkpoint without restoring state

composer/models/__init__.py, composer/models/resnet9_cifar10/__init__.py, composer/models/resnet9_cifar10/model.py, composer/models/resnet9_cifar10/resnet9_cifar10_hparams.py, composer/trainer/trainer_hparams.py, composer/yamls/models/resnet9_cifar10.yaml, tests/test_model_registry.py
This is [the architecture](https://myrtle.ai/learn/how-to-train-your-resnet-4-architecture/) that someone got to train to 94% accuracy [in 26 seconds](https://myrtle.ai/learn/how-to-train-your-resnet-8-bag-of-tricks/). The purpose of adding this is that it should let us do CIFAR-10 runs much faster for quick prototyping--I basically threw this together while waiting for some CIFAR-10 jobs to finish.
[Wandb results](https://wandb.ai/mosaic-ml/c10/runs/ig3ra9pm?workspace=user-dblalock): 92.82% accuracy from 1 run using our resnet56 hparams. This is slightly lower than in the blog post (94%), but has zero bag-of-tricks enhancements or hparam tuning.
=> Add ResNet-9 for CIFAR-10

composer/core/state.py, composer/trainer/checkpoint.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, pyproject.toml, tests/conftest.py, tests/test_state.py, tests/trainer/test_checkpoint.py
Support for model checkpointing while using DeepSpeed. We're lucky in that DeepSpeed provides a pretty good API for creating checkpoints. With this design, we entrust DeepSpeed to serialize the model and optimizer states, and we handle everything else as before.
One of the biggest changes in this PR is that a "checkpoint" is no longer a file, but a folder. This is necessary because it's how DeepSpeed does it - its checkpoints often comprise several files.
In practice, whereas before our structure was something like:
```
checkpoints_folder/
hparams.yaml
ep1.pt
ep2.pt
ep3.pt
```
We now have:
```
checkpoints_folder/
hparams.yaml
ep1/
mosaic_states.pt
<any DeepSpeed files>
ep2/
...
ep3/
...
...
```
DDP (and DeepSpeed) initialization has been moved into `Trainer.__init__` - this was necessary …
=> Checkpointing & DeepSpeed

composer/trainer/deepspeed.py, composer/trainer/trainer.py
Fixes the precision issues that were causing DeepSpeed to crash when used to train CV models. Namely, in FP16 mode we just have to cast batches to FP16 manually in some scenarios.
https://wandb.ai/mosaic-ml/deepspeed-cv-3?workspace=user-jbloxham
=> DeepSpeed precision fixes for CV

composer/yamls/models/gpt2_1,3b.yaml, composer/yamls/models/gpt2_13b.yaml, composer/yamls/models/gpt2_2,7b.yaml, composer/yamls/models/gpt2_350m.yaml, composer/yamls/models/gpt2_6,7b.yaml, composer/yamls/models/gpt2_760m.yaml
Time to go bigger :)
Specs copied from https://arxiv.org/pdf/2005.14165.pdf. Only fields changed from the existing GPT models are:
`model.gpt2.n_embd`
`model.gpt2.n_head`
`model.gpt2.n_inner`
`model.gpt2.n_layer`
`optimizer.adamw.lr`
`train_batch_size`
`grad_accum`
=> Add larger GPT models

setup.py
`pip install -e` doesn't work as root. `pip install --user -e` does.
=> Require `pip install -e` be `pip install --user -e` when running as root

.github/actions/pyright/action.yaml, composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/callbacks/benchmarker.py, composer/callbacks/speed_monitor.py, composer/core/state.py, composer/trainer/deepspeed.py, composer/trainer/trainer.py, composer/utils/data.py, composer/utils/iter_helpers.py, composer/utils/iter_helpers.pyi
1. Remove the dataspec from state! Instead, the trainer sets `batch_num_samples`, `batch_num_tokens`, `microbatches`, and `microbatch_idx` so these fields are accessible to algorithms that need to know the pertinent information that the data spec provided.
2. Removed last_batch_size from state. Replaced it with `dist.all_reduce(state.batch_num_samples)` where it was used.
3. Removed `train_batch_size` and `eval_batch_size` from state, as algorithms should not depend on constant batch sizing. Replaced it with `state.train_dataloader.batch_size * dist.get_world_size()` in the few places where it was used
4. Added a helper function to `get_device_of_batch`, which is required for part 3 (since `dist.all_reduce` requires tensors to be placed on the device it torch.dist was initialized with)
5. …
=> Cleaned Up State

composer/callbacks/speed_monitor.py
Since the speed monitor calls `dist.all_reduce`, it must run on all ranks now.
=> Fix the speed monitor

composer/optim/scheduler.py, setup.py, tests/test_dataset_registry.py
1. Removed `test_mnist_real_dataset` since it's slow (downloads the entire mnist) and doesn't add much value
2. Refactored `_convert_time_fields` in the scheduler so it doesn't modify the dataclass in place. The issue with in-place modification was that checkpoint saver was saving the hparams dataclass after the fields have been converted. Then, when resuming from checkpoint, the already-converted fields were no longer valid time strings, so it crashed.
3. Added `requests` to the base dependency (it is used by the checkpoint loader)
=> Fix broken tests

composer/core/state.py, composer/trainer/trainer.py
1. #223 introduced a bug where algorithms that run on the AFTER_DATALOADER and did a not-in-place modification of state.batch did not also update state.microbatches (which was used for training), so these algorithms were effectively ignored. Fixed this bug by computing the microbataches AFTER the Event.AFTER_DATALOADER event.
2. Removed the `microbatches` and `microbatch_idx` from the state. Instead, algorithms that need to run on smaller batch sizes should use the Event.BATCH_START event instead of Event.AFTER_DATALOADER, since Event.BATCH_START will get the forward-pass sized batch.
=> Fix bug with AFTER_DATALOADER event; remove microbatches from state

composer/utils/object_store.py, tests/callbacks/test_run_directory_uploader.py, tests/test_object_store.py, tests/trainer/test_checkpoint.py
Switched the object store provider to take `key_environ` and `secret_environ` instead of `key` and `secret`, so secrets are not stored in the config and instead must be specified via env variables.
Closes #242
=> Remove secrets from the yaml

composer/algorithms/label_smoothing/label_smoothing.py, composer/core/types.py, composer/trainer/checkpoint.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, composer/yamls/models/classify_mnist.yaml
- Includes more verbose logging for checkpoint saving + loading. Addresses #234 
- Minor fixes to docstrings
Example of checkpoint loading:
```
INFO:composer.cli.launcher:Starting DDP on local node for global_rank(0-0)
/mnt/cota/ajay/composer/composer/cli/launcher.py:105: UserWarning: AutoSelectPortWarning: The DDP port was auto-selected. This may lead to race conditions when launching multiple training processes simultaneously. To eliminate this race condition, explicitely specify a port with --master_port PORT_NUMBER
warnings.warn("AutoSelectPortWarning: The DDP port was auto-selected. "
INFO:composer.cli.launcher:DDP Store: tcp://127.0.0.1:59695
INFO:composer.cli.launcher:Launching process for local_rank(0), global_rank(0)
UserWarning: The given NumPy array is not writeable, and …
```
=> Checkpoint logging and doc fixes

composer/trainer/trainer.py
Every single time I've seen `init_process_group` fail, it's just been because something in initialization is slow with high variance across ranks (usually some sort of network operation). This change will make our lives a bit easier. For reference, DeepSpeed's default is also 30 minutes, which is what I went with here.
=> Dramatically increase default dist_timeout

composer/loggers/tqdm_logger.py, tests/test_logger.py
Will auto-select which `tqdm` to use base on whether its a console or a jupyter notebook. h/t: @moinnadeem 
Fixes #295
=> Use `tqdm.auto` for notebooks

composer/cli/launcher.py, composer/core/engine.py, composer/utils/dist.py
The distributed process group doesn't necessarily need to be initialized when we're doing single-process training, and this can help avoid crashes in certain environments. Note that the DDP initialization code already is a no-op when the distributed process group is not initialized.
Tested by running models with various world sizes (and no explicit world size), and using a print statement to verify whether the model was the original model class or a DDP wrapper.
=> Don't init dist when world_size is 1

composer/trainer/checkpoint.py, composer/trainer/trainer.py
If one process hits a distributed barrier but another one crashes before reaching it, then the process that hit the barrier will hang indefinitely. Distributed barriers do not respond to sigterm. Instead, this PR guards the code in the checkpointer that could raise errors with try/finally, so any exceptions (such as from failed downloads) will be re-propagated AFTER the barrier is released.
Also removed an unnecessary barrier in the trainer.
Closes #290
=> Guard `dist.barrier` in the checkpointer with try/finally

composer/core/__init__.py, composer/core/logging/base_backend.py, composer/core/logging/logger.py, composer/core/time.py, composer/loggers/__init__.py, composer/loggers/file_logger.py, composer/loggers/in_memory_logger.py, composer/loggers/logger_hparams.py, composer/loggers/mosaicml_logger.py, composer/loggers/tqdm_logger.py, composer/loggers/wandb_logger.py, docs/source/core/time.rst, docs/source/loggers.rst, tests/callbacks/test_grad_monitor.py, tests/callbacks/test_memory_monitor.py, tests/callbacks/test_speed_monitor.py, tests/test_logger.py, tests/test_mosaicml_logger.py
1. Added a Timestamp object to `composer.core.time`. The Timestamp object is Tuple that represents a snapshot of state.timer
2. Updated the logging API to pass the Timestamp object rather than (epoch, step).
3. Added an In memory logger that records all logging calls, with easy helpers to the most recent values for each key. This new feature required `Timestamp` objects so it is possible, say, to create a plot of samples or tokens vs a logged value. It also cleans up the API compared to storing (epoch, batch, sample, token) as a non-named tuple.
Closes #294
=> Added In Memory Logger, Timestamp Object

composer/algorithms/cutmix/cutmix.py, composer/algorithms/cutout/cutout.py, composer/algorithms/ghost_batchnorm/ghost_batchnorm.py, composer/algorithms/label_smoothing/label_smoothing.py, composer/algorithms/mixup/mixup.py, composer/algorithms/scale_schedule/scale_schedule.py, composer/algorithms/selective_backprop/selective_backprop.py, composer/algorithms/template.py, composer/datasets/dataloader.py, composer/trainer/trainer_hparams.py, tests/algorithms/test_selective_backprop.py
Replaced required hparams that have template defaults with optional fields, or just removed the template defaults. We really aren't using the templating feature, and if there's a template_default, then it should be a default for functional api users.
Also fixed typing issues in Selective Backprop
=> Removed `template_default` fields in hparams

docs/source/functional.rst
I broke this page in #368 by removing `composer.algorithms.functional`. This PR is a one-line fix in the rst file. Plus I changed `as CF` -> `as cf` in the example because it was right there and I couldn't resist.
=> Fix composer.functional page no longer showing functions

composer/algorithms/augmix/__init__.py, composer/algorithms/augmix/augmix.py, composer/algorithms/colout/__init__.py, composer/algorithms/colout/colout.py, composer/algorithms/cutmix/__init__.py, composer/algorithms/cutmix/cutmix.py, composer/algorithms/cutout/__init__.py, composer/algorithms/cutout/cutout.py, composer/algorithms/randaugment/__init__.py, composer/algorithms/randaugment/randaugment.py, composer/functional/__init__.py, docs/source/algorithms.rst, docs/source/functional.rst, docs/source/method_cards/col_out.md, docs/source/method_cards/cut_out.md, docs/source/method_cards/cutmix.md, docs/source/method_cards/rand_augment.md, tests/algorithms/test_colout.py, tests/algorithms/test_cutmix.py
Addresses #364. Just renames primary data augmentation algorithm functional API functions. Helper functions out of scope since we should probably make most of these private.
Changed names:
`augment_and_mix -> augmix_image`
`colout -> colout_image`, `batch_colout -> colout_batch`
`cutmix -> cutmix_batch`
`cutout() -> cutout_batch()`
`randaugment() -> randaugment_image()`
Splitting this into 2 PRs to keep each one nice and lightweight, since renames for different algorithms are independent.
=> Functional API renaming part 1

composer/models/base.py
Users who just want to run training, and not validate on an external dataset should not need to supply validation and metrics as part of their `ComposerModel`. Especially now that the `eval_dataloader` is an optional argument to our trainer. This PR removes the abstract marker for the two methods in question.
h/t: @A-Jacobson
=> Remove requirement for `validation` and `metrics`

composer/algorithms/scale_schedule/__init__.py, composer/algorithms/scale_schedule/scale_schedule.py, composer/functional/__init__.py, composer/trainer/scale_schedule.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, tests/trainer/test_scale_schedule.py
The upcoming schedulers refactor is easier to do if the trainer treats SSR as a first-class feature. Thus, this PR adds a new `scale_schedule_ratio` param to the trainer. The existing algorithm is still supported, but should eventually be removed.
=> Deprecate scale scheduler algorithm and move to trainer

composer/core/engine.py
Fixes issue with empty log lines when events were triggered with no algorithms present.
=> Fixes empty log lines if no algorithms are run

composer/yamls/algorithms/progressive_resizing.yaml
`resize_targets` is `False` by default in the algorithm. It's used in our KS for resnet50 but not unet, so should probably be `False` in our example yamls.
=> `resize_targets` set to `False` by default

composer/algorithms/cutout/cutout.py
Looks like the `cutout_batch` default hparams got wiped in some merge commit. This one-liner adds them back.
=> Add missing defaults for one function

composer/algorithms/colout/colout.py, composer/algorithms/cutout/cutout.py
Fixing issues that stop the functional API from being used in a reasonable way. E.g., colout and cutout can't be added to a dataset's list of transforms because they *only* work when their input is a batch (not a single image, whether a PIL image or tensor). On the critical path for #326.
Update: [looks like](https://colab.research.google.com/drive/1HIxLs61pyf0ln7MlnrGYvkNHq1uVbNWu#scrollTo=oXfFDF_VUTY6) everything's working now.
=> Get functional API running enough for notebook

composer/cli/launcher.py, composer/utils/run_directory.py
> By default, the run directory contains a timestamp with ":" in its name. If the run directory is uploaded to an object store, any checkpoints within it cannot be used by CheckpointLoader because it parses the load_path as a URL: https://github.com/mosaicml/composer/blob/dev/composer/trainer/checkpoint.py#L93-L99
Closes #442
=> Remove colons from run directory timestamps

composer/models/bert/bert_hparams.py, composer/models/bert/model.py, composer/models/gpt2/gpt2_hparams.py, composer/models/gpt2/model.py, composer/models/transformer_hparams.py, composer/models/transformer_shared.py
It doesn't really make sense for a ComposerTransformer to accept a `transformers.PreTrainedModel`, but a `tokenizer_name: str`. This interface was just too tightly coupled to YAHP.
This remedies the problem by the `__init__` function taking in a `transformers.PreTrainedTokenizer` instead of a `str`.
I also welcome any other suggestions for quality-of-life fixes!
=> Clean up Transformer models __init__ function

tests/trainer/test_checkpoint.py
These tests are causing timeout errors on Jenkins, but not reproduced locally. We will need to investigate, but skipping for now to unblock PRs.
=> Skip ResNet50 + DeepSpeed tests that are timing out

composer/models/unet/unet.py
Instance norm doesn't preserve memory format, i.e., if input is NHWC the output is NWHC. Therefore, instanceNorm pays the cost of NHWC => NCHW while the preceding conv pays the cost of NCHW => NHWC memory format change. 
5.5% improvement in wall_clock_train.
dice (validation): 69.99 (instance norm) 69.33 (batch norm)
=> Make batchnorm default for UNet

composer/trainer/devices/device_gpu.py
PyTorch versions < 1.10 do not have a second argument for autocast: https://pytorch.org/docs/1.9.1/amp.html. This PR fixes a bug introduced by the bfloat PR (#433) where we called torch.cuda.amp.autocast with a second argument (dtype) regardless of the PyTorch version.
=> fix autocast for pytorch < 1.10

composer/datasets/__init__.py, composer/datasets/c4.py, composer/datasets/dataset_registry.py, composer/trainer/trainer_hparams.py, composer/yamls/models/gpt3_125m.yaml, tests/test_dataset_registry.py
This PR adds an adapter for HF streaming datasets, so that we can train with DDP and sharding. There is also a small QoL fix for DeepSpeed.
I've also added a new GPT3-125m YAML which can be the start of our new GPT3 family of benchmarks. I think we should deprecate the GPT2 collection of YAMLs (-52m, -83m -125m) in the near future, say Composer v0.5.
Some TODOs, which can be follow-up PRs:
* Add the rest of the GPT3 family YAMLs
* Update the GPT2 model with QoL fixes
* Update the BERT-base benchmark to use C4
* Deprecate / combine the old `LMDataset` object
=> Add C4 Streaming dataset

composer/__init__.py, composer/core/__init__.py, composer/core/evaluator.py, composer/core/logging/logger.py, composer/core/precision.py, composer/core/serializable.py, composer/core/state.py, composer/core/time.py, composer/core/types.py
For evaluator.py, precision.py, serializable.py, state.py, time.py and types.py in composer.core
=> docstrings improvements for core modules

README.md
The link to the best practices blog post was broken
=> Fix broken "best practices" link

composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/datasets/c4.py
This PR is a quality-of-life improvement for training with the C4 dataset, instead of erroring out and killing the training job, it just overwrites `dataloader.num_workers` before initializing the dataloader.
I expect to relax the `num_workers=1` constraint in the future, but for now it just makes sharding simpler.
=> Let C4 Dataset overwrite `num_workers` if set incorrectly

.readthedocs.yaml, composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/models/ssd/ssd.py, meta.yaml, setup.py
1. This PR adds try..catch for the `pycocotools` imports, so that it's possible to use Composer locally without installing all the requirements. Right now with MCLI this was causing some issues.
2. Remove the hack in the readthedocs build
3. Fix the pycocotools in the meta.yaml to not install by default.
5. Remove wget (this library hasn't been updated since 2015) as a dependency; replace with requests
=> Lazy imports for `pycocotools`

composer/yamls/models/gpt3_350m.yaml, composer/yamls/models/gpt3_760m.yaml
This PR updates our GPT3 YAMLs with sizes >= 125M so that they will run without modification on 8xA100-40GB nodes.
=> Update GPT3-yamls for default 8xA100-40GB

composer/algorithms/alibi/alibi.py, composer/algorithms/augmix/augmix.py, composer/algorithms/blurpool/blurpool.py, composer/algorithms/colout/colout.py, composer/algorithms/cutmix/cutmix.py, composer/algorithms/cutout/cutout.py, composer/algorithms/factorize/factorize.py, composer/algorithms/ghost_batchnorm/ghost_batchnorm.py, composer/algorithms/label_smoothing/label_smoothing.py, composer/algorithms/layer_freezing/layer_freezing.py, composer/algorithms/mixup/mixup.py, composer/algorithms/progressive_resizing/progressive_resizing.py, composer/algorithms/randaugment/__init__.py, composer/algorithms/randaugment/randaugment.py, composer/algorithms/sam/sam.py, composer/algorithms/scale_schedule/scale_schedule.py, composer/algorithms/selective_backprop/selective_backprop.py, composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/algorithms/squeeze_excite/squeeze_excite.py, composer/algorithms/stochastic_depth/stochastic_depth.py
Fixes: #607 .
* All algorithms that have default arguments are not annotated as, for example:
```
alpha (float, optional): <description>. Default: 0.1
```
* Opportunistically cleans up some missing docstrings and type annotations here and there.
=> Add defaults to the docstrings for algorithms

composer/trainer/trainer_hparams.py, composer/yamls/models/gpt3_125m.yaml, composer/yamls/models/gpt3_350m.yaml, composer/yamls/models/gpt3_760m.yaml, tests/trainer/test_checkpoint.py
This is essentially a follow-up from https://github.com/mosaicml/composer/pull/322 - where it was missed that the ZeRO stage would have to be configured differently now. Annoyingly, there was nothing on DeepSpeed's end to catch this issue - but I've at least filed a ticket now: https://github.com/microsoft/DeepSpeed/issues/1809
This is probably not related to #610.
=> Fix ZeRO config

composer/algorithms/hparams.py, composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/algorithms/swa/swa.py, tests/algorithms/test_algorithm_registry.py
This updates SWA to allow batch- and epoch-wise resolution for updating the averaged model. This is exposed to the user via the `update_interval`, a time string denoting how frequently the averaged model is updated (e.g. `'1ep'`, `'5ba'`). The hparam formerly known as `anneal_epochs` has been renamed to `anneal_steps` to reflect the fact that the SWA-specific LR scheduler now operates at the resolution of `update_interval` instead of single epochs.
Excited to get some NLP results, @moinnadeem!
=> Batchwise resolution for SWA

composer/trainer/_checkpoint.py, tests/trainer/test_checkpoint.py, tests/trainer/test_ddp.py
This turned out to be a nasty race condition where rank 0 was able to release its temp dir, where various rank-agnostic checkpoint files were stored, before other ranks had finished using it. The fix is to add another `dist.barrier()`.
I was able to reproduce this locally, which made testing much easier. I wrapped `test_checkpoint` in a dummy fixture that just ran the whole test hundreds of time (commenting out the resnet test, which was slow), which was able to reliably produce plenty of failures. After this fix, I've seen no failures.
=> Fix DeepSpeed checkpointing

composer/datasets/hparams.py
`def initialize_object()` has an improperly indented docstring line that causes rendering problems
=> Fix DatasetHparams, WebDatasetHparams docstring

composer/datasets/c4.py, composer/yamls/models/gpt3_125m.yaml, composer/yamls/models/gpt3_350m.yaml, composer/yamls/models/gpt3_760m.yaml, tests/datasets/test_c4.py, tests/test_dataset_registry.py
This PR modifies the C4 streaming dataset so it will repeat over its underlying data source, until reaching the epoch boundary of `max_samples` provided by the user.
Previously, if `max_samples` were too big, there was a potential bug where the dataset iterator would stop early and our Trainer's time conversions would be incorrect. Also, DDP might not be synced.
To make the repeating HF dataset, I followed the structure of this code: https://github.com/huggingface/datasets/blob/3dfdb054e3636a5784d365bcd65759e5bd697b03/src/datasets/iterable_dataset.py#L394
I could use some guidance here... I have manually tested by creating a `C4Dataset` with a `max_samples` value that I know for sure is larger than the underlying dataset, and have seen that it works. But it takes ~5min to reach that …
=> Update `C4Dataset` to repeat, handle `max_samples` safely

.ci/lint_doctests.sh, Makefile, docker/pytorch/Dockerfile, docs/source/doctest_fixtures.py, setup.py, tests/trainer/test_trainer.py
Installing pyright via npm, as the pip pyright does not appear to pin versions properly.
Closes #733
=> Installing pyright via npm

tests/trainer/test_trainer.py
It occassionally fails on Jenkins with a 2 second timeout. Increasing to 5 seconds.
=> Increase the timeout for test trainer equivalence

composer/algorithms/seq_length_warmup/README.md
Added docs for sequential length warmup
=> Update sequence length warmup documentation

tests/trainer/test_trainer.py
Increased the timeout to 30s, since some tests were failing at a 5s timeout. See #774.
=> Increased the timeout for `test_trainer.py`

README.md
Add the eval dataloader to the readme to show decreasing loss.
PLEASE TEST THIS PR MANUALLY before approving, as it is not covered by Jenkins.
=> Add eval dataloader to the README.md

tests/algorithms/test_colout.py, tests/algorithms/test_cutmix.py, tests/conftest.py, tests/fixtures/dummy_fixtures.py, tests/fixtures/new_fixtures.py, tests/loggers/test_object_store_logger.py, tests/test_nlp_metrics.py, tests/trainer/test_checkpoint.py, tests/trainer/test_ddp_sync_strategy.py, tests/trainer/test_scheduler.py, tests/trainer/test_trainer.py, tests/utils/classifer.py
Motivation behind using a deterministic seed for each test is to avoid test flakiness and ensure that PRs do not fail due to unrelated test failures. Instead, we should configure Jenkins to run nightly regressions across multiple seeds to identify tests that depend on the random initialization, and triage nightly regression errors as appropriate.
1. Added a pytest CLI option `--seed`. If not set, defaults to 0.
2. Added an `autouse` fixture to set the seed automatically before each test.
3. For tests that create instances of the trainer, manually specified the `rank_zero_seed`, as otherwise the trainer would re-seed the rng with `os.random`.
4. Removed the xfail on `test_masked_accuracy`, as the seed is now deterministic.
5. Unrelated cleanup: Removed unused fixtures from `conftest`; …
=> Set the random seed before each test.

composer/core/data_spec.py, composer/datasets/cifar.py, composer/datasets/utils.py, composer/trainer/trainer.py, composer/yamls/models/resnet9_cifar10.yaml
Plan is just add it for Cifar10 first along with taking care of dependencies and installation issues. 
ImageNet will be added in a later PR
Currently this PR is to get high level comments for integration. 
- Should we preprocess data to ffcv format if the datafiles don't exist? 
`apt update; apt install libturbojpeg-dev libopencv-dev` is needed before pip install -e .[ffcv] can work. 
If ffcv can't find opencv4, use `cp /usr/lib/x86_64-linux-gnu/pkgconfig/opencv.pc /usr/lib/x86_64-linux-gnu/pkgconfig/opencv4.pc`
Once this is installed, the following should work. 
Without ffcv: 
`composer -n 1 examples/run_composer_trainer.py -f composer/yamls/models/resnet9_cifar10.yaml --max_duration 1ep --datadir /localdisk/CIFAR10`
With ffcv:
This processes the data to ffcv format first in the /tmp …
=> ffcv integration for cifar10 dataset

README.md
Adds a trainer link to the README, and closes #750 . The other suggestions are also resolved.
=> Add trainer link to README

composer/datasets/imagenet.py
Basic integration for imagenet. Use of ffcv transformations for algorithms will be added in a followup PR. 
`composer -n 1 examples/run_composer_trainer.py -f composer/yamls/models/resnet18.yaml --datadir /localdisk/ImageNet --max_duration=1ep --train_batch_size=256 --train_subset_num_batches=10 --loggers=progress_bar --train_dataset.imagenet.use_ffcv=true --val_dataset.imagenet.use_ffcv=true --train_dataset.imagenet.ffcv_write_dataset=true --val_dataset.imagenet.ffcv_write_dataset=true`
=> ffcv integration for imagenet

composer/__init__.py
I've been using composer in a separate repo, and encountering the following pyright error when doing `import composer`, as opposed to `from composer.foo import bar`:
```python
import composer
_ = composer.optim.CosineAnnealingWithWarmupScheduler
```
```
~/code/tmp ❯ pyright tmp.py
...
Assuming Python platform Darwin
Searching for source files
Found 1 source file
/Users/davis/code/tmp/tmp.py
/Users/davis/code/tmp/tmp.py:3:14 - error: "optim" is not a known member of module (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
Completed in 0.606sec
```
One-liner to reproduce:
```bash
$ echo 'import composer\n\n_ = composer.optim.CosineAnnealingWithWarmupScheduler' > tmp.py && pyright tmp.py
```
The fix is to just `from composer import optim as optim` in `composer/__init__.py`. This …
=> Fix submodule type errors when doing `import composer`

composer/datasets/cifar.py, composer/datasets/ffcv_utils.py, composer/datasets/imagenet.py, composer/datasets/utils.py, scripts/ffcv/create_ffcv_datasets.py
- A script to create datasets into ffcv format from a local dir or webdataset 
- Reorganization of ffcv_dataset function.  
Example: 
CIFAR10 from local disk: 
`python scripts/ffcv/create_ffcv_datasets.py --dataset cifar --split train --datadir /localdisk/CIFAR10 --write_path /tmp/cifar10_train.ffcv --num_workers 64`
CIFAR10 from webdataset:
`python scripts/ffcv/create_ffcv_datasets.py --dataset cifar --split train --remote s3://mosaicml-internal-dataset-cifar10 --write_path /tmp/cifar10_train.ffcv --num_workers 16`
imagenet from local disk:
`python scripts/ffcv/create_ffcv_datasets.py --dataset imagenet --split train --datadir /localdisk/ImageNet --write_path /tmp/imagenet_train.ffcv --num_workers 16`
imagenet from webdataset: 
`python scripts/ffcv/create_ffcv_datasets.py --dataset …
=> Support for webdatasets with ffcv

composer/callbacks/callback_hparams.py
Remove a broken link to an old callback hparams tutorial.
Closes #717.
=> Remove a broken link to an old callback hparams tutorial.

composer/datasets/ffcv_utils.py, composer/datasets/webdataset_utils.py, scripts/ffcv/create_ffcv_datasets.py
1) Webdataset can be specified from a local dir as well. 
2) Use FFCV's internal api to avoid downloading dataset twice. 
Test:
```
python scripts/ffcv/create_ffcv_datasets.py --dataset cifar --split train --remote s3://mosaicml-internal-dataset-cifar10 --num_workers 64
python scripts/ffcv/create_ffcv_datasets.py --dataset cifar --split train --remote /tmp/webdata --num_workers 64
```
=> [FFCV] webdataset from local + download only once

LICENSE
Add copyright, remove boilerplate instructions, remove empty line at the top. Additional goal is to make the Apache 2.0 license automatically detected by GitHub (currently says "View license" instead).
=> LICENSE: copyright and cleanup

composer/cli/launcher.py
1. Multi-node values for the CLI launcher can be specified via environment variables, akin to other common distributed launching tools.
2. A lot more validation to make sure that invalid multi-node configurations cannot be provided.
3. Only one of `node_rank` and `base_rank` needs to be provided when there's a constant amount of processes per node.
4. Another pass on the (internal) documentation for the launcher. In particular, the documentation is simplified for most users by distinguishing the multi-node options from everything else, and not documenting the "actual" placeholder defaults.
`composer -h` now returns:
```
% composer -h
usage: composer [-h] [-n NPROC] [--stdout STDOUT] [--stderr STDERR] [-v] [-m]
[--world_size WORLD_SIZE] [--base_rank BASE_RANK] [--node_rank NODE_RANK] …
```
=> CLI Launcher supports environment variables and tells fewer lies

composer/__init__.py
Version number was never bumped to 0.5.0 upon release. Just updating it now for the next release to avoid that in the future :)
=> Fixing version number

docker/pytorch/Dockerfile
cupy was missing. Adding it in the PyTorch_vision image.
=> Add missing ffcv dependency in pytorch_vision docker image

composer/algorithms/mixup/mixup.py, tests/algorithms/test_mixup.py
This PR fixes the issue with mixup + grad_accum > 1 by switching it to operate on the batch after it has been split. This should be math equivalent to the previous behavior.
Test runs currently gated due to lack of GPUs
[ResNet50-I1k with grad_accum=2 and interpolate_loss=True Accuracy 77.27%](https://wandb.ai/mosaic-ml/cory-mixup-changes/runs/nanpf6er)
=> Switch mixup events to avoid grad accum issues

composer/trainer/trainer_hparams.py
Initialize torch distributed before Dataloaders are created. FFCV Dataloaders make some calls to some functions from dist namespace. 
Test:
`composer -n 8 examples/run_composer_trainer.py -f composer/yamls/models/resnet50.yaml --max_duration 2ep --train_batch_size 32 --datadir /localdisk/ImageNet --loggers progress_bar`
=> Initialize distributed before dataloaders are created

pyproject.toml, tests/trainer/test_trainer.py
As an addendum to #875 (fix mixup and grad accum error):
* adds a test for `grad_accum=2` to the tests of each algorithm x trainer combination, which would catch the error being fixed in 875 earlier.
* silences the third-party (tensorboard) deprecation warnings.
This PR's tests should fail until #875 is merged:
```
=================== short test summary info ====================
FAILED trainer/test_trainer.py::TestTrainerAssets::test_algorithms[ga-2-mixup]
FAILED trainer/test_trainer.py::TestTrainerAssets::test_algorithms_multiple_calls[ga-2-mixup]
```
=> Add test for grad_accum > 2 to the asset tests

composer/models/resnet_cifar/resnets.py
This PR switches ResNet9 to use average pooling rather than max pooling, which has two effects:
1) The model can handle different input sizes, which enables `progressive_resizing`.
2) The reshape before the fully connected layer now plays nicely with `channels_last`, which didn't run before.
These changes also seem to slightly improve accuracy with current hparams.
Runs (5 seeds):
[Current dev: Accuracy 92.93% +/- 0.30 
After change: Accuracy 93.68% +/- 0.22](https://wandb.ai/mosaic-ml/cory-resnet9-speedtest?workspace=user-corymosaicml)
=> Modify ResNet9 benchmark to enable channels_last and progressive_resizing

composer/cli/launcher.py, composer/models/resnet_cifar/resnets.py, examples/run_composer_trainer.py
Fix the launcher script to always print the stdout/stderr of the crashing process. To do so, the stdout and stderr must always be saved to a file. Then, the launcher script can read from the stdout and stderr files to print these to the terminal.
=> Print the stdout/stderr of the crashing process

composer/trainer/trainer.py
Discovered that the loss being logged was `grad_accum` times larger than it should be when using DeepSpeed (any ZERO stage). I think this was due to a typo. Future `trainer.py` refactor should probably have some more explicit names like `state.microbatch`, rather than just `state.batch` which is getting set to minibatches/microbatches in different places.
=> Fix loss logging with DeepSpeed

.ci/Jenkinsfile
On a PR merge into dev, build each and every commit -- not just the latest.
=> Don't use Jenkins milestones on merge builds

composer/loggers/logger_hparams.py, composer/loggers/wandb_logger.py, examples/run_composer_trainer.py
This PR changes a few things to improve WandB arifact logging and make multinode logging more user-friendly. Note that the multi-rank features are only really necesary when using DeepSpeed ZERO.
Changes:
* Move the `rank_zero_only` naming behavior to `WandBLogger`, rather than `WandBLoggerHparams`
* previously, `traner.run_name` was not making its way into the logger
* Stick with WandB Artifacts rather than WandB `.save()`, because the latter doesn't have safe tmpdir+upload+delete_on_finish, which is required for our `LoggerDestination`
* WandB artifact extension is detected based on destination artifact name, not source filename (caused an issue with our temporary YAML file)
Right now, the way I would recommend a user to use the WandB logger with multi-rank is something like this: …
=> WandB multi-rank logging

composer/trainer/trainer_hparams.py
If I am understanding this correctly, the profiler docstrings previously mentioned `prof_trace_handlers`, whereas the code mentions `prof_trace_handlers`. 
This leads to errors and reading the code to figure out why `prof_event_handlers` is not an acceptable key in your YAML.
=> Update Profiler Docstrings

tests/callbacks/test_memory_monitor.py
`make test` fails when run on a GPU machine because `test_memory_monitor_cpu` still picks up on active GPU memory from other tests / concurrent jobs and debugging sessions.
This PR skips `test_memory_monitor_cpu` if GPU devices are available. This should not affect our CI/CD since we run CPU tests in a CPU machine.
=> Fix failing CPU memory monitor test

composer/cli/launcher.py
Killing by process group ID was accidentally killing the launcher script before it could terminate child processes. Instead, the launcher script will attempt the SIGTERM kill with just the PID. If that fails, then it will attempt a SIGKILL kill with the PID and all child process PIDs. This is necessary since, during a SIGKILL, the killed process cannot intercept the signal to manually terminate its children.
This approach also ensures that when the launcher script is killed via SIGKILL by the process group ID, or via SIGTERM by the process ID, all training processes also are killed. If we were to instead give each training process a new process group ID, then killing the launcher script via process group ID would result in zombie training processes, as the SIGKILL would not propagate to …
=> Fix the launcher script

tests/fixtures/new_fixtures.py, tests/loggers/test_logger.py
A logger test that was manually initializing dist configured the timeout to be too low, resulting in timeouts in other tests.
=> Fix Distributed Timeouts

pyproject.toml, tests/fixtures/new_fixtures.py
1. Include a distributed barrier in test setup to ensure that no rank starts any test before other ranks are ready to start it, which could be a cause of random timeouts (e.g. rank 1 starts the next test while rank 0 is finishing up validating the previous test).
2. Exclude fixtures from timeouts. This allows that distributed barrier in 1) to take as long as needed (up to the distributed timeout).
=> Fix random pytest timeouts

composer/datasets/cifar.py, composer/datasets/imagenet.py
We only need one instead of the two hyperparamters for destination file for ffcv.
=> [ffcv] remove extra hyperparameter

composer/algorithms/blurpool/blurpool.py, composer/algorithms/hparams.py, tests/algorithms/test_blurpool.py
BlurPool currently uses the hardcoded heuristic of `in_channels > 16` to prevent bluring the first input layer (essentially blurring the input image). 
This PR exposes that as an argument to surface the behavior and allow it to be configured. This helps with testing blurpool as we can then use existing `SimpleConvModel` (in_channels=8).
NB: unclear to me if we actually want to continue using this heuristic, or if a `ignore_first_layer: bool = True` is more appropriate, as using `min_channels` seems a bit of a hack.
=> Add `min_channels` to blurpool

composer/models/base.py, composer/trainer/trainer.py, tests/models/test_composer_model.py
-  #944 broke `copy.deepcopy(state.model)` and `pickle.dumps(state.model`), since it bound the Logger to the model, and the Logger cannot be serialized.
- Fixed by manually defining `__copy__`, `__deepcopy__`, and `__getstate__` on the `ComposerModel` base class.
- Added a test case
=> Fix `ComposerModel` copying and pickling

composer/algorithms/hparams.py, composer/algorithms/progressive_resizing/progressive_resizing.py, tests/algorithms/test_progressive_resizing.py
Add delay_fraction and pin_sizes hyperparameters to progressive resizing algorithm. Addition of these two new hyperparameters doesn't change the default behavior of progressive resizing. 
delay_fraction allows us  to skip a fraction of training in the beginning and progressive resizing keeps input initial_scale-sized during this period. 
pin_sizes allows us to pin sizes of images to a multiple of pin_sizes, i.e., if pin_sizes is 32 image width will always be a multple of 32 after progressive resizing.
=> Generalize progressive resizing

Makefile
When not in a virtualenv, `python` could point to `python2`. Setting the `PYTHON ?= python3` is a better default.
=> [nit] Default to `python3` in the `Makefile`

composer/algorithms/agc/README.md
Markdown squashed all the lines into one, so this commit wraps``` around the kinda pseudocode.
=> Typo fixes in AGC method card

docker/Makefile, docker/pytorch/Dockerfile
Somehow the `/tmp` folder was getting removed in the Dockerimage. This PR fixes that by not `rm -rf /tmp/*` but rather by removing the specific files written to `/tmp` in the proper build step.
=> Fix docker /tmp folder

.ci/Jenkinsfile
Docker changes should only be pushed if the branch is `dev`, not `main`, as not all dockerfile changes may be cherry-picked in a maintenance release. Since all commits already go on the dev branch, the docker images are already up-to-date, so they should not be updated again when the `main` branch is updated for releases.
=> Only push docker images if the branch is `dev`

.ci/lint_doctests.sh, .ci/test_lint_doctests.py, .pre-commit-config.yaml, CONTRIBUTING.md, Makefile, STYLE_GUIDE.md, composer/loggers/logger_hparams.py, composer/profiler/profiler_hparams.py, composer/trainer/trainer_hparams.py, docs/source/doctest_fixtures.py, scripts/ffcv/create_ffcv_datasets.py, scripts/webdatasets/ade20k.py, scripts/webdatasets/tinyimagenet200.py, setup.py, tests/algorithms/algorithm_test_template.py, tests/algorithms/test_channels_last.py, tests/algorithms/test_selective_backprop.py, tests/trainer/test_trainer.py
- Switched to using pre-commit hooks for pyright, yapf, isort, and some additional checks.
- Removed `make lint` and `make style`; updated docs to direct users to user pre commit
- Updated files that were failing the pre-commit checks. Moved attribute-level docstrings to the module's docstring (via the "Attributes" section, since attributes don't have `__doc__`. Converted non-docstring triple-quote comments to `#` comment notation (since they were being recognized as docstrings) or moved into the class for a class-level docstring.
- Currently disabling the checks that would result in a large diff; will enable later when there are few PRs out to minimize merge conflicts.
Closes #642
=> Pre commit hooks

composer/core/precision.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, tests/trainer/test_trainer.py
1. Move the check requiring DeepSpeed if using `Precision.FP16` to `Trainer.__init__()` from `TrainerHparams.validate()`.
1. Making `get_precision_context` be a no-op if `Precision.FP16` is provided.
1. Added tests to ensure that a) The trainer errors if `Precision.FP16` is used without DeepSpeed, and b) `Precision.FP16` works when using DeepSpeed.
Closes #968
=> Fix FP16 Precision with DeepSpeed

composer/algorithms/agc/README.md
Markdown squashed all the lines into one, so this commit wraps``` around the kinda pseudocode.
=> Improve formatting of Implementation details for AGC

composer/utils/dist.py
* If any distributed variables are set, and they match the single rank defaults, then populate the remaining single rank defaults. Before, if any variables were set, then the reset would not be populated, even if they matched the single rank defaults. An MCLI change that set `LOCAL_WORLD_SIZE` without the other variables broke running single-rank gpu tests.
* Also removed a warning about configuring distributed with just one rank, as this is expected behavior when using DeepSpeed.
Tested this change manually by running:
```python3
import os
from datetime import timedelta
import composer.utils.dist
os.environ['LOCAL_RANK'] = '0'
composer.utils.dist.initialize_dist('gloo', timedelta(seconds=5))
```
(Cannot unit test this, as distributed is configured globally for all unit tests, due to a …
=> Allow partially populated single rank distributed variables by default

composer/algorithms/layer_freezing/layer_freezing.py, composer/datasets/streaming/download.py, tests/algorithms/test_algorithm_resumption.py
* switched algorithm resumption to running on GPUs (faster), and also catches resumption issues with EMA.
* Adds a warning to layer freezing about algorithm resumption. Layer freezing will not be Serialization compatible until we invest in a redesign. Note that trying to save a model with Layer freezing currently fails already due to the freezing not removing params from the optimizer state.
=> Add warnings to Layer Freezing

composer/core/engine.py, tests/test_engine.py
- Track whether `atexit` triggered `Engine._close()`, which indicates whether the Python process is shutting down. If so, do not run `Engine._close()` again via `Engine.__del__()`, as Python machinery (e.g. the ability to do conditional imports, which is done with the WandB callback) is destroyed between when `atexit` and `__del__()` fire when Python exits with an exception.
- Added a test case to verify this fix
=> Fix `atexit()` shutdown procedure

composer/algorithms/hparams.py, composer/algorithms/progressive_resizing/README.md, composer/algorithms/progressive_resizing/progressive_resizing.py
delay_fraction = 0.5 and size_increment=4 provide the best speedup and accuracy.
=> Update defaults and docs for progressive resizing

setup.py
Allow the pip package name in `setup.py` to be specified by an environment variable, `COMPOSER_PACKAGE_NAME`. This change will allow for automatic pip publishing, as we use a different package name when publishing to https://test.pypi.org.
=> Allow the package name to be set via an env variable

docs/source/doctest_fixtures.py
Replaces get fn for `ObjectStore` in doctest fixtures with patching init function, so we can still type check. It's a little hacky, but afaik it's the only way to change the init params while preserving the type.
=> Fix Doc Tests

composer/loggers/wandb_logger.py
Adds support to load checkpoints from wandb logger. 
**Testing:**
Adding unit tests for this is a pain because you need to start saving and loading checkpoints from wandb, so you need to throw in wandb credentials and every time tests are run, we read and write from there. I spent a bit of time playing around with this, but I'm strongly in favor of not adding a unit test for this behavior. It's not ideal, but I think it's far better than constantly writing to wandb with each github action
To verify it works, I ran two runs which save and load from there. Run 1: 
```
composer -n 1 examples/run_composer_trainer.py -f composer/yamls/models/resnet56_cifar10.yaml 
--train_dataset.cifar10.datadir /localdisk/CIFAR10/ 
--val_dataset.cifar10.datadir /localdisk/CIFAR10/ 
--loggers progress_bar …
```
=> Load from wandb logger

docker/pytorch/Dockerfile
#974 didn't fix the missing tmp folder. Instead, let's manually create it.
=> Manually make the /tmp folder in the image

.ci/Jenkinsfile, composer/datasets/__init__.py, composer/datasets/ade20k.py, composer/datasets/coco.py, composer/datasets/dataset_registry.py, composer/datasets/imagenet.py, composer/datasets/streaming/dataset.py, composer/datasets/streaming/download.py, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml, composer/yamls/models/resnet50_streaming.yaml, meta.yaml, pyproject.toml, scripts/mds/ade20k.py, scripts/mds/coco.py, scripts/mds/imagenet1k.py, tests/datasets/test_streaming_ade20k.py, tests/datasets/test_streaming_remote.py, tests/test_dataset_registry.py
This PR adds implementations of Vision datasets using the new `StreamingDataset` class.
Specifically we will add streaming versions of ADE20k, ImageNet1k, and COCO, with more to come later.
Dataset writing scripts are kept out of the Composer core, as they are meant to be used when you have a local copy of the dataset available and are converting it to the `StreamingDataset` format.
=> MosaicML StreamingDataset (Part 2, vision datasets)

setup.py, tests/algorithms/test_torch_export.py
This PR adds simple tests for whether our surgery algorithms are exportable for inference via `torch.fx` or `ONNX`. This is an extension of #926 to other export options. 
`test_torchscript.py` is now renamed to `test_torch_export.py` to reflect the additional options.
Currently, the `torch.fx` option fails for several algorithms because their layers have unsupported control flow. 
With these updates, the current status of export support for **inference** is as follows (X=supported):
|                        | torchscript | torch.fx | ONNX |
|------------------------|-------------|----------|------|
| apply_blurpool         | X           |          | X    |
| apply_factorization    |             | X        | X    |
| apply_ghost_batchnorm  | X           |          | X    |
| …
=> Test for other export options (torch.fx, ONNX)

composer/models/tasks/classification.py, tests/models/test_composer_model.py
`ComposerClassifier` class was not torchscript-compatible due to:
* torchscript does not support `from future import __annotations__`
* torchscript does not support using a variable of type `Any` is a tuple, e.g. 
```
def forward(self, batch: Any):
input, target = batch
```
instead, the type needs to be expliciti: `Tuple[Tensor, Tensor]`.
This PR fixes those issues.
=> make ComposerClassifier torchscriptable

STYLE_GUIDE.md
The docs mention YAHP, but I think we mean YAPF for code formatting.
=> Change YAHP to YAPF in STYLE_GUIDE

composer/trainer/trainer.py
`.fit` warns that no schedulers are set if they are set on `init`. switched warning to check for schedulers from `state.schedulers`.
=> Remove no schedulers warning

composer/datasets/ade20k.py, composer/datasets/coco.py, composer/datasets/imagenet.py, composer/datasets/streaming/dataset.py, composer/datasets/streaming/download.py, composer/datasets/streaming/format.py, composer/datasets/streaming/writer.py, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml, composer/yamls/models/resnet50_streaming.yaml, scripts/mds/coco.py, scripts/mds/imagenet1k.py, tests/datasets/test_streaming_remote.py
Also switch the serialization of bytes_per_sample from i64 to u32, which cuts the index size in half while restricting samples to <4GB
~TODO~ DONE:
* re-generate all StreamingDataset implmentations (ADE20k, ImageNet, COCO), and upload to S3
* change defaults in YAMLs to point to new versions (e.g. `.../mds/1/`)
=> Update serialized format, adding magic and version

composer/trainer/trainer.py
I might be absolutely blind, but I see that we [run `Event.FIT_START`](https://github.com/mosaicml/composer/blob/dev/composer/trainer/trainer.py#L1365) in `_train_loop(...)` but never see `Event.FIT_END` actually run. If correct, then this PR aims to resolve that.
=> Add Event.FIT_END to the training loop

composer/callbacks/speed_monitor.py, tests/callbacks/test_speed_monitor.py
This refactors the `speed_monitor` to ignore validation time, and plots three quantities instead: (a) wall-clock time spent in training, (b) wall-clock time spent in validation, and (c) wall-clock time spent overall. 
Let's limit the scope of this PR to just fixing measuring validation on the current implementation. I agree that the speed monitor needs to be refactored, and can even get some of that in a separate PR today. However, I want to unblock others from starting runs tomorrow.
Correctness:
[Here's a WandB report](https://wandb.ai/mosaic-ml/speed_monitor_testing/reports/Ensuring-SpeedMonitor-Correctness--VmlldzoyMDIwMjE0) where I ablate the size of the validation set with three runs:
1) A baseline that trains for 1000 batches and evaluates every 1000 batches. Therefore, it runs …
=> Speed Monitor Part 1: ignoring validation time from training time

composer/core/engine.py, composer/loggers/wandb_logger.py, tests/test_engine.py
If a user something like this:
```python
cb = MyCallback()
trainer = Trainer(
...
callbacks=cb,
)
trainer.close()
trainer = Trainer(
...
callbacks=cb,
)
```
Then `__del__` for the first trainer will be triggered _after_ the new trainer is constructed. causing `MyCallback` to run `init()` (from the first trainer), `init()` (from the 2nd trainer), `close()` (from the first trainer), and then `close()` (from the second trainer). This ordering is incorrect.
This PR fixes it by: 
* Only calling `Engine.close()` if it has not been invoked already, so the sequence will be `init()`, `close()`, `init()`, `close()`.
* Erroring if the user forgets to call `trainer.close()`, since `__del__` from the new trainer would be invoked _after_ the new trainer would fire `Event.INIT` (it is not possible to …
=> Fix `Engine.close()` and WandB Atexit logic

docs/source/conf.py
Right now references to `transformers.Whatever` and `datasets.Whatever` don't link to the corresponding huggingface classes. This PR is a two-line change to our intersphinx mapping to fix this.
Can verify that links now work on the generated [models.BERT page](https://mosaicml-composer--1075.com.readthedocs.build/en/1075/api_reference/composer.models.bert.model.html?highlight=composertransformer) or [ComposerTransformer](https://mosaicml-composer--1075.com.readthedocs.build/en/1075/api_reference/composer.models.transformer_shared.html#composer.models.transformer_shared.ComposerTransformer) page. [Current docs](https://docs.mosaicml.com/en/stable/api_reference/composer.models.bert.model.html) (without working links) for reference.
=> Add intersphinx references to hf datasets + transformers

composer/trainer/trainer.py, tests/callbacks/test_early_stopper.py, tests/datasets/test_streaming.py
This PR addresses an issue with `grad_accum: auto` due to Composer's internal `state.batch` overriding behavior.
Assume we are in a situation like `train_batch_size: 128`, on 8 GPUs, and `grad_accum: auto`, but in truth we can only fit device microbatches of size `1` (not known ahead of time). So we should expect `Trainer` keep catching OOMs and increasing `grad_accum` until it hits `grad_accum: 16`.
Here's what currently happens:
> We start with `grad_accum = 1` by default.
> On step 0 we have `self.state.batch` == "the device batch", of size 128 // 8 = 16.
> We enter the microbatching loop
> Then `self.state.batch` is overwritten to be "the device microbatch", which is size 16 // 1 = 16
> We OOM, catch it, double the `grad_accum=2`, and start again
> **Here is the bug**: On this …
=> Fix `grad_accum='auto'` microbatch override

composer/models/resnet_cifar/README.md
Fix #1016 
> "Model card should say 160 epochs, not 16 epochs"
=> Update Resnet Cifar README.md

composer/core/state.py, composer/trainer/trainer.py, tests/trainer/test_trainer.py
Implement what was decided during design reivew on https://www.notion.so/Fix-Time-Tracking-d63e5ed67245405ca7c07032c3d5385c
=> Track dataloader samples and tokens; remove `batch_num_samples` and `batch_num_tokens` from the state.

setup.py
Installing composer with `pip install mosaicml[all]` and then performing `import composer` was generating the following error message:
```
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
To fix, this PR forces the protobuf package to be `<3.21.0`.
=> Pin `protobufs<3.21.0` when using `wandb`

setup.py
`traitlets` is required by `testbook`. `traitlets` version 5.2.2 has an import bug, so pinning to 5.1.1, which worked previously.
=> Fix `traitlets` dependency

pyproject.toml
Deprecation or other warnings can occur whenever a new package version is released that we haven't tested against yet (even minor releases). For contributors, that means that their local pytest returns an error on parts of the codebase that is not part of their actual contribution, making it difficult to make progress.
e.g. someone contributing an algo would be forced to fix warnings in esoteric parts of the codebase. Or, end up figuring out how to add filterwarnings to an unrelated test, and make that judgement call.
=> Treat `DeprecationWarning` as a warning in tests, not error

meta.yaml, setup.py
Using old versions of `wandb`results in a protobuf error. This PR pins `"wandb>=0.12.17,<0.13"`.
=> Force `wandb` to version `0.12.17` or greater.

composer/__main__.py, composer/cli/__main__.py, composer/cli/launcher.py, tests/cli/__init__.py, tests/cli/test_cli.py
1. Added the composer version argument to the launcher
2. Fixed `python -m composer` so it runs the launch script
3. Added test cases to ensure the version is printed correctly
4. Added a shebang to the launcher script
5. Removed the re-export of the launcher, since that caused a `RuntimeWarning`
Closes #309
=> Add version to the composer launcher; fixed `python -m composer`

composer/utils/libcloud_object_store.py
Modified `download_object` for the libcloud object store to first download to a tempfile and then rename if successful, as to eliminate partially downloaded corrupted files at the ``destination_path``.
=> Libcloud downloads to a tempfile

composer/datasets/ffcv_utils.py, composer/datasets/streaming/dataset.py, scripts/ffcv/create_ffcv_datasets.py
Add support for writing imagenet dataset in ffcv format using streaming dataset. 
Test:
Imagenet
```
python scripts/ffcv/create_ffcv_datasets.py
python scripts/ffcv/create_ffcv_datasets.py --split val
```
=> Write imagenet in ffcv format using streaming

Makefile, README.md
#1116 broke notebook links in the README.md and replaced `scripts/clean_notebooks.py` with a pre-commit hook; this PR does the cleanup.
=> Fix README.md notebook links; remove reference to old `clean_notebooks` script

pyproject.toml
There's a bug with using `concurrency=multiprocessing` with pytorch dataloader workers, as identified in the streaming dataloader tests that run daily. Disabling multiprocessing coverage reports for now.
Example of bug:
```
python -m coverage run --concurrency=multiprocessing -m pytest --timeout 100000 ./tests/datasets/test_streaming.py::test_dataloader_single_device[False-False-1-False-1] -m "daily"
```
But this works:
```
python -m coverage run -m pytest --timeout 100000 ./tests/datasets/test_streaming.py::test_dataloader_single_device[False-False-1-False-1] -m "daily"
```
=> Disable Multiprocessing Coverage Reports

tests/loggers/test_object_store_logger.py, tests/trainer/test_checkpoint.py, tests/utils/object_store/test_libcloud_object_store.py, tests/utils/object_store/test_object_store.py, tests/utils/object_store/test_object_store_hparams.py, tests/utils/test_file_helpers.py
Currently with `pip install .[dev]`, the pytests will fail for tests that require `libcloud`. This PR adds a bunch of `pytest.importorskip('libcloud')` to the codebase.
Is there a cleaner way to do this, than to annotate every test? Seems like a lot of clutter.
After:
```
============= 1801 passed, 235 skipped, 440 deselected, 43 xfailed, 8 xpassed in 72.81s (0:01:12) =============
```
=> Skip libcloud tests

composer/yamls/models/deeplabv3_ade20k_optimized.yaml, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml
I swear this is the last time. Last week, it was noticed the deeplabv3+ could be trained on 4x the batch size while still maintaining the same performance across SSRs. This gives a modest reduction in training time on a single node, but could pretty impactful in multi-node settings. This also lets us remove sync batch norm.
Wandb for SSR=1: https://wandb.ai/mosaic-ml/landan-dlv3p-baseline/groups/baseline-bs128-ssr1.0/workspace?workspace=user-landanjs
=> Update DeepLabv3+ Baseline Hyperparameters

composer/core/engine.py
This fixes the annoying issue of strange and unique to each run algorithm traces appearing in logs. However, if algorithms of the same name are used multiple times in the same run, logs might not be correct with this fix.
[A run showing what things look like after this change in wandb](https://wandb.ai/mosaic-ml/cory-debug/runs/u3mdtdmv)
=> Fix bug where algorithm names weren't being used to log traces

composer/cli/launcher.py
When using the launcher script, the stack trace would not be printed when the process is terminated via a POSIX signal (e.g. `SIGABRT` -- see #1165). This is to prevent cluttering the logs when the launcher script terminates the process via SIGTERM or SIGKILL.
Instead of skipping the stack trace on all negative exit codes (e.g. all signals), this PR skips the stack trace only when the process was terminated via SIGKILL or SIGTERM, which are the two codes that the launcher script uses to terminate processes.
=> Fix Printing of the Stack Trace on POSIX Signal Exits

composer/trainer/trainer.py
This PR fixes a reported bug where gradient accumulation was always automatic.
Coming along for the ride -> some better logging of the grad accum increases.
=> Only catch OOM if `grad_accum='auto'`

composer/trainer/trainer_hparams.py
Can't forget the docstrings...
=> Fix DeepSpeed typo in docstring

composer/trainer/trainer.py
Currently, the value of `grad_accum` is logged only when it is changed by `grad_accum="auto"`. This PR changes things such that the value of `grad_accum` is logged every step.
Example old behavior:
Example new behavior:
=> Move grad_accum logging to every step

composer/loggers/progress_bar_logger.py, tests/common/compare.py, tests/loggers/test_progress_bar_logger.py
This PR:
* lightly refactors the ProgressBar for code clarity
* renders the progress bar in units of `max_duration`
* fixes interleaving of train/eval progress bars (see: #1191 )
* Adds `current_pbar` property instead of using dictionaries for progress bars
* renames `_ProgressBarLoggerInstance` -> `_ProgressBar` for clarity/bervity. The object is a progress bar ala tqdm, not an instance of the logger itself. 
* Removes ProgressBarLoggerInstanceState, as unneccessary.
* Folds local rank zero guards into `show_pbar` property
`max_duration=10ep`, `eval_interval=1ep`
```
Epoch     0 train 100%|█████████████████████████| 29/29 [00:09<00:00,  3.14ba/s, ...
Epoch     0 val   100%|█████████████████████████| 10/10 [00:00<00:00, 21.35ba/s, ...
```
`max_duration=1000ba`, `eval_interval=10ba`
``` …
```
=> ProgressBar Units

composer/utils/fx_utils.py, tests/utils/test_fx_utils.py
- All parallel linears will be fused. It's not limited to 2. 
- Either all or none should have the bias for as a pre-condition of fusion. 
- If no parallel linears are found, unmodified GraphModule is returned. 
Example,
Before:
After:
CO-402
=> A utility to fuse parallel linear layers in FX-traced models

composer/trainer/trainer_hparams.py, examples/run_composer_trainer.py, setup.py
This PR partially reverts #1195 and removes the `composer_train` entrypoint from the pip package. Decided against including this in the pip package as it is very opinionated (e.g. with wandb config logging) and hides how users should use their own entrypoints.
It was also confusing to use it with the launcher script -- `composer -c composer_train` is unintuitive.
Instead, for users who want to use our example entrypoint with a `pip install` of composer, they can `wget` it from github.com at runtime.
=> Remove the `composer_train` entrypoint; put it back in `examples`

.ci/Jenkinsfile, docker/Dockerfile, docker/build_matrix.yaml, docker/generate_build_matrix.py, docs/source/model_cards/BERT.md
#1197, which introduced composer image staging builds, installs Composer from pypi rather than from github. This PR fixes that by ensuring the modified buildArgs are passed to kaniko correctly.
=> Fix Composer staging dockerimages

composer/utils/object_store/object_store_hparams.py, tests/utils/object_store/test_object_store_hparams.py
This PR allows the SFTP Object Store filepath to be set via an environ when using the yahp codepath. The enviorn defaults to `COMPOSER_SFTP_KEY_FILE` to match what is used by streaming datasets; however, this variable can be overridden via the `key_filename_environ` argument (to support multiple sftp object stores with different keys).
Closes https://mosaicml.atlassian.net/browse/CO-573
=> Set SFTP Object Store Private Key Filepath from an Environ

composer/utils/file_helpers.py
`pbar.update` was called incorrectly -- it was called with the total length, rather than the delta, so it was finishing too quickly and instead showing `O(n^2)` length
Closes https://mosaicml.atlassian.net/browse/CO-577
=> [xs] Fix progress bars in `get_file`

composer/datasets/streaming/dataset.py, composer/datasets/streaming/download.py, tests/datasets/test_streaming_remote.py
This PR allows SFTP urls passed to StreamingDataset to accept the same information (username, port, etc.) that we currently can for our SFTPObjectStore. This also eliminates the need for the `COMPOSER_SFTP_USERNAME` enviornment variable.
=> Cleanup SFTP url parsing for StreamingDataset

composer/trainer/trainer.py, composer/utils/module_surgery.py, tests/algorithms/test_algorithm_resumption.py, tests/utils/test_module_surgery.py
Currently, when we attempt to save/load check points when:
(1) a surgery algorithm has been used that modifies the pytorch otpimizer state
(2) the trainer is using an optimizer that has state (.e.g., adam) 
it fails. 
This fixes it. However, SAM still fails with mismatch and not sure what's the root cause. 
CO-382
=> Fix module surgery for training resumptions with optimizers that save state

composer/datasets/cifar.py, composer/datasets/coco.py, composer/datasets/imagenet.py
Allows algorithms that expect a torchvision-style VisionDataset to work on the streaming dataset implementations.
Closes https://mosaicml.atlassian.net/browse/CO-608
=> Update vision-style `StreamingDataset`s to subclass `VisionDataset`

composer/loggers/object_store_logger.py, composer/utils/object_store/sftp_object_store.py
Treat any dropped SSH/SFTP connection as a transient error.
If the conenct dropped, then recreate and reconnect to the client.
Closes https://mosaicml.atlassian.net/browse/CO-615
=> Treat any dropped SSH/SFTP connection as a transient error

composer/datasets/streaming/download.py
Tested that S3 remote test succeeds:
```
pytest -s -m remote "tests/datasets/test_streaming_remote.py::test_streaming_remote_dataset[val-ade20k]"
```
=> Hotfix for S3 `FileNotFoundError`

composer/datasets/streaming/dataset.py, composer/datasets/streaming/download.py
This PR addresses 2 issues:
1) When multiple processes use a file, one of them downloads the file, and the others wait (by design there should be no download conflicts). When waiting for a compressed file, it is important to wait for the **uncompressed** local file to exist, not the compressed one, because that is when the shard is ready to use.
2) When a remote dataset is missing its`compression.txt` file, the rank0 process notices right away with a `FileNotFoundError` and proceeds. But the other ranks, which are waiting for rank0 to complete it's download, may wait up to 3min (3 tries * 60s) to understand that the file is missing and proceed. The `dist.broadcast` behavior change here will make the init time in this case much faster.
=> Fix StreamingDataset compression with multi-rank

composer/datasets/streaming/dataset.py
This PR simplifies some of the core StreamingDataset logic and improves throughput in situations where the total # of shards and # samples is large. We also fix a bug that used to occur when the download status was set to `NOT_STARTED`.
=> Fix bug in streaming iteration/downloading, refactor

composer/trainer/trainer.py
For the non-deepspeed sections in trainer.py, it seems like the trainer aims to handle models that return a tuple of losses. One issue is that the backwards pass is called on each individual loss which will cause the error:
```
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```
In practice, most people sum multiple losses, then call backwards on the summed losses. This PR …
=> Support sequence of losses in backwards pass

composer/utils/object_store/sftp_object_store.py
Addresses https://mosaicml.atlassian.net/browse/CO-639, which contains the traceback that was caused by SFTP object store errors.
We should also verify that this is the right place to add the exception.
I was able to re-run and have not seen another crash in ~30 minutes, but this exception is pretty rare to being with.
=> Catching ChannelErrors on SFTP Failures

composer/datasets/streaming/dataset.py, composer/datasets/streaming/writer.py
Since our compression metadata is stored in a `.txt` file, it seems to imply that one could easily edit it. For example, I was trying to create some empty `compression.txt` files to upload to our older StreamingDatasets, for cleanliness.
But most text editors add a trailing newline when you try to save `.txt` files. They also display the file strangely if you open it and no newline exists.
What do you guys (@knighton, @milocress) think about adding this newline generally so that `compression.txt` is easily editable?
=> Make `StreamingDataset` compression file easier to write/read

composer/utils/object_store/s3_object_store.py
We have a rare issue that occurs when a user has no S3 credentials, and is trying to use a `StreamingDataset` that is not compressed (no `compression.txt` file present) from a bucket that has all public files.
Our `StreamingDataset` always looks for `compression.txt` and gracefully handles if not found. For filesystems this check is easy but for remote paths like S3, we catch different types of network errors and basically re-interpret them as `FileNotFound`.
It turns out that even if all the `.mds` files are public, the _bucket_ itself is not, so when we try to download `compression.txt`, we don't actually have permission to call `HeadObject` on the bucket and check if the file exists, so we get a 403. 
This PR adds the ClientError 403 to our list of "errors we interpret as FileNotFound"
=> Catch botocore ClientError 403

composer/algorithms/progressive_resizing/progressive_resizing.py
This PR removes the logging from the functional implementation of progressive resizing as it seems unnecessarily verbose
=> Make progressive resizing quieter

composer/trainer/devices/device_gpu.py, composer/yamls/recipes/resnet50_medium.yaml, composer/yamls/recipes/resnet50_mild.yaml, composer/yamls/recipes/resnet50_spicy.yaml, tests/models/test_model_yamls.py
This PR:
* fixes the recipe yamls to work with the latest version of COmposer
* expands our test coverage to include those yamls to prevent future regressions
Note: this is a UX change, as the recipe yamls will now have default ssr ratios, as well as datasets path. @growlix what do you prefer? It's easy to patch the yaml during the test if you would prefer to keep those unfilled.
=> Fix recipe yamls for `v0.8`, add testing

composer/algorithms/stochastic_depth/stochastic_layers.py, composer/utils/fx_utils.py, tests/utils/test_fx_utils.py
Detect residual blocks automatically and replace them with a stochastic version. See attached graphs for how transformation happens on ResNet50. 
~~TODO: Add tests.~~ Done
**Orig:** 
**Split into bottleneck and downsample:**
**Converted with a call to block_stochastic_module:**
=> Automatic Stochastic depth on residual blocks

meta.yaml, setup.py
* Follow up on #1612 to add packaging to the `meta.yaml`.
* Constrain `py-cpuinfo` to a max version of 9.0.0
=> Add packaging to `meta.yaml`; add `py-cpuinfo` max version

composer/datasets/streaming/writer.py, composer/yamls/models/bert-base.yaml, scripts/mds/c4.py
I've got a couple BERT+C4 usability improvements here that I packaged to avoid 3 tiny PRs, but if there's a lot of discussion I can split it up. Opening in draft mode as well.
1) (@knighton) Make the `StreamingDatasetWriter` shard flushing async, which helps overlap work a bit when writing `.mds` datasets. I see a small but meaningful perf improvement, and no more intermittent "pausing" in the progress bar. @knighton
2) (@knighton) Improve our C4 to `.mds` conversion example so that it all happens via streaming and ~saves to compressed `gz` format.~ not doing this right now b/c our compression during writing is way too slow, and we need to use pigz-python.
I added a quick wrapper around the HF dataset to make it multi-worker compatible, and now we don't need to pre-download the dataset …
=> BERT and C4 updates

composer/trainer/devices/device_gpu.py
PyTorch 1.12 disabled TF32 format by default for matmuls.  This could lead to a significant performance regression.
To fix, adding a flag in the `DeviceGPU` class to control whether to set PyTorch's `allow_tf32` flag. By default, Composer will set this to True, for consistent behavior across pytorch versions.
Closes https://mosaicml.atlassian.net/browse/CO-328
=> Default to `allow_tf32=True` for GPU Devices

composer/utils/object_store/object_store_hparams.py, composer/utils/object_store/s3_object_store.py, tests/utils/object_store/object_store_settings.py, tests/utils/object_store/test_object_store.py
This makes it easy to specify a folder-like prefix for objects that are stored in S3. 
This will be pretty important for users who share a bucket for artifacts like checkpoints, but use folders like `my-name/my-project/` within to separate work. 
It will also be important for this to land before connecting ObjectStore with StreamingDatasets (#1248) because the basic unit being referenced is a "folder" that is rarely an entire bucket.
=> Allow object name prefix for S3ObjectStore

composer/datasets/streaming/download.py
Forward slash must be stripped, otherwise the `S3ObjectStore` fails to download files.
Is this bug intentional by the way? I tried doing some local tests and it seems like all our ObjectStore implementations don't do any stripping of the `object_name`.
Will follow up in Slack, but this is also a good reminder that when modifying `StreamingDataset` code, it's always necessary to run the remote tests which actually do a full E2E download from S3 (and can be run even from your laptop!). This is how I noticed something was failing:
```
pytest -s -m remote "tests/datasets/test_streaming_remote.py::test_streaming_remote_dataset[val-cifar10]"            
```
=> Fix S3 remote paths for StreamingDataset download

composer/loggers/progress_bar_logger.py
Makes the progress bar deserialization compatible with `mosaicml<=0.8.0` checkpoints.
=> Checkpoint backwards compatibility for ProgressBar

composer/algorithms/blurpool/blurpool_layers.py, composer/utils/module_surgery.py, tests/utils/test_module_surgery.py
During module surgery, the new layers need a device assignment. The previous code to infer that device had a few bugs:
(1) If the original layer did not have any `parameters()` but had `buffers()`, no device would be found.
(2) If the original layer had no parameters or buffers, no replacement would be done.
This leads to a device mismatch on algorithms such as BlurPool.
This PR will infer the device from the original layer's `parameters` _and_ `buffers`. If no device can be inferred, then the device inferred from the whole model will be used instead.
Also adds a test case for this edge condition.
=> Fix device inference in module surgery

composer/loggers/tensorboard_logger.py
CO-690
This PR:
* Logging to a new file for every flush solves the quadratic complexity issue, where the same file was sent to S3, while it gradually increased in size.
[wandb report](https://wandb.ai/mosaic-ml/evan-tb-test/reports/Tensorboard-Fix-Plots--VmlldzoyMzE0MTEy?accessToken=bnqi0jaawy5xubsfcck9mz1izabzdyom29o34sdp2nn9ovy5vb8o2naq3aeo0rcb)
=> Fix TB Logger + ObjectStore quadratic complexity issue by doing 1 file per flush

examples/run_composer_trainer.py
Fix the logging of hparams to object stores in the `examples/run_composer_trainer.py`. It was likely that the file was not being flushed before uploading, causing an empty file to be uploaded. To fix, switched to using a TemporaryDirectory, and creating a file within the tmpdir that can be properly closed before uploading.
Example of the fix: https://wandb.ai/mosaic-ml/ravi-composer-examples/runs/uexuga9v/files/config.yaml
Closes https://mosaicml.atlassian.net/browse/CO-687
=> Fix logging of hparams to object stores

composer/yamls/models/bert-base.yaml
* Using compressed version of the C4 streaming dataset is causing regression failures
* Pointing the example to the un-compressed version for v0.8.1
* Fixes CO-763
=> [Hot fix] Remove compression from Bert example

composer/trainer/trainer.py, tests/trainer/test_predict.py
This PR adds a `return_outputs` flag to `predict()`, which when set, will move all batch outputs to cpu and accumulate them in a python list when running `predict()`.
Closes https://mosaicml.atlassian.net/browse/CO-765
=> Add a `return_outputs` flag to `predict()`

composer/loggers/wandb_logger.py, composer/trainer/trainer_hparams.py, tests/fixtures/new_fixtures.py, tests/loggers/test_wandb_logger.py
Fix`get_file_artifact` to work on all ranks, not just the rank zero even if `rank_zero_only=True`
This allows for resuming from checkpoints stored in WandB in multi-node settings, even if `rank_zero_only=True`.
Added a `@pytest.mark.remote` test to verify the fix. Verified that this test passed locally.
Closes https://mosaicml.atlassian.net/browse/CO-640
=> Fix `get_file_artifact` in the WandBLogger to work on all ranks

composer/core/engine.py, tests/callbacks/test_image_visualizer.py
Adds a single line of logic into `composer.core.engine` so that `FusedLayerNorm` is last in the algorithm execution order.
This will ensure that any `torch.nn.LayerNorm` modules which are added by other model surgery algorithms are caught by `FusedLayerNorm` and converted into the fused versions.
As a motivating use case, when `GatedLinearUnits` and `FusedLayerNorm` are used together on a BERT model, having `GatedLinearUnits` perform surgery last will result in a model that is roughly 50/50 fused and unfused layernorm instances.
=> Enforce FusedLayerNorm is ordered last

.ci/Jenkinsfile
The composer dockerimage should only be built when merging into dev (or on a pr that does that); it should not be built on release branches, as the correct composer version is not yet published on pypi (and the build will thus fail!)
Closes https://mosaicml.atlassian.net/browse/CO-761
=> [xs] Build the Composer Docker Image only on `dev` branch merges

composer/loggers/progress_bar_logger.py, composer/utils/__init__.py, composer/utils/collect_env.py, composer/utils/misc.py
#1264 broke the progress bars in notebooks. It screwed up the formatting and caused an `io.UnsupportedOperation` error in Colab when calling `sys.stderr.fileno()`.
This PR fixes these issues.
To test, manually pip install this branch in a notebook. For example:
`%pip install 'mosaicml[dev] @ git+https://github.com/ravi-mosaicml/ravi-composer.git@CO-770'`
Closes #1312
Closes https://mosaicml.atlassian.net/browse/CO-770
=> Fix Notebook Progress Bars

composer/loggers/wandb_logger.py
This PR fixes an issue with loading from WandB artifact checkpoints. Previously we had fixed the auto-resume pathway but not a direct load from checkpoint. 
We should probably set up a design review soon @eracah as the WandB Artifact storage is more tricky to deal with than our other object stores.
=> Fix WandB load from checkpoint

examples/huggingface_models.ipynb
The HF fine-tune example is missing an actual read of the model eval accuracy after fine-tuning.
This change adds the code that shows how to read the eval metrics.
=> Update HF example with read of model eval accuracy

docs/source/_templates/autosummary/module.rst, docs/source/conf.py
Cleanup the API Reference to only show the name, and not the fullname, in the title and default description.
Closes https://mosaicml.atlassian.net/browse/CO-786
=> Cleanup API Reference Titles

examples/huggingface_models.ipynb
HuggingFace example did not include a demonstration of saving the fine-tuned PyTorch model parameters.
This commit addresses this and adds saving of the model parameters.
Tested on Colab with `%pip install "mosaicml[nlp] @ git+https://github.com/mosaicml/composer@dev"`, ran successfully.
=> Add save fine-tune model to HuggingFace example

composer/optim/decoupled_weight_decay.py
This PR fixes #1334 and does the following:
* fix bug when `lr=0`
* Fix some typings
* Update `DecoupledAdamW` default values for `weight_decay` and `betas` to be safer
@ravi-mosaicml I'm wondering if I should also go through all the docstrings and clean them up? I see some inconsistent formatting like `weight_decay (float, optional)` and wonder if it should be `weight_decay (Optional[float])`. Let me know what you suggest!
=> Update DWD optimizers

composer/optim/scheduler.py, tests/optim/test_scheduler.py
This PR should close #1077 and add extra tests to catch the edge case when `t_warmup` == `t_max`.
=> Fix scheduler edge cases

composer/profiler/json_trace_merger.py
https://github.com/mosaicml/composer/issues/1270 identified how the trace merger did not work on multi-node training. This PR fixes that by using the local rank zero, rather than the global rank zero, to synchronize timestamps.
Did not add test cases as we do not support multi-node testing.
Closes https://github.com/mosaicml/composer/issues/1270
Closes https://mosaicml.atlassian.net/browse/CO-674
=> Fix the profiler on multi-node training

composer/trainer/trainer.py
Adds cache clearing to auto grad accum, which should help reduce the fragmentation issues people have been seeing. Used a [simple function](https://github.com/pytorch/pytorch/issues/29554) which approximates fragmentation. Picture below shows fragmentation dropping as we call cache clear
```
def compute_memory_fragmentation():
snapshot = torch.cuda.memory_snapshot()
return sum(b['allocated_size'] for b in snapshot) / sum(b['total_size'] for b in snapshot)
```
=> Auto Grad Accum Cache Clearing

composer/trainer/trainer.py
Unsure if microbatch size is a well known term but this information is helpful for folks setting the `eval_batch_size`.
=> Print the microbatch size when using Adaptive Gradient Accumulation

composer/core/callback.py, composer/core/engine.py, composer/core/event.py, composer/core/types.py, composer/trainer/trainer.py, docs/source/getting_started/welcome_tour.rst
Currently, the only point in which `Profiler` adds a marker outside the engine is for dataloader yields. This is messy agent wise because accessing dataloader yield times (for checking if we're dataloader bottlenecked) requires monkeypatching `Profiler`. 
In order to simplify the control plane, we've now added `Event.BEFORE_DATALOADER`. The engine should have enough entry points to control the entire flow without relying on anything else, and this new event helps complete that.
More broadly, `Profiler` is really just a wrapper around inserting callbacks. We should refactor away `Profiler` into callbacks so each trace handler can have its own schedule. This is a broader redesign though that's lower priority since it's mostly to clean up Composer internals as opposed to user-facing changes.
=> Add Event.BEFORE_DATALOADER

composer/utils/inference.py, examples/exporting_for_inference.ipynb
Showcase the use of new exportForInference callback and functional API in the export_for_inference notebook. 
Couple of issues I see:
1) ~~We don't specifically showcase torchscript export. Should we?~~ 
2) Torch.fx part is just dangling at the bottom. Should we keep it or remove?
=> [inference] Update export_for_inference notebook with new APIs

composer/models/resnet/model.py
Resnet warning doesn't filter to see if initializer is provided
=> Fix resnet warnings criteria

composer/trainer/trainer_hparams.py
Hparams by default instantiates `train_subset_num_batches` to -1. However, we only check if its not None when giving a warning
=> Fix hparams error

composer/core/data_spec.py, tests/trainer/test_dataspec.py
This PR:
* adds an informative error if the batch yielded by the dataloader has a non-Tensor element (e.g. cannot retrieve the shape)
* improves test coverage of the `_default_num_samples_in_batch` function.
=> Add informative error for infer batch size issues

composer/models/deeplabv3/README.md, composer/models/deeplabv3/deeplabv3_hparams.py, composer/models/deeplabv3/model.py, composer/yamls/models/deeplabv3_ade20k_optimized.yaml, composer/yamls/models/deeplabv3_ade20k_unoptimized.yaml, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml, examples/streaming_dataloader_facesynthetics.ipynb, tests/common/models.py, tests/models/test_model_registry.py
This is supposed to be similar to the ResNet PR here: https://github.com/mosaicml/composer/pull/1262. 
The `is_backbone_pretrained` and `backbone_url` are replaced in favor of `backbone_weights` which uses PyTorch's new multiple weights API. When torchvision is below 0.13, the respective urls for `IMAGENET1K_V1` and `IMAGENET1K_V2` are hardcoded.
For the future, we need a better interface to be able to use arbitrary pre-trained weights i.e. be able to use weights locally or ones stored in the cloud. I just wanted to get a quick fix to use PyTorch 1.12, but will create a jira for this feature
=> Update DeepLabv3 pretrained weight interface to work with PyTorch 1.12

composer/trainer/trainer.py
Adds `mps` and `tpu` to Trainer docstrings
=> [xs] Add `mps` and `tpu` device to Trainer docstrings

docs/source/trainer/using_the_trainer.rst
added a line about getting current eval metrics from the trainer after training.
stopgap for CO-756. Metrics can also be accessed from the composermodel, but i believe this is the most logical way to access them.
=> current metrics docs

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
1.12.0 -> 1.12.1 comes with some bugfixes, particularly Adam optimizer resumption, that will be good to have.
=> Upgrade to torch 1.12.1

composer/models/resnet/README.md
Updating some information here to match our updated YAMLs and to fix `sgd` -> `decoupled_sgdw`.
=> Update default hparams for ResNet model card

README.md, composer/__init__.py, composer/trainer/trainer.py, docs/source/index.rst, setup.py
Addresses [CO-947](https://mosaicml.atlassian.net/browse/CO-947).
Changes:
- Touched up the pypi blurb
- Has our hero figure from the readme on our docs main page
- Composer module now has a meaningful (if concise) module docstring.
- Various prose edits throughout README
Generated docs [link](https://mosaicml-composer--1422.com.readthedocs.build/en/1422/) for convenience.
=> Clean up prose in key files

composer/trainer/trainer.py
Missing indent for `autoresome` argument in `Trainer` docstring which messed up documentation rendering. Also adjusted length of some lines while I was there.
=> Fix missing indent

composer/utils/__init__.py, composer/utils/inference.py, tests/utils/test_inference.py
Adds 
1. Helper wrapper for dynamic quantization 
2. If scripting fails, we were printing an exception stack trace but still continuing with tracing. Fix this. 
3. Add a test for dynamic quantization. 
closes https://mosaicml.atlassian.net/browse/CO-798
Test:
python -m pytest -k "test_dynamic_quantize" -s
=> Dynamic quantization + minor improvements in inference APIs

setup.py
On our custom GLUE entrypoint, we use multiprocessing to manage fine-tuning in parallel.
However, because our spawned processes cannot spawn further processes, we get this error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/wandb_init.py", line 1043, in init
run = wi.init()
File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/wandb_init.py", line 556, in init
backend.ensure_launched()
File "/usr/local/lib/python3.9/dist-packages/wandb/sdk/backend/backend.py", line 220, in ensure_launched
self.wandb_process.start()
File "/usr/lib/python3.9/multiprocessing/process.py", line 118, in start
assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
```
There are two potential …
=> Upgrade WandB version

composer/utils/object_store/s3_object_store.py
Should be `streaming` not `s3`, as users should do `pip install mosaicml[streaming]`
=> Fix incorrect deps group in `streaming` requirement

.ci/test_lint_doctests.py, STYLE_GUIDE.md, docs/Makefile
This PR:
* add `-q` flag, so only warnings and failures are shown
* add `clean` command that will automatically remove `source/api_reference`
* adjust docs accordingly
* adjust jenkins accordingly
=> Clean up docs Makefile

composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, tests/test_precision.py, tests/trainer/test_trainer_eval.py
Based on discussions in #1429 , it's clear that our Eval API should be updated to be consistent with the Trainer API, eg.
```
trainer = Trainer(
eval_dataloader=...
)
trainer.eval()
```
or
```
trainer = Trainer(
...
)
trainer.eval(
eval_dataloader=...
)
```
Instead, currently the `eval` API is fairly constrained to evaluating a single dataloader/metric, and also requires re-passing in the metrics, even though they have already been defined by the user in the `model`. This PR implements the new Evaluation API.
Todo:
=> Update Eval API

tests/trainer/test_ddp.py, tests/utils/test_batch_helpers.py, tests/utils/test_inference.py, tests/utils/test_iter_helpers.py, tests/utils/test_module_surgery.py
This PR removes the usage of `yahp` in the DDP unit testing.
Coming along for the ride: some readability and stylistic fixes
=> Remove hparams from test_ddp

composer/trainer/trainer.py
Change behavior for `train_metrics` to reset every batch, rather than every epoch.
=> Reset train metrics every batch

composer/core/engine.py, tests/test_engine.py
The engine currently emits extremely verbose debug logs. `pytest` errors invoke debug logging levels, which ends up polluting the pytest output even when engine errors were not the issue.
Instead, this PR hides the debug log behind an `ENGINE_DEBUG` environment variable, which can be set if specialized debugging of the engine is required. This is consistent with our frameworks that use envvars to control specific debugging modes.
=> Squelch Engine debug logs

composer/datasets/streaming/download.py, tests/datasets/test_streaming.py
- Improved the code comments and removed redundant `__all__` from `composer/datasets/streaming/download.py`.
- Update the test code with `joinpath()` API rather than using `/` for robustness
`pre-commit run`
```
PASSED
``` 
`pytest tests/algorithms/test_torch_export.py`
```
=========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/karan/Projects/doc_composer, configfile: pyproject.toml
plugins: pytest_codeblocks-0.16.1, httpserver-1.0.5
collected 137 items / 104 deselected / 33 selected
tests/datasets/test_streaming.py .............................x... …
```
=> Improved comments and improved test code

composer/trainer/trainer.py
As title. It's very complicated to support profiler and auto grad accum since profiler requires all "close" events, eg `AFTER_X`, run. This is hard to do and not worth it right now.
=> Raise ValueError for Profiler + Auto Grad Accum

composer/trainer/trainer_hparams.py, composer/utils/__init__.py, examples/run_composer_trainer.py, pyproject.toml
This PR adds deprecation warnings whenever a user invokes:
* `run_composer_trainer.py` entrypoint
* `TrainerHparams` creation
There are many places in our codebase where we have hparams objects, but this should be sufficient to cover most use cases.
=> add yahp deprecation warnings

composer/loggers/wandb_logger.py
This is a leftover from when we used to store `run_name` in `self.logger`. 
Note: automerge is on
=> Fix run name comment

composer/trainer/trainer.py, composer/utils/__init__.py, composer/utils/inference.py, composer/utils/misc.py
Fixes dev regressions. These were caused by the model being in eval mode for all but the first microbatch.
Now, we set train mode only once (at start of training) and all eval happens within a context which automatically cleans up eval mode.
Regression runs verifying fix: https://wandb.ai/mosaic-ml/mihir-metrics-debug?workspace=user-mihirmosaic (pre-metrics vs. fix-medium)
=> Use eval context

composer/algorithms/sam/sam.py, composer/trainer/trainer.py
Fixes spikes in loss logs from SAM (yellow line) where every SAM pass has 2x the loss logged. Loss should not be computed from the second pass. Bug was introduced [here](https://github.com/mosaicml/composer/commit/8f0d7601eb5a29773f36a5b1aed9c9d8273f94ae) when loss became computed by passing by reference
=> Fix SAM loss

examples/streaming_dataloader_facesynthetics.ipynb
- Running the notebook as it is in google colab throws `ValueError('In the absence of local dataset, path to remote dataset must be provided')`. This is because the existing notebook does not stream the data from a cloud instead using the local dataset. Hence, it requires a minor change for variable `remote_train` and `remote_test` when using the local data.
- Full Traceback is as below:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/composer/datasets/streaming/download.py](https://localhost:8080/#) in download_or_wait(remote, local, wait, max_retries, timeout)
150             else:
--> 151                 dispatch_download(remote, local)
152 …
```
=> Fixed remote path in streaming dataloader facesynthetics jupyter notebook

composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/core/state.py, composer/trainer/trainer.py
As is, this would silently skip certain things (eg metrics calculation) for non-CPU / non-GPU devices. It would catch OOM and then just... return. We should be checking device type at top.
Note: I am assuming AGA doesn't work on TPU and disabling, but @hanlint  feel free to change if you think it should work / is something you've tested
Update: Also moved aga check to state so seq length warmup does this properly
=> Rework auto grad accum checks

composer/datasets/streaming/dataset.py
This fixes issue CO-1071
The problem is that we were expecting the wrong exception (for when the dataset is on localdisk), but actually each cloud backend will throw its own exception for the missing file.
=> Fix compression file remote download exception handling.

composer/callbacks/checkpoint_saver.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, composer/yamls/models/bert-base.yaml, docs/source/doctest_fixtures.py, docs/source/notes/resumption.rst, docs/source/trainer/artifact_logging.rst, docs/source/trainer/checkpointing.rst, docs/source/trainer/logging.rst, docs/source/trainer/using_the_trainer.rst, examples/checkpoint_autoresume.ipynb, examples/checkpoint_with_wandb.py, examples/exporting_for_inference.ipynb, examples/glue/glue_entrypoint.ipynb, examples/glue/glue_example.yaml, examples/glue/nlp_trainer_hparams.py, examples/glue/run_glue_trainer.py, examples/imagenet/train_resnet_imagenet1k.py, examples/training_without_local_storage.ipynb, tests/algorithms/test_algorithm_resumption.py, tests/test_events.py, tests/trainer/test_checkpoint.py, tests/trainer/test_trainer.py
1.  Rename arguments
1. `Trainer.save_folder` -> `Trainer.checkpoint_save_path`
2. `Trainer.save_interval`  -> `Trainer.checkpoint_save_interval`
3. `CheckpointSaver.folder` -> `CheckpointSaver.checkpoint_save_path`
4. `Trainer.save_num_checkpoints_to_keep` -> `Trainer.num_checkpoints_to_keep`
5. `CheckpointSaver.filename` -> `CheckpointSaver.checkpoint_filename`
6. `CheckpointSaver.latest_filename` -> `CheckpointSaver.latest_checkpoint_filename`
2. Along for the ride
*  Add skip tests for uninstalled modules (wandb and libcloud)
[PR Part 2](https://github.com/eracah/evan-composer/pull/1)
=> Checkpointing Interface Refactor Part I: Renaming Arguments

composer/core/evaluator.py, tests/trainer/test_trainer_eval.py
- User can now pass the `'<*>dur'` or `Time(<value>, TimeUnit.DURATION)` as `eval_interval` during training.
- For example, `eval_interval` as `0.1dur` with `max_duration` as `20ep` (20 Epochs) means that evaluation would get executed at every 2 epochs with total of 10 evaluations during the whole training process.
- There are multiple ways where user can define a combination of `eval_interval` and `max_duration`.
| No.  | eval_interval                 | max_duration | Description                              |
| ---- | ----------------------------- | ------------ | ---------------------------------------- |
| 1    | '0.1dur'                      | '50ep'       | Perform evaluation at every 5 epochs     |
| 2    | '0.05dur'                     | '1000ba'     | Perform evaluation at every …
=> Update evaluate_periodically() when eval interval is of type Duration

composer/datasets/ade20k_hparams.py, composer/datasets/coco_hparams.py, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml
- Add a ADE20K and COCO v2 dataset behind a version flag
- Old PR with a similar change for reference https://github.com/mosaicml/composer/pull/1507
=> Add ADE20K and COCO v2 dataset behind a version flag

meta.yaml, setup.py
- Composer CI unittest is failing `AttributeError: module 'distutils' has no attribute 'version'`. This is because distutils Version classes are deprecated and recommendation is use `packaging.version` instead but the changes is not controlled by us as it is getting originated from [PyTorch Tensorboard code](https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/__init__.py#L2).
- Recommendation step mentioned in `https://github.com/pytorch/pytorch/issues/69894` is to pinned `setuptools` to `59.5.0`.
- There is already a tracking issue in PyTorch to fix this issue `https://github.com/pytorch/pytorch/issues/84712`.
=> Pinned setuptools version to fix distutils version error

composer/utils/dist.py, composer/utils/file_helpers.py, tests/utils/test_file_helpers.py
Previously, if `NODE_RANK` was not set, formatting of files would fail, even though `{node_rank}` was not even in the format string.
This PR modifies the formatting in less strict mode, and will only error if requested variable is not set and also not in the format string.
Fixes #1511
=> Less strict name formatting

composer/datasets/ade20k_hparams.py, composer/datasets/c4_hparams.py, composer/datasets/cifar_hparams.py, composer/datasets/coco_hparams.py, composer/datasets/imagenet_hparams.py, composer/utils/__init__.py
- Defaulting streaming dataset version to 1
- Added a deprecation warning if using streaming dataset version 1
- Make `DeprecationWarning` `stack_level` to 2 since the caller calls a function wrapper.
=> Defaulting streaming dataset version to 1 and add a deprecation warning

docker/Dockerfile, docs/source/conf.py
* Previously relying on installing pandoc through the documentation build 
* PyPandoc PyPi wrapper seems to be unreliable, at the time of this PR the `download_pandoc()` function is broken
* Solution: Install pandoc directly in the Docker image, will leave the conf.py as is to handle local builds
=> Add Pandoc to Docker images, bump version to 2.19.2

composer/trainer/trainer.py
As above. When running with DeepSpeed and GradMonitor throw an error:
`Traceback (most recent call last): File "/workdisk/brandon/composer_git/scratch/run_composer_trainer.py", line 76, in <module> _main() File "/workdisk/brandon/composer_git/scratch/run_composer_trainer.py", line 46, in _main trainer = hparams.initialize_object() File "/workdisk/brandon/composer_git/composer/trainer/trainer_hparams.py", line 515, in initialize_object trainer = Trainer( File "/workdisk/brandon/composer_git/composer/trainer/trainer.py", line 1051, in __init__ raise TypeError('GradMonitor is not supported with DeepSpeed because DeepSpeed clears ' TypeError: GradMonitor is not supported with DeepSpeed because DeepSpeed clears the gradients before in the last call to .backward …
=> Adding in erroring for when using GradMonitor and DeepSpeed

composer/loggers/cometml_logger.py
- Change main comet link to point to the main site instead of the docs
- Add query params to all comet links
Items 1 and 5 in CO-1104
=> Update comet links to include query params and point to main site

composer/loggers/cometml_logger.py, tests/loggers/test_cometml_logger.py
- Call experiment.end in post_close
- Log a Created from value to CometML
- Refactor test to be more complete
Items 2 and 3 from CO-1104
Also fixes CO-1160
Run from v0.10.0 branch: https://www.comet.com/mosaic-ml/daniel-test/92f7bd9ec1a948408fccfd59eb47f0bc?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&xAxis=step
Run from the commit in this PR on top of v0.10.0 (not on top of dev, because MNIST example is broken on dev right now): https://www.comet.com/mosaic-ml/daniel-test/dca086a1a5b1453f9640d9c165d38bb4?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&xAxis=step
Can see that the run on v0.10.0 branch (1:27pm) has an extra ghost experiment, while the run with this PR (1:22pm) does not 
BERT run from this PR: …
=> Add missing _enabled flag, post_close, and clean up comet ml tests

composer/trainer/trainer.py
We originally added `eval_batch_split` as a feature similar to `grad_accum` to be run when evaluating metrics. This is currently used in eval mode and in some algorithms.
However, with the metrics refactor, we now run train metrics at a microbatch level. This uses the cached output from the forward call in that microbatch level. Now, `eval_batch_split` is no longer needed in train metrics. Further, if it is triggered, it will actually cause an error as composer still returns the cached outputs. Instead, we should let any OOMs here raise all the way up to auto grad accum level.
=> Remove eval batch split

composer/callbacks/image_visualizer.py
Resolves an issue where `ImageVisualizer` was not logging images to w&b with a step. This caused an issue because w&b auto increments step on every log call if you don't pass it in.
Fixes CO-1169.
Experiment before the fix (note that `metrics/eval` is not present: https://wandb.ai/mosaic-ml/daniel-debug/runs/2sbl8ujb
Experiment after the fix (note that `metrics/eval` is present, but everything else is the same): https://wandb.ai/mosaic-ml/daniel-debug/runs/1vt8vmea
Spawned tickets:
- CO-1181: Add a unit test, not including in this PR because it is a hot fix.
=> Add step explicitly to ImageVisualizer logging calls

tests/fixtures/new_fixtures.py
Removes unused fixture, which likely was a leftover from after we switched to the inbuilt `tmp_path` fixture.
N/A
=> Remove unused fixture

composer/models/huggingface.py
HuggingFace model output is a dict or a tuple based on `use_return_dict` config. For loss/eval_forward we assume that it's a dict. Fix this. 
TEST: 
Model with config that has `return_dict=True` works fine.
=> fix loss and eval_forward for HF models

examples/training_without_local_storage.ipynb, setup.py
removes tensorflow-io as a requirement and adds tensorflow-io import to `examples/training_without_local_storage.ipynb`
=> Remove tensorflow-io from setup.py

composer/callbacks/checkpoint_saver.py, composer/callbacks/mlperf.py, composer/loggers/__init__.py, composer/loggers/file_logger.py, composer/loggers/in_memory_logger.py, composer/loggers/logger.py, composer/loggers/logger_destination.py, composer/loggers/logger_hparams_registry.py, composer/loggers/object_store_logger.py, composer/loggers/progress_bar_logger.py, composer/loggers/tensorboard_logger.py, composer/loggers/wandb_logger.py, composer/profiler/json_trace_handler.py, composer/profiler/torch_profiler.py, composer/trainer/trainer.py, composer/utils/inference.py, docs/source/doctest_fixtures.py, docs/source/trainer/artifact_logging.rst, examples/getting_started.ipynb, examples/run_composer_trainer.py, tests/loggers/test_file_logger.py, tests/loggers/test_logger.py, tests/loggers/test_object_store_logger.py, tests/loggers/test_wandb_logger.py, tests/trainer/test_predict.py
Removes the `should_log_artifact` which was unused as far as we know, and would require a user writing a custom filter function that takes in state and `LogLevel` to decide whether to log an artifact. Also, the `WandBLogger` did not support this argument. `should_log_artifact` was also the only use of `LogLevel`, so that has been removed everywhere.
Closes CO-1189
Relates to CO-1167
Manually tested saving (loading) checkpoints to (from) WandB and S3.
=> Remove log level and should_log_artifact

composer/trainer/dist_strategy.py
One-line fix for [CO-1197](https://mosaicml.atlassian.net/browse/CO-1197).
Right now, if your `min_params` for fsdp is a string like '1e8', this line throws. I encountered this when using our public GPT benchmarks.
=> Add more robust casting to int for fsdp min_params

docs/source/notes/distributed_training.rst
Fixes minor typo in deepspeed docs
=> Deepspeed Docs Typo

docs/source/composer_model.rst
I should have caught this earlier... I couldn't find `build_model` in mmdet, but `build_detector` worked
=> Fix mmdet typo

pyproject.toml, setup.py
Based on user request, updating `torchmetrics` to `v0.10` upper limit.
`v0.10` introduces some major API changes to the classification metrics, but they should be backwards compatible. We will need to adjust the code logic when torchmetrics releases `v0.11`.
=> update torchmetrics requirement

composer/algorithms/blurpool/blurpool.py, composer/algorithms/blurpool/blurpool_layers.py
Previously, applying blurpool multiple times caused failures. This now makes it idempotent (useful for agent).
[CO-1213](https://mosaicml.atlassian.net/browse/CO-1213)
=> Blurpool idempotent

composer/cli/launcher.py
Remove warning re. race condition when `master_port` is auto selected. I don't think there is any race condition involved as the args are constructed in the main thread, before any subprocesses are launched. There would only be a race if the toplevel command `composer ...` itself was launched in multiple processes at once, which should never be the case...
[CO-1230]
[CO-1230]: https://mosaicml.atlassian.net/browse/CO-1230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove warning when `master_port` is auto selected

composer/trainer/trainer.py
Auto grad accum used to fail if it crashed in backwards pass as the graph was leftover. This cleans it up.
[CO-1117 ](https://mosaicml.atlassian.net/browse/CO-1117)among others.
No tests since it's too hard to reliably repro in a unit test.
=> Remove Graph in Auto Grad Accum

composer/callbacks/early_stopper.py, composer/callbacks/mlperf.py, composer/callbacks/threshold_stopper.py, composer/core/state.py
Adds a `state.stop_training()` method for algorithms and callbacks to gracefully stop training (finishing the rest of the events in the current batch and any scheduled evals and epoch ends). The EarlyStopping and MLPerf callback now uses this interface instead of setting the max duration itself.
=> add stop method

CODEOWNERS
As people add new algorithms, it's important that we ensure they are compatible in agent. I've run into several problems with new additions that had edge cases which could have been avoided if I was aware of them, either by adding mitigations in agent (eg blacklist incompatabilities) or suggesting alternative solutions (`required_on_load=True`). I'd like to be added to codeowner for algorithms so I'm pinged whenever someone puts something new out so I don't keep having to go back and hotfix issues
=> Add mvpatel2000 as codeowner for algos

composer/callbacks/speed_monitor.py
Adjusts speed monitor to start tracking at `BEFORE_DATALOADER` instead of `BEFORE_BATCH`. This resolves issues with dataloader bottlenecks being potentially masked. Note that currently it should still work since data transfer is done async, but to be safe, we should start the clock on `BEFORE_DATALOADER`.
=> Adjust speed monitor

docs/source/notes/resumption.rst
The doctests are extremely difficult to debug. The logs are different every time I run them locally, get swallowed when the doctest errors, and the offending doctest only fails some of the time. I couldn't figure it out, so I basically removed the offending doctest since this is blocking all CI. I can't be certain, but I believe the issue is limited to the doctests, because the normal tests pass, and I ran the doctest code in an ipython outside of the doctests and it worked consistently. If someone feels like they have a better handle on the doctests, they may want to try to figure this out.
Fixes [CO-1290](https://mosaicml.atlassian.net/browse/CO-1290)
=> Attempt to fix flaky doctest

docs/Makefile
- Fixed html path for make host command for docs. It should be `_build/html` instead of `_build/_html`
=> Fixed html path for make host command for docs

composer/loggers/progress_bar_logger.py
In ProgressBarLogger: checks to see if `log_to_console` or `progress_bar` is True before logging hyperparameters.
Especially helpful for decreasing verbosity in doctests, where `log_to_console` and `progress_bar` are set to False
Before in doctests:
```
[hyperparameter]: num_nodes: 1
[hyperparameter]: num_cpus_per_node: 1
[hyperparameter]: rank_zero_seed: 3942616347
```
After:
```
```
fixes CO-1284
=> Fix hyperparameters logged to console even when progress_bar and log_to_console are False

examples/imagenet/train_resnet_imagenet1k.py
Scales the ImageNet example normalization values by 255 since `pil_image_collate` results in inputs with values in between 0-255 instead of 0-1 (when using `ToTensor`). Also added a comment clarifying the differences
Fixes https://github.com/mosaicml/composer/issues/1634
=> Fix ImageNet Example normalization values

CODEOWNERS, docs/source/doctest_fixtures.py
Changes to logging level to WARN for doctests. This reduces the verbosity of doctests and makes it easier to see your error.
CO-1285
=> Changed default logging to WARN for doctests

composer/loggers/progress_bar_logger.py, examples/imagenet/train_resnet_imagenet1k.py, examples/run_composer_trainer.py
Lazily logs hyperparameters to console and pretty prints them exactly like the yahp entrypoint does.
Before:
```
[hyperparameter]: seed: 42
[hyperparameter]: deterministic_mode: False
[hyperparameter]: dist_timeout: 300.0000
```
After:
```
******************************
Config:
algorithms: null
autoresume: false
callbacks:
lr_monitor: {}
speed_monitor:
window_size: 100
console_stream: stderr
dataloader:
num_workers: 8
persistent_workers: true
pin_memory: true
prefetch_factor: 2
timeout: 0.0
ddp_sync_strategy: null
deepspeed_config: null
deterministic_mode: false
device:
gpu:
allow_tf32: true
device_id: null
dist_timeout: 300.0
eval_batch_size: auto
eval_interval: 1ep
eval_subset_num_batches: -1
evaluators: null
grad_accum: auto
grad_clip_norm: -1.0
load_ignore_keys: null …
```
=> Lazy Logging +  pretty print dict for hparams

docs/source/_templates/base.html
With indexes starting to include other projects - like streaming - we need a way to filter out search results for those projects
=> Search index filtered by project

examples/streaming_dataloader_facesynthetics.ipynb, tests/test_notebooks.py
The three notebook failures:
- `training_without_local_storage`: seems to not have the correct s3 credentials, skipping for now, created a JIRA (https://mosaicml.atlassian.net/browse/CO-1318)
- `streaming_dataloader_facesynthetics`: gets killed by jenkins, works locally, not sure why, created a JIRA (https://mosaicml.atlassian.net/browse/CO-1315)
- `huggingface_models`: force redownload of glue dataset to fix stale dataset issue, should pass now
=> Notebooks part 2

composer/metrics/map.py, composer/metrics/metrics.py, composer/metrics/nlp.py, composer/models/ssd/ssd.py
Newer version of torchmetrics can be faster if we update our custom metrics.
Composer generating extra warning
TEST:
No warning with this change. 
```
import torch
from torchmetrics.utilities import check_forward_full_state_property
from composer.metrics import MaskedAccuracy
batch_size = 16
num_classes = 10
generated_preds = torch.rand((batch_size, num_classes))
true_labels = torch.randint(low=0, high=num_classes - 1, size=(batch_size,))
m = MaskedAccuracy(ignore_index=0)
m.update(generated_preds.float(), true_labels.float())
```
```
import torch
from torchmetrics.utilities import check_forward_full_state_property
from composer.metrics import MaskedAccuracy
batch_size = 16
num_classes = 10
generated_preds = torch.rand((batch_size, num_classes))
true_labels = torch.randint(low=0, …
```
=> Faster metrics calculations + Fix warnings added by the new version of torchmetrics

composer/algorithms/gated_linear_units/gated_linear_units.py
=> Update glu check

composer/cli/launcher.py, composer/trainer/trainer.py
The timeout variable was being ignored before. We should actually use it by setting the appropriate env vars. From Pytorch Dist docs:
"""
– Timeout for operations executed against the process group. Default value equals 30 minutes. This is applicable for the gloo backend. For nccl, this is applicable only if the environment variable NCCL_BLOCKING_WAIT or NCCL_ASYNC_ERROR_HANDLING is set to 1.
"""
Also updates default dist_timeout to be same as what Pytorch has (30 min).
[CO-1356](https://mosaicml.atlassian.net/browse/CO-1356)
=> Add nccl env var

composer/loggers/progress_bar_logger.py
Fixes epoch # when calling eval before epoch 0
[CO-1383](https://mosaicml.atlassian.net/browse/CO-1383)
=> Fix eval timestamp

composer/loggers/wandb_logger.py, tests/loggers/test_wandb_logger.py
When WandB is disabled, many things are instances of `wandb.sdk.lib.disabled.RunDisabled`, which looks like this
```
class RunDisabled(str):
def __init__(self, *args, **kwargs):
object.__setattr__(self, "___dict", {})
def __add__(self, other):
return self
def __sub__(self, other):
return self
def __mul__(self, other):
return self
def __truediv__(self, other):
return self
def __floordiv__(self, other):
return self
def __mod__(self, other):
return self
def __pow__(self, other, modulo=None):
return self
def __lshift__(self, other):
return self
def __rshift__(self, other):
return self
def __and__(self, other):
return self
def __xor__(self, other):
return self
def __or__(self, other):
return self
def __iadd__(self, other):
return self
def __isub__(self, other):
return self
def __imul__(self, …
```
=> Return empty dict if wandb disabled

composer/loggers/remote_uploader_downloader.py, composer/trainer/trainer.py, tests/trainer/test_checkpoint.py, tests/trainer/test_trainer.py
Adds errors so that users should not be able to hit edge case bugs. See linked issues.
@mvpatel2000 I think I can fix the symlink/formatting issue (CO-1272), but wanted to get these in now for your full pipeline testing.
Closes [CO-1365](https://mosaicml.atlassian.net/browse/CO-1365?atlOrigin=eyJpIjoiMmRhNWViNjU4ZGMwNGM1MTgwMzUzZmMzMWZkOWRjZDMiLCJwIjoiaiJ9).
Relates to [CO-1270](https://mosaicml.atlassian.net/browse/CO-1270) and [CO-1272](https://mosaicml.atlassian.net/browse/CO-1272)
=> Autoresume related error messages

composer/algorithms/ema/ema.py
This PR cleans up the `_move_params_to_device()` function in EMA to account for `param_list` and `buffer_list` no longer existing after #1524. This was causing errors with Pyright 1.1.277. EMA functionality be identical after this change.
=> Fix typing in EMA's _move_params_to_device()

composer/callbacks/checkpoint_saver.py, tests/trainer/test_checkpoint.py
Adds support for `Path` objects alongside `str`, per #1573. Additional tests were added to explicitly test `__init__` of `CheckpointSaver`, since #1573 talks about subclassing.
- Related to #1573
=> Add support for Path in CheckpointSaver

composer/trainer/trainer.py, tests/trainer/test_trainer_eval.py
Checks to ensure `eval_subset_num_batches` is specified if using infinite dataloader
[CO-1416](https://mosaicml.atlassian.net/browse/CO-1416)
=> Add inf eval check

composer/trainer/trainer.py, tests/trainer/test_trainer_eval.py
`eval_microbatch` was a local variable, which meant that modifying `state.batch` on `EVAL_BEFORE_FORWARD` did not successfully modify the batch. This PR fixes that to match the behavior in the training loop.
Fixes [1420](https://mosaicml.atlassian.net/browse/CO-1420)
=> Assign eval microbatch to self.state.batch

composer/core/state.py, composer/utils/__init__.py, composer/utils/collect_env.py, docs/source/trainer/checkpointing.rst, tests/test_state.py
Adds composer version to a `metadata` section of the state dict. This will allow us to do compatibility checks in the future, and also debug checkpoints that may be broken.
Is a start to [CO-1428](https://mosaicml.atlassian.net/browse/CO-1428)
=> Add composer version state

composer/trainer/trainer.py, composer/utils/__init__.py, composer/utils/file_helpers.py, tests/loggers/test_remote_uploader_downloader.py, tests/utils/test_file_helpers.py
I have had to write code that autoparses the URI to create an `S3ObjectStore` and then calls `get_file` with that newly created object store a couple of times, and the util to pull huggingface tokenizer/model out of a composer checkpoint is going to need to do the same, so I added the same auto parsing support as in trainer to the `get_file` function. It shouldn't change any behavior of any existing code interacting with `get_file`.
Manual tested that I can download a file from S3 using this, and also that checkpointing/autoresume from S3 still works.
Part of [CO-1110](https://mosaicml.atlassian.net/browse/CO-1110)
=> Adds auto object store creation to `get_file`

composer/devices/device_gpu.py, tests/test_device.py
Fixes a bad None check.
Fixes [CO-1456](https://mosaicml.atlassian.net/browse/CO-1456?atlOrigin=eyJpIjoiNzMwOTMzYjBiYjRmNDU0OTg1MDI3ODI0MDNkY2ZmODgiLCJwIjoiaiJ9)
=> Device id none

docker/Dockerfile
Now that flash attention has tags, we should use a release tag instead of a frozen fork.
[CO-1455](https://mosaicml.atlassian.net/browse/CO-1455)
=> Switch flash attention to tag

composer/trainer/trainer.py, tests/trainer/test_trainer.py
Removes long deprecated code for grad clip norm.
Along for ride, forgot to put deprecation tag for grad accum in docs
[CO-1439](https://mosaicml.atlassian.net/browse/CO-1439)
=> remove grad clip norm

composer/core/engine.py
Fixes memory not being freed with object deletion. 
Experiment training resnet twice in same python process
Before:
After: 
[CO-1443](https://mosaicml.atlassian.net/browse/CO-1443)
=> unregister

tests/models/test_hf_model.py
New HF version changed whether a certain key is present on the tokenizer representation. If this becomes a recurring problem, I can revisit the tests that rely a bit on internal HF tokenizer details.
=> Fix hf tokenizer test for new hf version

composer/utils/collect_env.py
The call `cpuinfo` is apparently kind of slow. Since we call it inside of `composer_collect_env` (which is called inside of `state.state_dict()`), it gets called a lot of times during the tests, particularly while checkpointing. Looks like it cut total PR time down from 26m to 17m.
Closes [CO-1469](https://mosaicml.atlassian.net/browse/CO-1469)
=> cache call to cpuinfo

.ci/test.sh
Adds a duration arg to pytest so that if tests randomly slow down, a developer can at least see the slowest tests to look for a dramatic change.
Here is what it looks like in the logs:
N/A
=> Add durations arg to pytest

composer/trainer/dist_strategy.py
Updates the supported FSDP config flags in composer to include:
- sync_module_states
- forward_prefetch
- limit_all_gathers
Addresses:
[CO-1487](https://mosaicml.atlassian.net/browse/CO-1487)
Tested locally in LLM foundry (trains for a few gradient steps):
```
FSDP: Using sharding_strategy=ShardingStrategy.FULL_SHARD
FSDP: Using cpu_offload=None
FSDP: Using mixed_precision=MixedPrecision(param_dtype=torch.bfloat16, reduce_dtype=torch.bfloat16, buffer_dtype=torch.bfloat16, keep_low_precision_grads=False)
FSDP: Using backward_prefetch=BackwardPrefetch.BACKWARD_POST
FSDP: Using min_params=100000000
FSDP: Using activation_checkpointing=False
FSDP: Using activation_cpu_offload=False
FSDP: Using sync_module_states=True
FSDP: Using forward_prefetch=True
FSDP: Using limit_all_gathers=True
```
=> Updating FSDP supported config flags

docs/source/composer_model.rst, docs/source/trainer/evaluation.rst
Removes a couple of references to `validate` in the docs.
Closes [CO-1506](https://mosaicml.atlassian.net/browse/CO-1506)
=> Remove references to validate in docs

composer/core/evaluator.py, tests/trainer/test_trainer_eval.py
If you accidentally pass a string to `Evaluator` for `metric_names`, you get a semi nasty silent error of not actually filtering your metrics, because `_filter_metrics` will happily loop over the string you provided. This PR explicitly checks that the input of `metric_names` is a list.
Closes [CO-1505](https://mosaicml.atlassian.net/browse/CO-1505)
=> Check and make sure that metric names is a list of strings

composer/trainer/dist_strategy.py
Passing in 'NONE' as a value for MixedPrecision in FSDP will keep all values in 'FULL' precision:
https://github.com/pytorch/pytorch/blob/eb56b08f96fdbca17ee09ab8500ca145085e1a3a/test/distributed/fsdp/test_fsdp_mixed_precision.py#L78
[CO-1503](https://mosaicml.atlassian.net/browse/CO-1503)
=> Adding in the possibility of 'None' for MixedPrecision FSDP

.github/workflows/pytest.yaml
As title, also switches to explicit docker image tags for the vision images because it is faster.
N/A
=> Remove pip install all from coverage action

composer/loggers/logger.py
removes:
* `data_fit`
* `data_epoch`
* `data_batch`
from `Logger`, which have been deprecated since 0.10
fixes CO-1554
=> Remove old deprecated logger methods

composer/metrics/nlp.py, tests/metrics/test_nlp_metrics.py
Adds missing tests for `HFCrossEntropy` and `Perplexity`
Closes [CO-1478](https://mosaicml.atlassian.net/browse/CO-1478)
=> NLP metrics tests

tests/utils/test_file_helpers.py
add tests for functions in `file_helpers.py`:
* `parse_uri`
* `maybe_create_object_store_from_uri`
* `maybe_create_remote_uploader_downloader_from_uri`
fixes CO-1555
=> Add tests for uri helper functions

composer/trainer/trainer.py
fixes doc default value for `log_to_console`
fix CO-1576
=> Fix doc issue, Trainer hparam log_to_console defaults to False

docs/source/conf.py
Fixes a bug that was introduced in the API Reference refactor.  Implements quick fix to switch to `sphinx.ext.viewcode` plugin instead of previous `sphinx.ext.linkcode` plugin since source code GH URL 
Fixes [CO-1382](https://mosaicml.atlassian.net/browse/CO-1382).
=> Fix source code links in docs

tests/test_full_nlp.py, tests/test_precision.py
Fixes tests that started failing in nightly (and then on this PR too)
=> add importorskip

docker/Dockerfile, tests/test_full_nlp.py
For Debian distros, Python 3.10 sysconfig default install paths have changed to `posix_local` instead of `posix_prefix` per:
https://lists.debian.org/debian-python/2022/03/msg00039.html
This is an issue with Triton which specifically uses `sysconfig.get_paths()` to determine install paths.  This PR sets the `DEB_PYTHON_INSTALL_LAYOUT=deb` to force previous default behavior in the Python 3.10 image.
Fixes [CO-1605](https://mosaicml.atlassian.net/browse/CO-1605)
=> Update Docker images to use ‘posix_prefix’ paths

composer/loggers/console_logger.py, tests/loggers/test_console_logger.py
Always log first batch and first epoch even if console_log_interval != 1
fix CO-1617
=> ConsoleLogger: log first batch and first epoch when using console_log_interval

.github/workflows/pytest-daily.yaml, .github/workflows/pytest.yaml, docs/source/composer_model.rst, examples/getting_started.ipynb, tests/test_notebooks.py
Disables new notebook test in CI flow
Also removes fast fail on daily tests since we want to see all faillures
Also bumps images to torch 1.13.1 now that we've switched over
=> Disable new notebook in CI

tests/datasets/test_in_context_learning_eval_datasets.py
`test_lm_task_evaluation` is very slow rn (90 seconds on CPU where our max allowed is 5s). It also runs a while on GPU when I dont think its needed. This speeds it up
[CO-1639](https://mosaicml.atlassian.net/browse/CO-1639)
[CO-1639]: https://mosaicml.atlassian.net/browse/CO-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Speed up test_lm_task_evaluation

composer/trainer/dist_strategy.py
This enables users to pass `ignored_modules` to the FSDP module
This PR is related to [RESEARCH-351](https://mosaicml.atlassian.net/browse/RESEARCH-351).
MoE modules which handle their own sharding / grad accum strategy should be ignored by FSDP; this PR enables that.
FSDP will eventually deprecate `ignored_modules` in favor of `ignored_parameters`. We'll need to migrate when this happens.
[RESEARCH-351]: https://mosaicml.atlassian.net/browse/RESEARCH-351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add ignore_modules to fsdp

composer/core/state.py, composer/devices/device.py
When loading composer state dicts, we load in train and eval metrics. However, these metrics have a defined `_device` which is usually always the rank 0 device since that's what stored in the `state_dict.` As a result, we need to manually copy over each metric (so we don't override a user's current metrics) and manually set the devices.
Before our memory overhead was:
|    0   N/A  N/A   3770555      C                                   31567MiB |
|    0   N/A  N/A   3770556      C                                     965MiB |
|    1   N/A  N/A   3770556      C                                   31567MiB 
Now, our memory overhead when loading models is normal:
|    0   N/A  N/A   3770555      C                                   31567MiB |
|    1   N/A  N/A   3770556      C …
=> Updating how we load metrics in a state_dict so we don't add extra memory overhead 

composer/core/data_spec.py, tests/test_split_batch.py
Add support to dataspec to split batches consisting of primitive types, e.g. a list of strings as prompts.
[CO-1686](https://mosaicml.atlassian.net/browse/CO-1686)
[CO-1690](https://mosaicml.atlassian.net/browse/CO-1690)
[CO-1686]: https://mosaicml.atlassian.net/browse/CO-1686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CO-1690]: https://mosaicml.atlassian.net/browse/CO-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add primitive list support

composer/trainer/dist_strategy.py, tests/common/models.py, tests/trainer/test_fsdp.py
Ensure FSDP throws an error if the underlying `module` in composer doesn't have a `param_init_fn` or `reset_parameters` function.
1. Does a pointer comparison to ensure the pointers to the underlying data are the same.
2. Adds a `param_init_fn` to the tested modules.
[CO-1689](https://mosaicml.atlassian.net/browse/CO-1689)
- [x ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ x] Did you run the tests locally to make sure they pass?
- [x ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))
[CO-1689]: …
=> Raise an error in FSDP `meta` tensor initialization if there's no initialization functions, fix associated flaky FSDP test

docker/Dockerfile
FFCV has accepted my two PRs https://github.com/libffcv/ffcv/pull/278 https://github.com/libffcv/ffcv/pull/275 which fix the installation issues we've seen in docker (sklearn and imgcat). This PR removes our temporary hack arounds and updates to pin to updated commit hash on main branch in FFCV.
=> Update docker with FFCV fix

.github/workflows/pytest-cpu.yaml, .github/workflows/pytest-gpu.yaml
Github is sometimes not running tests as the workflow for GPUs and CPUs has the same name. This leads to GHA cancelling one of them because of the concurrency check telling it to only run the latest one.
=> Update workflow names

composer/utils/object_store/s3_object_store.py, docs/source/trainer/checkpointing.rst
Coreweave object store is compatible with boto3. Uploading objects to Coreweave object store is almost exactly like writing to S3 using S3Object Store, except an endpoint_url must be set: `https://object.<region>.coreweave.com`.
Unfortunately, the endpoint_url can only be set programmatically (AWS doesn't support an endpoint_url env var or config field), so we create our own env var called `AWS_ENDPOINT_URL`, that we check for in the `S3ObjectStore`. The Trainer interface for the user is exactly the same as normal S3, except they have to set this env var.
Tested manually for save and load checkpoint
fix CO-1471
=> Add coreweave object store support.

.github/mcp/mcp_pytest.py, .github/workflows/pytest-gpu.yaml, .pre-commit-config.yaml, setup.py
Fixes a mis specified dependency that results in installation from source failing with `'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers`. Is likely related to the latest release of setuptools (https://setuptools.pypa.io/en/latest/history.html#v67-0-0), but I'm not sure what the dependency path is that leads us there, as this fails without changing anything about the environment it is running in (i.e. did not upgrade any packages, and setuptools is pinned to `0.59.5` in the environment i'm running in).
isort also broke so requires an upgrade: https://github.com/PyCQA/isort/pull/2078
This also requires moving the pip install out of the mcli integration, so that it can pick up changes to setup.py …
=> Fixes mis specified dependency

pyproject.toml
We ran into an issue where a setuptools release broke pip install from source. This is because pip uses an isolated build environment, which would always install the latest setuptools. In this PR we pin the setuptools version for building the package so that we have control over when to upgrade. Tested `pip install -e '.[all]'` locally.
Closes [CO-1702](https://mosaicml.atlassian.net/browse/CO-1702)
[CO-1702]: https://mosaicml.atlassian.net/browse/CO-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> pin setuptools in build requirements

.github/mcp/mcp_pytest.py, .github/workflows/code-quality.yaml, .github/workflows/pytest-cpu.yaml, .github/workflows/pytest-daily.yaml, .github/workflows/pytest-gpu.yaml
Adds `--upgrade` to the `pip install`s in CI. This ensures that CI will flag a dependency that upgrade that breaks composer
Closes [CO-1707](https://mosaicml.atlassian.net/browse/CO-1707)
[CO-1707]: https://mosaicml.atlassian.net/browse/CO-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add upgrade flags to pip installs

.github/workflows/code-quality.yaml, .github/workflows/pytest-cpu.yaml, .github/workflows/pytest-daily.yaml
This is a temporary workaround to unblock CI while we figure out the root cause. Currently installing from source does not work with pip==23 outside of a virtual env.
=> Temporarily pin pip to <23

.ci/Jenkinsfile, .github/mcp/mcp_pytest.py, composer/algorithms/squeeze_excite/README.md, setup.py
`follow_run_logs` occasionally disconnects. Instead, we need to wait for the run to complete and then get logs. Additionally, we want to add a timeout to kill daily tests if they don't finish in time.
Along for ride, adds `datasets` to nlp install which breaks install rn
[CO-1722](https://mosaicml.atlassian.net/browse/CO-1722)
[CO-1722]: https://mosaicml.atlassian.net/browse/CO-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix mcp script to avoid follow

.github/mcp/mcp_pytest.py
Fixes typo in script due to stale MCLI docs. CI currently broken because of this
=> Typo due to stale MCLI docs 

docker/Dockerfile
Pins `pip<23` in Docker images to unblock CI for the upcoming release.  This will be removed when we switch to miniconda Python.
Fixes [CO-1710](https://mosaicml.atlassian.net/browse/CO-1710)
[CO-1710]: https://mosaicml.atlassian.net/browse/CO-1710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Pin pip<23 in Docker images

composer/trainer/trainer.py, tests/loggers/test_console_logger.py, tests/trainer/test_trainer_eval.py
hot fix for bug caused by ConsoleLogger due to `trainer.eval` (when called with an `eval_dataloader` specified) not adding `evaluators` to `state.evaluators`:
1. Adds any passed in evaluators to state.evaluators and then once eval is done; removes them.
2. Adds tests to `test_console_logger` for the following use cases:
*  `trainer.eval(eval_dataloader=...)`
*  `trainer.fit(eval_dataloader=...)`
1. modified console_logger unit tests as described above
2. local manual test:
```python
transform = transforms.Compose([transforms.ToTensor()])
train_set = datasets.MNIST("data", train=True, download=True, transform=transform)
val_set = datasets.MNIST("data", train=False, download=True, transform=transform)
train_dataloader = DataLoader(train_set, batch_size=128)
eval_dataloader = …
```
=> Fix bug in trainer.eval and add test cases for test_console_logger

.github/workflows/pytest-daily.yaml, tests/datasets/test_streaming_datasets_train.py
Disable `test_streaming_datasets` test in `pytest-daily`.  This test fails intermittently on all tested nodes, additional debug is required.  A Jira issue has been filed to track this, the test will be re-enabled after a fix has been identified.
To test I temporarily enabled this workflow for pull requests, see the following GHA runs:
https://github.com/mosaicml/composer/actions/runs/4079311935/jobs/7030550011
https://github.com/mosaicml/composer/actions/runs/4079311935/jobs/7030550179
https://github.com/mosaicml/composer/actions/runs/4079311935/jobs/7030550288
=> Disable test_streaming_datasets in pytest-daily

composer/trainer/trainer.py, tests/common/__init__.py, tests/common/datasets.py, tests/trainer/test_trainer.py
Raises an error if the train dataloader is infinite and max duration is specified in epochs.
UX:
```
In [11]: trainer.fit()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 trainer.fit()
File ~/github/composer/composer/trainer/trainer.py:1693, in Trainer.fit(self, train_dataloader, train_dataloader_label, train_subset_num_batches, duration, reset_time, schedulers, scale_schedule_ratio, step_schedulers_every_batch, eval_dataloader, eval_subset_num_batches, eval_interval, grad_accum, device_train_microbatch_size, precision)
1690     _raise_missing_argument_exception('max_duration')
1692 if self.state.dataloader_len is None and self.state.max_duration.unit == …
```
=> Raise error if max duration is in epochs and dataloader is infinite

.github/mcp/mcp_pytest.py
Rename mcp tests in mcloud to include more descriptive names of whats running
[CO-1737](https://mosaicml.atlassian.net/browse/CO-1737)
[CO-1737]: https://mosaicml.atlassian.net/browse/CO-1737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update MCP GHA Name

tests/trainer/test_trainer.py
~~Randomize the order of pytest to catch errors that may work if the tests are run in the same order.~~
Move the test up in order so that it passes. Don't ask me why!!
=> Move ffcv up in test order

composer/utils/inference.py
Functional model surgery algorithms now return None instead of some returning the model object and others returning None. This change has broken one of the notebook tests. This PR fixes these tests.
=> Fix model surgery failure due to functional API change

composer/datasets/in_context_learning_evaluation.py, tests/datasets/test_in_context_learning_datasets.py
Add functionality to support ICL with OPT tokenizer (which prepends special tokens each time tokenizer is called). Due to the way we concatenate context and continuation encodings into a single input, it's important that no special tokens are put between them.
GPT Neo 1.3 B gets following accuracy
metrics/piqa/5-shot/InContextLearningMultipleChoiceAccuracy: 0.717934787273407
metrics/lambada/0-shot/InContextLearningLMAccuracy: 0.5883721113204956
OPT 1.3B gets:
metrics/piqa/5-shot/InContextLearningMultipleChoiceAccuracy: 0.719565212726593
metrics/lambada/0-shot/InContextLearningLMAccuracy: 0.5883721113204956
MosaicGPT 1.3B gets:
metrics/piqa/5-shot/InContextLearningMultipleChoiceAccuracy: 0.637499988079071
metrics/lambada/0-shot/InContextLearningLMAccuracy: 0.4075581431388855
ICL eval …
=> permit opt tokenizer

composer/models/huggingface.py, tests/models/test_hf_model.py
Previously `HuggingFaceModel` automatically used `metrics` for both `train_metrics` and `eval_metrics`. This can cause an issue if using `Evaluator`s with metrics that can't be applied during training (e.g. ICL metrics). Now, if you pass in `eval_metrics`, it will use that for `eval_metrics` instead.
[CO-1788](https://mosaicml.atlassian.net/browse/CO-1788)
[CO-1788]: https://mosaicml.atlassian.net/browse/CO-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> allow eval metrics to be passed in to HuggingFaceModel directly

composer/core/precision.py, composer/trainer/dist_strategy.py, tests/test_precision.py, tests/trainer/test_trainer.py
Adds amp_fp8 precision. This will allows us to train model faster using FP8 precision on H100 systems. It's a no op if amp_fp8 precision is not used. 
FP8 training support on H100
=> Add support for FP8 on H100 using NVidia's TransformerEngine

composer/models/__init__.py, composer/models/huggingface.py, tests/models/test_hf_model.py
Adds a basic util function to load a composer checkpoint of a `HuggingFaceModel` and write out the `config.json` and `pytorch_model.bin` that are expected in a huggingface pretrained folder.
[CO-1445](https://mosaicml.atlassian.net/browse/CO-1445)
[CO-1445]: https://mosaicml.atlassian.net/browse/CO-1445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Util for writing HuggingFace save_pretrained from a composer checkpoint

composer/datasets/in_context_learning_evaluation.py, composer/utils/dist.py, tests/datasets/test_in_context_learning_datasets.py
Fixes two issues with ICL
- only downloads the dataset file once per node
- requires `destination_path` arg (and makes it possible to pass through the dataloader helper) to avoid accidentally overwriting files and loading the wrong ones
[CO-1796](https://mosaicml.atlassian.net/browse/CO-1796)
[CO-1796]: https://mosaicml.atlassian.net/browse/CO-1796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix ICL race conditions

composer/models/huggingface.py
Adds `map_location` to some calls to `torch.load`
No Jira, just noticed the bug while doing other stuff.
=> add map location to huggingface utils

.github/workflows/daily.yaml
The `python-version` input was removed from the `pytest-cpu` workflow as a last minute change before #1968 was merged.  However we missed removing the `python-version` input in the `daily` workflow, this PR removes the vestigial input since it breaks the workflow.
=> Remove python-version input from Daily CPU tests

composer/trainer/trainer.py
Fixes minor typo in eval docstring with missing space
=> Fix typo in docstring for eval with missing space

.github/workflows/code-quality.yaml, .github/workflows/daily.yaml
This PR modifies the `daily.yaml` workflow by adding the `merge_group` event trigger and removing the `push` trigger for the `dev` branch.  Merge queues were just enabled for `dev` so the intent is that the `daily` workflow will run on PR's pushed to the merge queue.  For more information on merge queues, please see:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue
The `daily` workflow is now triggered as follows:
* Run workflow on merge_group event
* Run workflow on pushes to main and release branches
* Run workflow at 2:30am every day …
=> Add merge_group event trigger to GHA daily workflow

composer/trainer/trainer.py
We currently don't reset the scalar state when adjusting grad accum. This is a problem because if we OOM in the wrong spot, we'll hit an error about unscaling after step. This was caught, tested, and shown in graphs here https://github.com/mosaicml/composer/pull/1998
[CO-1830](https://mosaicml.atlassian.net/browse/CO-1830)
[CO-1830]: https://mosaicml.atlassian.net/browse/CO-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Reset scaler state

composer/callbacks/runtime_estimator.py, docs/source/trainer/callbacks.rst
The callbacks docs is missing a link to the runtime estimator
=> Update docs to include runtime estimator

composer/algorithms/low_precision_groupnorm/low_precision_groupnorm.py, composer/algorithms/low_precision_layernorm/low_precision_layernorm.py
LowPrecisionLayernorm and LowPrecisionGroupnorm are surgery algorithms that should be tagged accordingly to ensure they trigger the right unit tests and are baked into the checkpoints.
=> Tag surgery algorithms LPLN and LPGN

composer/callbacks/speed_monitor.py
Updates SpeedMonitor description to mention utilization. This means the table in the docs will include it (as the table takes the first line of the docstring). Minor nit from @bandish-shah
=> Update SpeedMonitor short-description for docs table

composer/callbacks/runtime_estimator.py, composer/callbacks/speed_monitor.py, tests/callbacks/test_runtime_estimator.py
Updates runtime estimator and speed monitor to use hours as unit by default when logging
Now in hours
[CO-1839](https://mosaicml.atlassian.net/browse/CO-1839)
[CO-1839]: https://mosaicml.atlassian.net/browse/CO-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update wallclock logging to default hours

composer/algorithms/blurpool/blurpool_layers.py, composer/trainer/trainer.py
This PR extracts the dynamic control flow operations in `blur_2d` into static control flow operations in the `BlurConv2d` class while leaving the dynamic control flow operations in place for `BlurMaxPool2d`. This allows FX graph mode post-training dynamic quantisation to be applied to models where blurpool has been applied to convolutions (though not max pooling).
There still seems to be an issue with static quantisation however, which I'm unsure of how to fix:
```
RuntimeError: quantized::conv2d_prepack() is missing value for argument 'bias'. Declaration: quantized::conv2d_prepack(Tensor weight, Tensor? bias, int[] stride, int[] padding, int[] dilation, int groups) -> __torch__.torch.classes.quantized.Conv2dPackedParamsBase
```
This PR partially fixes issue #1985 in that blurpool applied …
=> Allow FX graph mode post-training dynamic quantisation of BlurConv2d operations.

composer/algorithms/gyro_dropout/gyro_dropout.py, composer/algorithms/sam/sam.py, composer/algorithms/stochastic_depth/stochastic_depth.py, composer/algorithms/swa/swa.py, tests/algorithms/algorithm_settings.py, tests/algorithms/test_algorithm_resumption.py
Resuming some model-surgery algorithms using DDP in multi-gpu settings can cause issues due to module renaming.
There is a unit test (`test_algorithm_resumption.py::test_algorithm_resumption`) that checks for every algorithm whether you can train a model with that algorithm, save a checkpoint, then resume the training from that checkpoint with the algorithm. However, that unit test only checks when using one gpu. 
In this PR, we:
*  extend `test_algorithm_resumption.py::test_algorithm_resumption` to include a 2 gpu setting. 
* To enable that setting, we also modify `algorithm_settings.get_alg_dataloader` to include support for distributed samplers
* Add an xfail for the algorithm SWA for the 2-gpu setting since it has a known issue that we won't fix at the moment
fix CO-1848
=> Add multi-gpu testing to test_algorithm_resumption

composer/algorithms/ema/ema.py
This PR adds backwards compatibility for loading checkpoints saved with the EMA algorithm from composer 0.12.1 and earlier. 
Here is a plot showing a checkpoint saved on composer 0.12.1 resuming training on this PR branch.
=> Add backwards compatible checkpoint loading for EMA

composer/callbacks/speed_monitor.py, tests/callbacks/test_optimizer_monitor.py
As title. Fixes speed monitor bug which has a problem with flops/MFU. We now keep a record of flop utilization, as the values might be different depending on the level of padding in the batch. We also correctly sum the flop counts from all the devices
[CO-1838](https://mosaicml.atlassian.net/browse/CO-1838)
[CO-1838]: https://mosaicml.atlassian.net/browse/CO-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Patch Speed Monitor MFU

composer/loggers/console_logger.py, tests/loggers/test_console_logger.py
Fix eval duplicate logging issue. Along for the ride, refactor and clean up console log testing.
fix CO-1769
=> Fix eval duplicate logging issue

.github/workflows/pr-docker.yaml
Add's the `workflow_dispatch` trigger to the `pr-docker.yaml` workflow so that we can trigger this manually.
None, minor quality of life improvement.
=> Add workflow_dispatch trigger to pr-docker workflow

docker/Dockerfile
Follow on to PR #2007, previous PR upgraded the `ipython` package in Composer's `setup.py`.  However the `mosaicml/pytorch*` images are failing because the version already installed in the image needs to be upgraded as well.
This should resolve CVE-2023-24816.
[CO-1844](https://mosaicml.atlassian.net/browse/CO-1844)
[CO-1844]: https://mosaicml.atlassian.net/browse/CO-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade ipython installed in Docker images

composer/trainer/trainer.py, tests/trainer/test_trainer_eval.py
Currently, trainer ignores `eval_subset_num_batches` when passed into init when calling `trainer.eval()` and always uses `subset_num_batches`. Instead, we should use `subset_num_batches` if specified, or otherwise fall back on what is already specified in the evaluator (either through trainer or in evaluator constructor). This PR fixes this and adds a unit test for it.
[CO-1753](https://mosaicml.atlassian.net/browse/CO-1753)
[CO-1753]: https://mosaicml.atlassian.net/browse/CO-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Eval subset num batches bug fix

composer/callbacks/health_checker.py
Fixes #2030 . `slack_sdk` is not in the base install, so the `HealthChecker` needs to check the import.
=> Protect for missing `slack_sdk` import

.github/workflows/code-quality.yaml, .github/workflows/smoketest.yaml, composer/models/timm/model.py, tests/test_smoketest.py
This PR does two things:
- switches our code quality workflow back to dev target to avoid forcing install all for linting to pass
- adds a smoketest workflow that just imports the top level composer modules to avoid accidentally missing conditional imports
Closes [CO-1866](https://mosaicml.atlassian.net/browse/CO-1866)
[CO-1866]: https://mosaicml.atlassian.net/browse/CO-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> switch code quality workflow to dev target and smoketest

composer/callbacks/health_checker.py
To reduce the verbosity of pings, the `HealthChecker` should only send the test message for global rank zero, not local rank zero.
=> HealthChecker should only send test message on global rank zero

composer/models/huggingface.py, tests/fixtures/fixtures.py, tests/models/test_hf_model.py
Previously, `HuggingFaceModel` automatically resizes the model vocab size to match whatever the tokenizer vocab size is. This can cause an issue when the model vocab size is rounded to a multiple of 8 or 64 and _intentionally_ does not match the tokenizer vocab size. This PR changes our behavior to only resize the model vocab size when it is _necessary_, meaning when the model vocab size is less than the tokenizer vocab size. When the tokenizer vocab size is less than the model vocab size, we just raise a warning now.
Closes [CO-1861](https://mosaicml.atlassian.net/browse/CO-1861)
[CO-1861]: https://mosaicml.atlassian.net/browse/CO-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adjust HuggingFaceModel token embedding resizing to only occur when necessary

.github/workflows/pr-cpu.yaml, .github/workflows/pytest-cpu.yaml, composer/utils/collect_env.py
We recently added the `composer` package in addition to `mosaicml` for the first time. We had one piece of code `get_composer_commit_hash` that relied on the `mosaicml` package name existing. This change makes the code robust to any package name (won't crash), and gives expected results for either `mosaicml` or `composer`.
Manually tested by doing `COMPOSER_PACKAGE_NAME=composer pip install .[all]` and verifying that `composer_collect_env` errors before this change, and does not error after this change. Also verified that the the tests suite fails when package is built as `composer`, so this new workflow would have caught this issue.
Closes [CO-1901](https://mosaicml.atlassian.net/browse/CO-1901)
https://github.com/mosaicml/composer/issues/2048 will be closed once re-released with this …
=> test and fix composer package name usage in composer_collect_env

composer/trainer/trainer.py, tests/loggers/test_mlflow_logger.py
It would be good if we had Composer logging print relevant node information as part of the logs for all ranks so that this is possible, and consistent, for all users.
```bash
Starting training...
******************************
Config:
enabled_algorithms/GradientClipping: true
node_name: inst-iqyol-r7z2-workers
num_gpus_per_node: 8
num_nodes: 2
rank_zero_seed: 17
******************************
/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
warnings.warn(
/usr/lib/python3/dist-packages/torch/distributed/distributed_c10d.py:2849: UserWarning: torch.distributed._reduce_scatter_base is a private function and will …
```
=> Log nodename information in composer

composer/core/state.py, composer/models/huggingface.py, composer/utils/__init__.py, composer/utils/checkpoint.py, composer/utils/inference.py
We currently lose backwards compatibility due to a breaking change in torchmetrics. This PR monkeypatches on a new attribute necessary for restoring checkpoints. It also raises an error when trying to restore metrics which had API changes.
Testing with monkeypatched function
Testing with error raised when hitting accuracy.
[CO-1894](https://mosaicml.atlassian.net/browse/CO-1894)
[CO-1894]: https://mosaicml.atlassian.net/browse/CO-1894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Backward Compat with Torchmetrics

composer/trainer/mosaic_fsdp.py, docs/source/notes/distributed_training.rst
Our MixedPrecision setting 'DEFAULT' should be updated to:
```
mixed_precision = MixedPrecision(
param_dtype=autocast_precision,
reduce_dtype=torch.float32,
buffer_dtype=autocast_precision,
)
```
This will make 'DEFAULT' emulate AMP behavior.
use FULL if you need
use PURE if you want to live dangerously
standard AMP should be the 'DEFAULT' MixedPrecision setting (see above)
The current 'DEFAULT' shouldn't really be used.
Fixes https://mosaicml.atlassian.net/browse/CO-1896
=> update fsdp mixed precision

.github/workflows/pr-gpu.yaml
Comments out the GPU workflow for the `composer` package due to it causing GPU tests to fail. Also, increases load substantially for GPU CI and is not necessary. Note: the GPU tests are still run, just only for the `mosaicml` package build.
N/A
=> Delete composer package GPU workflow

composer/trainer/trainer.py, composer/utils/checkpoint.py, composer/utils/dist.py, composer/utils/inference.py, tests/utils/test_autolog_hparams.py
This reverts commit 25c9a67014e23d655258bb241df0fe0748164c90.
Reverts the recent checkpointing simplification because it seems to cause a hang in autoresume, blocking https://github.com/mosaicml/composer/pull/2054. Reverting until we can debug further
N/A
=> Revert "Checkpoints Simplified (#2041)"

composer/algorithms/low_precision_groupnorm/low_precision_groupnorm.py, composer/algorithms/low_precision_layernorm/low_precision_layernorm.py
I think the init signature got modified somewhere in the previous PR #2044. 
Reverting here, thanks @growlix for catching!
=> Add `device` and `dtype` back to `LPLayerNorm`

composer/trainer/trainer.py, composer/utils/checkpoint.py, composer/utils/dist.py, composer/utils/inference.py, tests/trainer/test_sharded_checkpoint.py, tests/utils/test_autolog_hparams.py
This reverts commit b25b7f03ae38843419adc23cdcf45cfc2a0557dc.
This reverts the refactor PR, which we are going to break up into individual PRs to fix the relevant issues. There will be four follow on PRs to fix:
1. the checkpoint download takes a long time, causing non zero ranks to timeout
2. autoresume + FSDP sharded checkpoints not working
3. skip the download on non local rank 0 ranks if not necessary
4. update dist timeout everywhere
=> Revert "Checkpoints Simplified (#2059)"

composer/utils/checkpoint.py
Before the `dist.barrier()` in `download_checkpoint`, busy wait for local rank 0 to reach that part of the code. This prevents a timeout on the barrier when it takes local rank 0 a long time to download the checkpoint.
[Manual test passed](https://wandb.ai/mosaic-ml/evan-v13-2-resumption-tests/runs/9vgl7fb5)
Closes [CO-1881](https://mosaicml.atlassian.net/browse/CO-1881)
[CO-1881]: https://mosaicml.atlassian.net/browse/CO-1881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Busy wait so that non local rank zeros don't timeout while local rank zero downloads a monolithic checkpoint

composer/trainer/trainer.py, tests/trainer/test_sharded_checkpoint.py
Adds support for FSDP sharded checkpoints in the autoresume code path.
[Passes](https://wandb.ai/mosaic-ml/evan-v13-2-resumption-tests/runs/fxsiqran) [manual test](https://wandb.ai/mosaic-ml/evan-v13-2-resumption-tests/runs/1qe6lc7f/overview)
Closes [CO-1906](https://mosaicml.atlassian.net/browse/CO-1906)
[CO-1906]: https://mosaicml.atlassian.net/browse/CO-1906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add support + test for autoresume with FSDP sharded checkpoints

composer/utils/checkpoint.py
Previously, if the `load_path` was specified as a _not_ format string, all ranks would download the same checkpoint, resulting in 8x the ingress to the node. This PR gates the downloads behind a check for whether sharded checkpoints are used so that only local rank 0 downloads the checkpoint.
Before and after of network usage for a resumption:
Closes [CO-1883](https://mosaicml.atlassian.net/browse/CO-1883)
[CO-1883]: https://mosaicml.atlassian.net/browse/CO-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Skip extra downloads when not using a format string

setup.py
Pins transformers to <4.27 (the version released today)
N/A
=> Pin transformers package to <4.27

CODEOWNERS
Given that streaming was spun off into its own repository, it doesn't make sense to have Karan and James codeowners for this section of the codebase anymore.
=> Update datasets CODEOWNERS

composer/models/huggingface.py, setup.py, tests/datasets/test_in_context_learning_datasets.py, tests/models/test_hf_model.py
This PR fixes the usage of `name_or_path` in the saving/loading of the HuggingFace tokenizer to be resilient to the key not existing, as apparently it was removed in a minor release. It also pins transformers so this does not happen again.
Closes [CO-1942](https://mosaicml.atlassian.net/browse/CO-1942)
[CO-1942]: https://mosaicml.atlassian.net/browse/CO-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix name_or_path usage in HF save/load usage

composer/trainer/dist_strategy.py
torch 2.0 has some fsdp related name changes for params and some imports are different. We conditionally make composer work with torch 2.0. This doesn't break composer for pre 2.0 torch version. 
Support for torch 2.0 with fsdp
=> make composer fsdp work with latest torch

composer/algorithms/ema/ema.py
This PR fixes a bug where if `trainer.eval()` is called before `trainer.fit()` when resuming training with EMA, the model parameters and buffers are not moved to GPU. The fix: ema parameters/buffers are now moved to device on `Event.EVAL_START` as well as `Event.FIT_START`.
=> Fix EMA resumption issue with calling trainer.eval() before trainer.fit()

tests/models/test_hf_model.py
Skips the HF+FSDP tests if torch version is <1.13. This caused daily tests to fail, which we still run on older torch versions.
=> skip fsdp tests for <1.13

composer/algorithms/ema/ema.py, composer/trainer/dist_strategy.py
Fixes EMA to work with FSDP. FSDP doesn't like directly accessing torch tensors -- instead we have to use copy. This has a small memory impact, but since it's not during a fwd/backward, it should be fine
Confirmed with manual test curves are same w or w/o FSDP:
```
Eval batch=1/1] Eval on eval data:
Eval metrics/eval/FrechetInceptionDistance-scale-0p0: 418.2500
Eval metrics/eval/MeanSquaredError: 1.1608
Eval metrics/eval/MeanSquaredError-bin-0-to-1: 1.1608
```
```
[Eval batch=1/1] Eval on eval data:
Eval metrics/eval/FrechetInceptionDistance-scale-0p0: 418.2500
Eval metrics/eval/MeanSquaredError: 1.1608
Eval metrics/eval/MeanSquaredError-bin-0-to-1: 1.1608
```
[CO-1943](https://mosaicml.atlassian.net/browse/CO-1943)
[CO-1943]: https://mosaicml.atlassian.net/browse/CO-1943?atlOrigin=eyJpIjo …
=> Patch EMA with FSDP

composer/algorithms/gradient_clipping/gradient_clipping.py, composer/trainer/dist_strategy.py, composer/utils/__init__.py, composer/utils/misc.py
In torch 2.0 they change the error message that is thrown for gradient clipping. This PR adds code to catch this new error message.
ran locally with torch 2.0:
https://wandb.ai/mosaic-ml/examples_fork-examples_llm/runs/prr9w4gb?workspace=user-bcui
link to PyTorch 2.0 new error message:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1000
[CO-1955](https://mosaicml.atlassian.net/browse/CO-1955)
[CO-1955]: https://mosaicml.atlassian.net/browse/CO-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating gradient clipping to be torch 2.0 compatible

composer/trainer/dist_strategy.py, tests/common/models.py, tests/trainer/test_fsdp.py
Adding checks, tests for on `meta` initialization with FSDP s.t. when we check for weight tying, `None` attributes aren't added to the list of attributes to check.
Before we added all `None` attributes and it would raise a scary error. 
[CO-1968](https://mosaicml.atlassian.net/jira/software/c/projects/CO/issues/CO-1968)
[CO-1968]: https://mosaicml.atlassian.net/browse/CO-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding checks for weight tying s.t. we don't think `None` attributes are weight tied

composer/models/huggingface.py, composer/utils/misc.py
This PR gates the extra forward call to get generate to work with fsdp on the model actually being fsdp so it is not called when not necessary.
N/A
=> gate the extra forward call specifically for fsdp

composer/models/huggingface.py, setup.py, tests/models/test_hf_model.py
This PR adds support for saving sentencepiece tokenizers by serializing and loading the `spiece.model` file (e.g. https://huggingface.co/bigscience/T0pp/blob/main/spiece.model)
Closes [CO-1902](https://mosaicml.atlassian.net/browse/CO-1902)
[CO-1902]: https://mosaicml.atlassian.net/browse/CO-1902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add sentencepiece support to `HuggingFaceModel`

composer/callbacks/__init__.py, composer/callbacks/activation_monitor.py, tests/callbacks/test_activation_monitor.py
Adds a callback that monitors activations in the network. Every `interval` batches it will attach a forwards hook and logs the `max`, `average`, `l2 norm`, and `kurtosis` for the input and output activations.
the output in wandb looks sth like:
Also as a sanity check the average kurtosis is ~3 at initialization:
And it doesn't impact throughput that heavily:
In particular every `interval` batches it looks like we take maybe a ~5% throughput hit. However, making `interval` say 25ba or 50ba should alleviate the issues.
[CO-1915](https://mosaicml.atlassian.net/browse/CO-1915)
- [x ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [x ] Did you update any related docs and document your change?
- [ x] Did you update any related tests …
=> Activation monitor

composer/models/huggingface.py, tests/models/test_hf_model.py
The utility function to write out a huggingface checkpoint from a composer checkpoint relied on `_name_or_path`, which only exists if the huggingface model was created using `from_pretrained`. This PR adds the necessary code to load the config using `model_type` instead. It first tries to use `model_type`, then tries to use `_name_or_path`, then crashes if neither of those work.
Closes [CO-1984](https://mosaicml.atlassian.net/browse/CO-1984)
[CO-1984]: https://mosaicml.atlassian.net/browse/CO-1984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add logic for direct instantiation

composer/callbacks/runtime_estimator.py
The runtime estimator currently over estimates the number of evals left when resuming. This fixes the num evals left correction.
Manual test:
Before: After first eval, we see 26 hr ETA
After: After first eval, we see 13.5 hr ETA
[CP-1978](https://mosaicml.atlassian.net/browse/CO-1978)
=> Runtime estimator

examples/early_stopping.ipynb
The hyperlinks are wrong and messed up in current docs.
This PR fixes it as we've done in other notebooks.
Now, it's fixed:
=> Fix early stopper docs links

composer/callbacks/optimizer_monitor.py, tests/callbacks/test_optimizer_monitor.py
Adds a `batch_log_interval` to the `OptimizerMonitor`
=> Add batch log interval to optimizer monitor

composer/callbacks/checkpoint_saver.py, composer/core/engine.py
Flushes checkpoint on kill. Adds signal handling to ensure atexit fns run. Notes:
1. cloud doesn't currently support this -- theyre fixign a bug to ensure it actually sends SIGINT
2. this leads to some nasty traces when ctrl + Cing... I'm not really sure if we can handle this any better. Open to ideas, but I think this is ok for a v1?
Manual test:
1) I kill with ctrl C
2) Checkpoint exists
[CO-1987](https://mosaicml.atlassian.net/browse/CO-1987)
[CO-1987]: https://mosaicml.atlassian.net/browse/CO-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Flush checkpoint on kill

composer/trainer/dist_strategy.py, composer/trainer/trainer.py, tests/utils/test_autolog_hparams.py
Adds a flag to enable a user to disable FSDP auto wrapping in composer.
This is necessary, since if a user pre-wraps their modules, then auto-wrap will see there are already pre-wrapped modules and it will raise an error. 
https://mosaicml.atlassian.net/browse/CO-2004
=> Add flexibility for FSDP Auto Wrap in Composer

composer/core/data_spec.py, composer/models/huggingface.py, tests/common/__init__.py, tests/trainer/test_dataspec.py, tests/trainer/test_trainer.py
Adds better defaults for `get_num_tokens_in_batch`, so that `max_duration` in tokens is supported by default.
Manual tested a gpt run with
```
GLOBAL_BATCH_SIZE = 512
MAX_SEQ_LEN = 2048
DURATION_INT = 104_857_600
MAX_DURATION = f'{DURATION_INT}tok'
```
and it ran for 100 batches
Closes [CO-1876](https://mosaicml.atlassian.net/browse/CO-1876)
[CO-1876]: https://mosaicml.atlassian.net/browse/CO-1876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Better defaults for `get_num_tokens_in_batch`

composer/utils/checkpoint.py, tests/trainer/test_sharded_checkpoint.py
In the edge case where one is using sharded checkpointing + autoresume and one rank's save checkpoint operation fails, then that rank will resume from an older checkpoint than the other ranks and this will be a silent error. 
This PR fixes that by checking to make sure that all timestamps loaded in match. If they don't it errors out
```image: mosaicml/pytorch:latest
integrations:
- git_branch: release/v0.0.4
git_repo: mosaicml/examples
integration_type: git_repo
pip_install: .[llm]
- git_branch: ckpt-timestamp
git_repo: eracah/evan-composer
integration_type: git_repo
pip_install: .[all]
parameters:
load_path: s3://mosaicml-internal-checkpoints-test/evan-test/checkpoints/gpt_125m/sharded-ws-8/125m-ws-8-save-FYeuN0/ep0-ba1-rank{rank}.pt
max_duration: 4ba
```
logs:
```
Starting training... …
```
=> Make sure the timestamps of the checkpoints are the same when loading

composer/trainer/dist_strategy.py, composer/trainer/trainer.py, composer/utils/misc.py, tests/trainer/test_trainer.py, tests/utils/test_autolog_hparams.py
- Support of `torch.compile` as part of Trainer argument.
- Add a new parameter `compile_config` in Trainer() which support model compilation based on the value of `compile_config` parameter.
CO-1956
**Node:** 1
**GPUs:** 4
| Model    | Dataset  | With compile thoughput/samples_per_sec | Without compile thoughput/samples_per_sec | Performance % |
| -------- | -------- | -------------------------------------- | ----------------------------------------- | ------------- |
| HF BERT  | C4       | 4259                                   | 3360                                      | 26.75%        |
| ResNet50 | ImageNet | 7424                                   | 5557                                      | 33.60%        |
- Some known FSDP Torch 2.0 issues when doing eval (Training works fine): …
=> Add torch.compile support for torch 2.0

README.md, composer/core/state.py, composer/models/resnet/README.md, examples/TPU_Training_in_composer.ipynb, examples/auto_microbatching.ipynb, examples/checkpoint_autoresume.ipynb, examples/custom_speedup_methods.ipynb, examples/early_stopping.ipynb, examples/exporting_for_inference.ipynb, examples/ffcv_dataloaders.ipynb, examples/finetune_huggingface.ipynb, examples/functional_api.ipynb, examples/getting_started.ipynb, examples/medical_image_segmentation.ipynb, examples/migrate_from_ptl.ipynb, examples/pretrain_finetune_huggingface.ipynb, examples/training_with_submitit.ipynb
* Updates "docs.mosaicml.com/en" to "docs.mosaicml.com/projects/composer/en" project URL
N/A
=> Fix broken URLs due to docs site refactor

composer/algorithms/ema/ema.py, composer/callbacks/__init__.py, composer/callbacks/checkpoint_saver.py, composer/core/evaluator.py, composer/core/state.py, composer/trainer/trainer.py, tests/trainer/test_checkpoint.py, tests/trainer/test_trainer_eval.py
Adds support for specifying `eval_interval` and `save_interval` in tokens, as well as the combination of `max_duration` in tokens and `eval_interval` in `dur`.
Manual test:
```
GLOBAL_BATCH_SIZE = 512
MAX_SEQ_LEN = 2048
DURATION_INT = 104_857_600
MAX_DURATION = f'{DURATION_INT}tok'
EVAL_INT = 12_582_912
EVAL_INTERVAL = f'{EVAL_INT}tok'
SAVE_INT = 41_943_041
SAVE_INTERVAL = f'{SAVE_INT}tok'
```
TODO:
Closes [CO-1877](https://mosaicml.atlassian.net/browse/CO-1877)
[CO-1877]: https://mosaicml.atlassian.net/browse/CO-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add support for `eval_interval` and `save_interval` in tokens

composer/datasets/in_context_learning_evaluation.py
This PR fixes the setting of a prefix space for the continuation for ICL eval. some tokenizers don't want this and some do. I am not aware of a property to check directly, so instead we run a simple string through ` a` and see what happens.
=> Fix ICL eval for sentencepiece tokenizers

docker/Dockerfile
I still leave the old install as well so that both versions should be cached I think.
The increase is to match the new examples version: https://github.com/mosaicml/examples/pull/309
=> bump flash attentionv ersion

.github/mcp/mcp_pytest.py, composer/core/state.py, composer/core/types.py, tests/common/compare.py, tests/trainer/test_checkpoint.py
1. Adds the `s3_bucket` config option to the GPU tests
2. Adjusts the precision for the old torchmetrics checkpoint test
3. Adds an attr to the loaded metric that needs to be present for torch 2
4. Special cases an equivalence tests for fused adam, because the loaded checkpoint has `False` and the CPU trained checkpoint has `None`
5. Ignores a few types so that precommit passes locally
=> Another attempt to fix the daily tests

tests/trainer/test_checkpoint.py
Skips the backwards compatibility test on torch versions prior to 1.13. The checkpoint in question was saved using torch 1.13, and there are some minor differences when loading on older torch versions (like pytorch changes to the optimizer). They should not _actually_ break backwards compatibility, but they break the way we check if two checkpoints are equal. We are going to stop supporting pytorch versions before 1.13 in the next release anyway, so I am just skipping that test on older torch versions.
=> Skip backward compatible checkpointing test on older torch versions

composer/datasets/in_context_learning_evaluation.py
Fixes bug with spacing on SentPiece tokenizer
=> bugfix sentpiece

examples/custom_speedup_methods.ipynb
Fixes broken image link with composer training loop
Also, fixes broken markdown headings
Fix CO-2071
Fix https://github.com/mosaicml/composer/issues/2168
=> Fix Broken Training Loop Image Link

composer/algorithms/gated_linear_units/README.md
Fix broken image link for GLU. This was caused by using `storage.cloud.google.com` instead of `storage.googleapis.com`
h/t to eagle eye @shinyfoil for finding this
fix CO-2072
fix https://github.com/mosaicml/composer/issues/2106
=> Fix broken image link for GLU

composer/core/state.py, tests/models/test_hf_model.py
Fixes an issue where HF info was not being saved if the model was DDP wrapped
Closes [CO-2077](https://mosaicml.atlassian.net/browse/CO-2077)
[CO-2077]: https://mosaicml.atlassian.net/browse/CO-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add support for saving HF info in state dict when using DDP

README.md
The previous "join slack" link required a `@mosaicml.com` email address.
=> Working slack link

docs/source/trainer/evaluation.rst
Fixes a couple typos in the evaluation docs.
Fixes the typo raised by #2219
=> Fix typo in evaluation docs

tests/test_loss.py
Removes warning filtering (which is valid)
[CO-57](https://mosaicml.atlassian.net/browse/CO-57)
[CO-57]: https://mosaicml.atlassian.net/browse/CO-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clean soft cross entropy

.github/mcli/mcli_pytest.py, .github/workflows/pytest-gpu.yaml, composer/loggers/mosaicml_logger.py, setup.py, tests/loggers/test_mosaicml_logger.py
Upgrades to mcli 0.4.0
Small changes:
* Uses root import instead of `mcli.sdk` (This is not required, but feels nicer 🙂)
* Renames mcp to mcli
* Removes `mcli init --mcloud` for CI testing - this is only user facing, not actually needed if api key env variable is set
Dependabot wants to update since we recently pushed 0.4.0 https://github.com/mosaicml/composer/pull/2220
=> Upgrade to mcli0.4, smaller mcli improvements

composer/callbacks/health_checker.py, tests/callbacks/callback_settings.py, tests/callbacks/test_health_checker.py
Deprecate healthchecker, which has been superseded by nodedoctor.
[CO-2103](https://mosaicml.atlassian.net/browse/CO-2103)
[CO-2103]: https://mosaicml.atlassian.net/browse/CO-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Deprecate healthchecker

tests/common/datasets.py, tests/models/test_hf_model.py
This adds two tests. One checks that in a case with no padding, CE loss and CE metric are equivalent. The other xfails that when you use microbatching and padding, CE loss and CE metric are not equivalent. This is because the microbatching engine does not take into account the number of loss generating tokens in each sample, and just weights samples equally.
=> CE loss vs CE metric equivalence

composer/core/algorithm.py
Rename `backwards_create_graph` decription
[CO-931](https://mosaicml.atlassian.net/browse/CO-931)
[CO-931]: https://mosaicml.atlassian.net/browse/CO-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Rename `backwards_create_graph` description

composer/core/callback.py, composer/core/event.py, composer/trainer/trainer.py, tests/test_events.py
For multiple use cases, such as weight norm calculations, and logging after all evaluators run, we want to add events before and after all evaluators, termed `EVAL_BEFORE_ALL` and `EVAL_AFTER_ALL`. To do this, we modify the documentation and the workflow for the `_run_evaluators` function in order to first cache the results of whether evaluators run and add these events if that occurs.
N/A
=> Add callbacks for EVAL_BEFORE_ALL and EVAL_AFTER_ALL

.github/workflows/daily.yaml, .github/workflows/pytest-cpu.yaml, .github/workflows/pytest-gpu.yaml
Adds alerts for daily tests if they fail. Tested https://github.com/mvpatel2000/composer/pull/53 and 
This will likely have a hiccup or two the first time around so it may require follow-ons
[CO-1631](https://mosaicml.atlassian.net/browse/CO-1631)
[CO-1631]: https://mosaicml.atlassian.net/browse/CO-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> alerts for daily tests

examples/ffcv_dataloaders.ipynb
We changed dockerfile cupy version, but forgot to update notebook, so it installs the wrong version in tests. Fixes daily
=> Fix daily tests by patching cupy version

composer/callbacks/speed_monitor.py, composer/trainer/trainer.py, tests/trainer/test_checkpoint.py, tests/utils/test_autolog_hparams.py
Add `spin_dataloader` argument to Trainer. This lets users disable spinning for faster resumption, which users have occasionally requested when they don't want deterministic resumption.
It's a little annoying that we have a var `spin_datalaoders` but a fn `_spin_dataloaders`.... It's probably fine but open to other ideas? We could also just flatten `_spin_dataloaders` since its only used once.
[CO-2154
](https://mosaicml.atlassian.net/browse/CO-2154)
=> Spin dataloader arg

composer/models/huggingface.py, tests/common/datasets.py, tests/common/models.py, tests/fixtures/fixtures.py, tests/models/test_hf_model.py
This pull request first checks if the output variable has two dimensions before then checking if the shape of the second element of the output variable is 1, then after using squeeze(dim=1) to squeeze the second element. 
The previous code was failing sometimes, when the output variable had only 1 dimension, and the code was checking for the shape of the second element. I was getting an error: 
```
IndexError: tuple index out of range
```
Was discussed on the Slack channel together with @dakinggg when I was facing an issue with a regression example using the HuggingFace Model.
Tagging Daniel to help with creating tests and configuring this PR in the best way possible for it to be merged
- [ -] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBU …
=> Confirming the output variable has two dimensions before confirming the shape of the second element.

composer/models/huggingface.py, tests/models/test_hf_model.py
Patches our `HuggingFaceModel` integration to allow for `.py` files in the tokenizer output of `save_pretrained`. It appears that as of the latest transformers version, tokenizer `save_pretrained` output does _not_ have python files in it, but i ran the test locally on `transformers==4.28.x` to confirm it passed.
```
(composer-dev-torch2) danielking@MML-1B940F4333E2 composer % pip show transformers
Name: transformers
Version: 4.28.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: …
```
=> Patch for tokenizers that have python files in save_pretrained output

composer/utils/file_helpers.py, tests/utils/test_file_helpers.py
Fixes a bug in which _get_file(overwrite=True) would fail if the destination path already exists. Ideally, we would instead delete anything at the existing destination path and overwrite it. This created bugs because ICL datasets rely on this utility and was failing if multiple runs in a row tried to write to the same destination. https://github.com/mosaicml/composer/blob/9b2d5ec34b6c26651c6bdae526dc849a652743cc/composer/datasets/in_context_learning_evaluation.py#LL138C8-L140C72
=> fix get file(overwite=True) to properly handle pre-existing files

composer/callbacks/mlperf.py, composer/trainer/trainer.py, setup.py, tests/trainer/test_trainer_eval.py
Now, if a user passes in a list of some DataLoaders/DataSpecs and Evaluators to the Trainer class, it no longer tries to apply all metrics to the DataLoaders/DataSpecs, causing a crash. Instead, it raises a ValueError and instructs the user to wrap the DataLoaders in an Evaluator beforehand to prevent unexpected behavior.
[CO-1763](https://mosaicml.atlassian.net/browse/CO-1763
)
[CO-1763]: https://mosaicml.atlassian.net/browse/CO-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add errors for Mixed Dataloader Eval

composer/callbacks/checkpoint_saver.py, tests/trainer/test_checkpoint.py
Add unit tests and functionality so that we delete symlinks when there are no checkpoints that should be saved locally.
[CO-2112](https://mosaicml.atlassian.net/browse/CO-2112)
[CO-2112]: https://mosaicml.atlassian.net/browse/CO-2112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Delete symlinks when not saving checkpoints locally

composer/models/huggingface.py, tests/models/test_hf_model.py
Originally the function 'write_huggingface_pretrained_from_composer_checkpoint' would not properly write the tokenizer from the composer checkpoint. This change fixes that by additionally saving the tokenizer from the composer checkpoint to the HuggingFace checkpoint. 
An additional test was implemented for this issue.
- Fixes CO-1976 (https://mosaicml.atlassian.net/browse/CO-1976)
=> fixed adding tokenizer to hf

composer/callbacks/speed_monitor.py, composer/loggers/console_logger.py, tests/loggers/test_console_logger.py
New PR for the console logger test, which is now smaller and has documentation, for the discard before eval and not at the end of epoch functionality.
[CO-2152](https://mosaicml.atlassian.net/browse/CO-2152)
[CO-2030](https://mosaicml.atlassian.net/browse/CO-2030
)
[CO-2152]: https://mosaicml.atlassian.net/browse/CO-2152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CO-2030]: https://mosaicml.atlassian.net/browse/CO-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> New Console Logger Test + Discard before Eval

composer/datasets/in_context_learning_evaluation.py
Enabled kv caching during generate to speed up QA Task
=> Enabled kv caching during generate to speed up QA Task

composer/trainer/trainer.py, tests/trainer/test_trainer.py
This PR fixes a bug where saving a checkpoint in training was called incorrectly and not saving the state and logger
This change fixes CO-2178
=> Fixed how save_checkpoint_to_save_folder called CheckpointSaver object to save state and logger

README.md, composer/callbacks/checkpoint_saver.py, composer/callbacks/mlperf.py, composer/datasets/in_context_learning_evaluation.py, composer/loggers/console_logger.py, composer/loggers/progress_bar_logger.py, composer/loggers/wandb_logger.py, composer/models/huggingface.py, composer/trainer/trainer.py, composer/utils/file_helpers.py, composer/utils/object_store/libcloud_object_store.py, composer/utils/object_store/oci_object_store.py, composer/utils/object_store/s3_object_store.py, docs/source/index.rst, setup.py, tests/loggers/test_console_logger.py, tests/loggers/test_mlflow_logger.py, tests/loggers/test_wandb_logger.py, tests/models/test_hf_model.py, tests/trainer/test_checkpoint.py, tests/trainer/test_trainer.py, tests/trainer/test_trainer_eval.py
This PR fixes several logger tests. test_mlflow_logging_works will use cpu when both cpu and gpu are available. test_wandb_artifacts is reenabled for offline mode and mocks the wandb artifact.
[CO-1021](https://mosaicml.atlassian.net/browse/CO-1021)
[CO-1021]: https://mosaicml.atlassian.net/browse/CO-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix tests for wandb and mlflow loggers

tests/fixtures/autouse_fixtures.py, tests/trainer/test_checkpoint.py
Adds gc to pytest fixture + jiggles tests s.t. daily passes?
https://github.com/mosaicml/composer/actions/runs/5293961521
=> Jiggling tests and adding gc collect

composer/core/state.py, composer/trainer/dist_strategy.py, composer/trainer/trainer.py, composer/utils/checkpoint.py, tests/fixtures/autouse_fixtures.py, tests/trainer/test_fsdp_checkpoint.py
1. Raises ValueError if user has mixed initialization without syncing module states
2. Patches error when loading monolith ckpt with optimizer differing from ckpt
3. Patches error where user specifies load rank 0 only but then doesn't actually pass a load path
=> Monolithic loading improvements

.github/secrets/exclude.yaml, .pre-commit-config.yaml
- Add secrets check as part of pre-commit.
- The `pre-commit run` command would fail if there is a verified secret leak. 
CO-2201
=> Add secrets check as part of pre-commit

composer/utils/checkpoint.py
Compute local ranks from global - local instead of using local world size. This lets us do different nodes with variable sizes
We're not going to test full elastic since it's not a priority. Just patching the obvious bugs for now.
[CO-2151](https://mosaicml.atlassian.net/browse/CO-2151)
[CO-2151]: https://mosaicml.atlassian.net/browse/CO-2151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update local rank 0 to be elastic

composer/callbacks/runtime_estimator.py, tests/callbacks/test_runtime_estimator.py
Previously, the runtime estimator used `state.dataloader.dataloader_len` when computing how often eval was run. This becomes inaccurate when an eval dataloader is swapped in, which caused incorrect computation for eval frequencies. This PR corrects the computation and adds a unit test which previously failed before this PR
[CO-2170](https://mosaicml.atlassian.net/browse/CO-2170)
[CO-2170]: https://mosaicml.atlassian.net/browse/CO-2170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Runtime estimator eval fix

docs/source/notes/distributed_training.rst
=> Fix typo in distributed_training.rst

composer/callbacks/image_visualizer.py
The `ImageVisualizer` doesn't need `wanbd`. This is the responsibility of the logger.
We are trying to use a different logger and the  `ImageVisualizer` crashes because `wanbd` is not installed.
=> [fix] Remove wandb from the `ImageVisualizer`

composer/algorithms/selective_backprop/selective_backprop.py, composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/core/precision.py, composer/core/state.py, composer/trainer/trainer.py, tests/test_precision.py, tests/utils/test_autolog_hparams.py
This PR introduces a new field to the trainer `State` that configures the FP8 scaling recipe used by Transformer Engine. Previously, these values were [hardcoded](https://github.com/mosaicml/composer/blob/b73c776725c05fbd5b7cf43b63a8ca85ed455af0/composer/core/precision.py#L73-L74), but now we can experiment with different parameters by supplying a `precision_config` dictionary to the `Trainer`. The dictionary should contain init parameters for the [`DelayedScaling`](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/api/common.html?highlight=delayedscaling#transformer_engine.common.recipe.DelayedScaling) class from Transformer Engine.
Implements https://mosaicml.atlassian.net/browse/CO-2210
=> Add precision config arg for FP8

composer/callbacks/image_visualizer.py, composer/core/state.py, docs/source/notes/distributed_training.rst
sets the default for sharded and local state dicts to offload_to_cpu=True. This helps avoid OOMs for large models when saving sharded checkpoints
Ran manual test of saving 30B checkpoints
https://github.com/mosaicml/llm-foundry/issues/367
=> Set offload_to_cpu True for state_dict_type=sharded

tests/fixtures/autouse_fixtures.py
We currently slam MAPI when we auto add mosaicml logger. This disables for autouse fixture
=> Fix mapi mocking

tests/trainer/test_fsdp_checkpoint.py
fixes `_compare_model_params_between_state_dicts`, so that both tensors that need to be compared are cast to cpu.
This fixes the failed `test_fsdp_load_old_checkpoint` test
=> Fix test_fsdp_load_old_checkpoint test to fix daily tests

composer/trainer/trainer.py
Add spaces between sentences in eval label warning.
=> Add spaces between sentences in eval label warning

composer/trainer/trainer.py
Before this change, if I create a Trainer with `seed=0`, the seed is overwritten with a random seed.
=> Avoid overwriting seed==0

.github/secrets/exclude.yaml, composer/loggers/wandb_logger.py
The new wandb release (0.15.5) changes it's error messages for artifact downloading failures. Our `WandBLogger` is designed to be EAFP instead of LBYL, so it relies on catching an exact error to prevent autoresume from trying to download checkpoints from wandb that aren't actually there.
This PR makes it so the check is not so specific (i.e. it catches all wandb CommErrors instead of just ones with specific messages). As a result, the EAFP code will then work with the new wandb install.
=> Fix wandb errror with autoresume issue

setup.py
Only deepspeed has errors with pydantic 2. Moving the pin down to there as we don't actually use in composer normally
=> Move pydantic pin to deepspeed

composer/trainer/trainer.py, setup.py
Add support for reading run_name from env var
=> Read Composer run name env var

tests/fixtures/autouse_fixtures.py, tests/trainer/test_trainer.py
Currently, unit tests all read the environment variable and use the same run name. This breaks things. Instead, we should hide the env var.
Along for ride, a unit test
=> Isolate env var in unit tests

composer/core/time.py, tests/test_time.py
Made changes to composer/core/time.py: Currently, regex used to parse timestring and create Time object (to decide "max_duration" param for training) cannot handle cases such as '3_000_000_000tok'. So, we modified the regex accordingly. Now, it will divide timestring into 2 parts: value and unit of time and then use float() fn of python to convert value to a float. This way python directly handles parsing first part of string.
Some example timestrings that now will be supported: '4_000tok', '3_00_0sp', '3_0e10tok', etc.
[CO-2238](https://mosaicml.atlassian.net/browse/CO-2238)
[CO-2238]: https://mosaicml.atlassian.net/browse/CO-2238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> regex changed in time.py

composer/trainer/trainer.py, tests/common/__init__.py, tests/common/models.py, tests/trainer/test_trainer.py
Currently, an optimizer is created in Trainer if an optimizer is not specified. If a user wants to evaluate an API model via the gauntlet, they would need to create a ComposerModel with a forward fn that calls the API.  This would currently break as the model does not have any parameters when Trainer attempts to auto-create an optimizer. So, currently, they need to auto-add dummy params (eg a small linear layer) that is unused.
Instead, we should give a warning in this case and defer requiring an optimizer to a fit call.
=> Support no param models by making optimizer optional

setup.py
identify on pypi has changed to 2.5.26, which cause pretty format json to reformat notebooks which is not compatible nbstripout. As a temporary solution, pinned identify to 2.5.25. 
- [ x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [x ] Did you run the tests locally to make sure they pass?
- [ x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))
=> pin identify version to resolve codequality failures

.github/workflows/pytest-cpu.yaml
Moves pytest-cpu slack notifications to issues from helpdesk
=> Moves pytest-cpu slack notifications to issues from helpdesk

composer/metrics/map.py, tests/metrics/test_map.py
`compute_on_step` has been deprecated from `torchmetrics`. In this PR I remove it and add basic tests to the MAP metric to detect other changes.
=> Remove compute_on_step from MAP

composer/core/callback.py, composer/core/engine.py, composer/core/event.py, composer/loggers/remote_uploader_downloader.py, composer/trainer/trainer.py, tests/test_events.py, tests/trainer/test_trainer_eval.py
Previously, `RemoteUploaderDownloader.wait_for_workers` was called on the `eval_end` event. This meant that `wait_for_workers` would happen after _every_ individual evaluator loop. This results in unnecessary hangs waiting for checkpoint upload in the middle of a run. This PR adds new events to signify that the standalone `trainer.eval` is being called, as opposed to eval from within the training loop, and changes the `RemoteUploaderDownloader` to use that event instead of the `eval_end` event. It also spawns a new issue [CO-2268](https://mosaicml.atlassian.net/browse/CO-2268).
Closes [CO-2267](https://mosaicml.atlassian.net/browse/CO-2267)
Manual test is by running
```
composer train.py yamls/finetune/mpt-7b_dolly_sft.yaml max_duration=5ba global_train_batch_size=4 …
```
=> Add a `EVAL_STANDALONE_START` and `EVAL_STANDALONE_END` events and change RUD to not `wait_for_workers` every eval

composer/callbacks/optimizer_monitor.py, composer/optim/decoupled_weight_decay.py, tests/callbacks/test_optimizer_monitor.py, tests/loggers/test_console_logger.py
The optimizer monitor logs very aggressively. This PR changes default to log every 10 batches. It also cleans up comments and removes some logging which is not useful per @bmosaicml's recommendation
=> Throttle optimizer monitor

composer/trainer/trainer.py
When you return empty dictionary in a model within `get_metrics`, at every batch `eval_forward` is being run.
According to my investigation, this is caused by `_eval_train_metrics` within `Trainer` class. Hence, I have added an extra condition to avoid running `_eval_train_metrics` if the `train_metrics` is returned as an empty dictionary.
Otherwise, you need to return None in `get_metrics` within a `ComposerModel` which causes the checkpointing to break.
=> Adding extra condition to avoid running eval_train_metrics

composer/utils/auto_log_hparams.py, tests/utils/test_autolog_hparams.py
When logging hyper-parameters only built-in types were supported. Otherwise the class name was used. This cause a loss of information when using enum. For example when logging precision `precision: Precision`.
This contribution takes the value field if the object is an Enum. Resulting in `precision: amp_fp16`
=> [fix] Use Enum value when logging hyper-parameters

composer/core/precision.py
Allow fp8 layers on Ada GPUs. 
Thanks @float-trip for testing it. I don't have access to Ada GPUs so can't test it. 
https://github.com/mosaicml/composer/compare/mosaicml:dev...dskhudia:ada_fp8?expand=1
=> fp8 on Ada

.github/mcli/mcli_pytest.py, setup.py
MCLI changed API for max duration. We need to update accordingly to use hours.
=> Update max duration on tests

composer/models/huggingface.py
PEFT overrides generate with kwargs only, so we need to call the underlying model in that way.
N/A
=> Change `input_ids` to a kwarg in `HuggingFaceModel.generate`

composer/core/state.py, composer/utils/checkpoint.py
ran a save_weights only for MPT 30B with:
* Lion (run_name: `test-ckpt-oom-prevent-lion-8-GzSIU3`)
* Adam (run_name: `test-ckpt-oom-prevent-adam-8-lqMUBL`)
using torch 2.01 (not nightly) on 500GB cpu memory 8xA100_80GB
Both successfully saved
=> Materialize only model state_dict in memory for  `save_weights_only`

.github/workflows/release-docker.yaml
Add torch 2.1.0 args for github release-docker workflow. 
Before PR: 
- Failed docker release build: https://github.com/mosaicml/composer/actions/runs/5957832159/job/16161172096
After PR: 
- Successful docker release build: https://github.com/mosaicml/composer/actions/runs/5958183901
=> Add torch 2.1.0 args for github release-docker workflow

.github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, pyproject.toml, tests/common/models.py
Test pytorch 2.1.0 docker images on ci/cd for cpu and daily tests. Also fixes broken tests due to UserWarnings on torch 2.1.0 related to: 
- has_*** is deprecated. 
- enable safe_tensor is True. 
- CI/CD Tests for new nightly image all [pass](https://github.com/mosaicml/composer/actions/runs/5979443813/job/16223545853?pr=2469) ✅
=> Test pytorch 2.1.0 docker images on ci/cd

composer/models/huggingface.py, tests/models/test_hf_model.py
For slow tokenizers, the `.model` tokenizer file must remain present on disk in order for the tokenizer to be loaded again. This change switches from using a tmpdir (which would not remain present), to a normal directory. It also fixes an issue where if there were two tokenizer files with the same name (e.g. tokenizer.json and tokenizer.model), only one of them would get saved in the checkpoint (at random). This adjusts the code to use the full filename instead of just the stem, and adds handling for backwards compatibility.
Closes [GRT-2280](https://mosaicml.atlassian.net/browse/GRT-2280)
Closes [GRT-2281](https://mosaicml.atlassian.net/browse/GRT-2281)
[GRT-2280]: https://mosaicml.atlassian.net/browse/GRT-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> Fix huggingface tokenizer loading for slow tokenizers

docker/Dockerfile
Security vulnerability in `semver` seen due to node. This PR upgrades the node version to bump up semver from 7.5.1 to 7.5.2
Action Run: https://github.com/mosaicml/composer/actions/runs/6017539089
Correct version of semver seen after upgrade: 
```
#14 [pytorch_stage  7/24] RUN npm list -g semver --depth=1
#14 2.223 /usr/lib
#14 2.223 `-- npm@9.8.0
#14 2.223   `-- semver@7.5.2
#14 2.223 
#14 DONE 2.4s
```
=> upgrade node

tests/trainer/test_fsdp_checkpoint.py
The PR adds tags to modules in tests to wrap FSDP at the module level, which was done historically by setting `min_params.` However, that parameter is now deprecated.
=> Adding some fixes to FSDP tests

composer/loggers/mosaicml_logger.py
Disables mosaicml logger after 3 failed attempts to log to avoid doom loop
=> Fail count on mosaicml logger

tests/trainer/test_fsdp_checkpoint.py
Fiilters warning about torchmetrics that we added to fix daily tests
=> filter warning

tests/trainer/test_fsdp_checkpoint.py
Fix sharded checkpoint test to ignore metric comparision
=> Fix sharded ckpt

composer/profiler/profiler.py
The `torch_prof_remote_file_name` argument of `Profiler` is passed as the `remote_file_name` argument of `TorchProfiler`, which supports passing `None` to disable uploading trace files. Prior to this commit, passing `None` to `Profiler` to do this whilst using a static type checker led to a type error.
=> Annotate `torch_prof_remote_file_name` as Optional

composer/core/state.py
This PR is a continuation of the previous PR #2411.
Summary: When you return empty dictionary in a model within get_metrics, at every batch eval_forward is being run.
And if you return `None` in `get_metrics` in ComposerModel (as below), it was throwing an error.
```
def get_metrics(self, is_train: bool) -> dict[str, Metric]:
if is_train:
return None
return {}
```
The previous PR #2411 fixed the problem only for the first epoch. After training for an epoch, it throws an error since it is trying to checkpoint according to the train_metrics, see the error below:
```
File "~/lib/python3.10/site-packages/composer/callbacks/checkpoint_saver.py", line 389, in _save_checkpoint
saved_path = checkpoint.save_checkpoint(
File "~/lib/python3.10/site-packages/composer/utils/checkpoint.py", line 760, …
```
=> fix: when there is no train_metrics, do not checkpoint

composer/core/state.py, composer/trainer/trainer.py, docs/source/trainer/checkpointing.rst, tests/trainer/test_checkpoint.py, tests/utils/test_autolog_hparams.py
Adds a flag gating saving metrics, which is false by default. Sharded checkpoints now also raise a value error instead of a warning when disabling metric saving. 
[GRT-2378](https://databricks.atlassian.net/browse/GRT-2378)
=> Remove metric saving

.github/mcli/mcli_pytest.py, composer/algorithms/channels_last/README.md, composer/algorithms/colout/README.md, composer/algorithms/cutmix/README.md, composer/algorithms/cutout/README.md, composer/algorithms/ema/README.md, composer/algorithms/factorize/README.md, composer/algorithms/ghost_batchnorm/README.md, composer/algorithms/label_smoothing/README.md, composer/algorithms/layer_freezing/README.md, composer/algorithms/mixup/README.md, composer/algorithms/swa/README.md
Updates `mcp_pytest` logging to include full unbuffered output and fixes daily tests by removing gpu marker from docs. 
Before PR failed daily test on mixup_test.md: 
- https://github.com/mosaicml/composer/actions/runs/6089103543/job/16521181092
After PR no more failed daily test: 
- https://github.com/mosaicml/composer/actions/runs/6114292229 
- Need to do some investigation on why this test is failing on GPU markers. Might be an issue with how `pytest-codeblocks` is clearing memory. For now just make sure all doctests run on cpu and not gpu.
=> Fix daily tests by removing gpu marker

setup.py
This PR upgrades the MLFlow requirement from >=2.0.1 to >=2.5.0. 
Some of the environment variables used in the MLFlow logger like `MLFLOW_EXPERIMENT_NAME` and `MLFLOW_EXPERIMENT_ID` were not introduced until v2.5.0.
=> Upgrade to MLFlow version 2.5.0

composer/optim/decoupled_weight_decay.py
Fix `optimizer_metrics` keys sorting in `DecoupledAdamW` `pre_reduce_metrics` and `dist_reduce_metrics` functions that are used to aggregate values for `OptimizerMonitor` in case of FSDP use so that keys order is the same on every rank.
- Apply regular sort function (`sorted`) to gathered keys without `key` parameter tweaks.
- Remove code blocks that were intended for `cosine` metrics as they are no longer calculated.
Fixes #2513
- No, but the change is small and the correctness was checked during debug and training runs.
- Via `pre-commit` install, they ran automatically on commit.
=> Fix metrics keys sort in DecoupledAdamW for OptimizerMonitor FSDP metric agreggation

composer/callbacks/runtime_estimator.py, tests/callbacks/test_runtime_estimator.py
=> Log runtime estimator units

examples/exporting_for_inference.ipynb, tests/algorithms/test_torch_export.py, tests/test_full_nlp.py, tests/utils/test_inference.py
Fixes failing Export for Inference ONNX tests caused by an ONNX version bump. As of ORT 1.9, you are required to explicitly set the [providers](https://onnxruntime.ai/docs/execution-providers/) parameter when instantiating InferenceSession.
=> Add providers param to ONNX Session in tests

docker/Dockerfile, setup.py
Update setup.py to bump flash attn. The latest version fixes the build isolation issues from pyproject toml and is required for transformer engine
=> Bump flash attn

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py, tests/utils/object_store/test_gs_object_store.py
Adds simple wrappers around mlflow save and register model functions, similar to the log model function
=> Add save and register wrappers to mlflow logger

composer/algorithms/gradient_clipping/gradient_clipping.py
Updates FSDP Gradient Clipping to use root function instead of try/except
=> Simplify FSDP Gradient Clipping

composer/trainer/mosaic_fsdp_utils.py
Fixes default precision to use fp32 reduce dtype
[GRT-2491](https://databricks.atlassian.net/browse/GRT-2491)
=> Patch default precision

composer/callbacks/generate.py
Adds a small log to track callback speed over time
=> Add logging for generate callbacks

composer/profiler/torch_profiler.py, docs/source/trainer/performance_tutorials/profiling.md
Logs profile averages
Example:
```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  Total MFLOPs  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
ProfilerStep*         0.11%      20.738ms       100.00%       19.110s        4.777s     396.89 Mb      -2.00 Mb             4            --  
Optimizer.step#DecoupledAdamW.step         4.05%     774.719ms        99.88%       19.086s        4.772s     396.89 Mb …
```
=> Log profile averages

composer/profiler/profiler.py, composer/profiler/torch_profiler.py, composer/trainer/trainer.py, docs/source/trainer/performance_tutorials/profiling.md
Add profiling remote downloader to composer
=> Add automatic remote uploader downloader for composer profiler

docker/Dockerfile, docker/build_matrix.yaml, docker/generate_build_matrix.py
This PR offers upgraded capabilities for AWS OFI NCCL version. This will update the OFI NCCL version with adding the required HWLOC package for properly building.
[GRT-2485](https://databricks.atlassian.net/browse/GRT-2485)
=> Update the AWS_OFI_NCCL version and add in the MPI HWLOC install

composer/trainer/mosaic_fsdp_utils.py, composer/utils/checkpoint.py, tests/trainer/test_fsdp_checkpoint.py
Gate torch import by 2.1.0. We are not confident checkpointing works on earlier versions per @eracah
=> Gate HSDP by torch 2.1.0

composer/trainer/dist_strategy.py
Fix FSDP arg default to match torch for limit all gathers
=> Fix FSDP arg default to match torch

composer/__init__.py, composer/models/huggingface.py, setup.py, tests/models/test_hf_model.py
This PR upgrades the transformers pin to allow 4.34.
Unfortunately there appear to be a number of bugs in transformers related to saving, loading, and modifying tokenizers.
https://github.com/huggingface/transformers/issues/26772
https://github.com/huggingface/transformers/issues/26773
https://github.com/huggingface/transformers/issues/26775
https://github.com/huggingface/transformers/issues/26777
and a major issue with having flash attention v1 installed
https://github.com/huggingface/transformers/issues/26778
The flash attention import remains an issue (hopefully fixed in next release), but the other issues are resolved.
=> Upgrade to transformers 4.34.1

composer/utils/file_helpers.py, setup.py
Adds a script that validates remote object store paths using composer utility functions. 
This is helpful for debugging especially on remote runs.
=> Add script to validate remote object store paths

composer/core/state.py, composer/trainer/mosaic_fsdp_utils.py, composer/trainer/trainer.py, composer/utils/reproducibility.py, tests/test_state.py, tests/trainer/test_fsdp_checkpoint.py
As of torch 2.1, torch has changed how RNG states work which is breaking our tests. This PR patches tests.
In order to address this issue, we catch RNG load issues and emit a warning. As this generally does not affect resumption too much, we choose to emit a warning instead of raising an error
=> Torch 2.1 Resumption Support

setup.py
The only dangerous thing in this release is that `save_pretrained` now saves safetensors format weights by default
=> Upgrade transformers to 4.35

tests/conftest.py, tests/fixtures/autouse_fixtures.py
Fix broken local eval test by adding distributed barrier to pytest sessions to ensure teardown cleans up resources properly. 
Fix spurious [test](https://github.com/mosaicml/composer/actions/runs/6791886988/job/18464220412?pr=2565#step:5:4077)
12/12 CPU tests passing stably
- Passing 3/3 https://github.com/mosaicml/composer/actions/runs/6803305965
- Passing 3/3 https://github.com/mosaicml/composer/actions/runs/6804399138/job/18501846426?pr=2694 
- Passing 3/3 tests again https://github.com/mosaicml/composer/actions/runs/6804399138 
- Passing CPU test https://github.com/mosaicml/composer/actions/runs/6804407850
=> Add distributed barrier test fixture to ensure pytest cleans up resources properly

composer/core/evaluator.py, composer/trainer/trainer.py, tests/trainer/test_trainer.py
Addresses error using `use_train_metrics: false`: `KeyError: 'continuation_indices'`
Manual test runs:
no fix: empty-eval-gFgK8Q 
with fix: empty-eval-with-fix-wpQHSK 
Changes
(1) Previously, if `metric_names` is an empty list, we return `metrics` without filtering. This is incorrect as an empty list should signify no metrics. We update this to handle an empty list.
(2) evaluator.metric_names should default to None not an empty list, so we can properly populate it with defaults later
=> Properly handle empty metric_names passed to Trainer._filter_metrics

composer/loggers/mosaicml_logger.py
We are seeing run events inconsistently sent to run metadata for finetuning runs. Adding logs to help debug and force flushing metadata when run event related metadata is being written to the run.
=> Adding logging and force flushing for run events

tests/trainer/test_fsdp_checkpoint.py
`tests/trainer/test_fsdp_checkpoint.pytest_fsdp_checkpoint::test_elastic_resumption` checks for accurate resumption by gathering the params to rank 0 and comparing state_dicts. This comparison check only needs to be on rank 0 and can cause issues on non-zero ranks because some state dicts will be empty.
This didn't used to be a problem because 'full' state_dicts on non-zero ranks were of the form `{'key':[]}`, but now they are of the form `{}`
Fixes daily test failure
=> [daily-test fix] Add rank 0 gating to test_elastic_resumption state dict comparison

composer/loggers/mlflow_logger.py
=> [S] Add tag support to MLFlowLogger

composer/callbacks/checkpoint_saver.py
=> Use `raise ... from e` to preserve stack trace

composer/profiler/torch_profiler.py
Fix profiler logging issue where we don't log memory stats if it does not exist. 
https://databricks.atlassian.net/browse/GRT-2584
=> Fix profiler issue

docker/build_matrix.yaml, docker/generate_build_matrix.py
NVIDIA has pushed new base images that seem to be missing forward compatibility in the NVIDIA_REQUIRE_CUDA env var. We are overriding it here specifically for the 11.1 images.
To Do:
Related to #2722.
=> Override NVIDIA environment variable for CUDA 12.1 images

docker/build_matrix.yaml, docker/generate_build_matrix.py
NVIDIA has pushed new base images that seem to be missing forward compatibility in the NVIDIA_REQUIRE_CUDA env var. We are overriding it here specifically for the CUDA 12.1 Composer and Torch nightly images.
=> Add NVIDIA_REQUIRE_CUDA_OVERRIDE env variable to Composer and Torch nightly Docker images

composer/utils/checkpoint.py
This PR fixes loading checkpoints with a different activation checkpointing granularity.
FSDP activation checkpointing wraps the module with `_checkpoint_wrapped_module`, when loading a model checkpoint, besides `_fsdp_wrapped_module`, `_checkpoint_wrapped_module` also needs to be striped out of the module name so that the name mapping is correct when loading state dict.
=> fix checkpointing with activation checkpointing

composer/callbacks/lr_monitor.py
Removes a duplicated for loop in the `LRMonitor` callback.
=> Remove duplicated for loop in lr_monitor.py

composer/loggers/mosaicml_logger.py, tests/loggers/test_mosaicml_logger.py
- We are noticing that wandb url specifically is being dropped from regression test runs inconsistently, adding logs to try to debug this moving forward.
See Jira: https://databricks.atlassian.net/browse/GRT-2588
=> Add metadata logging for wandb

composer/trainer/trainer.py, tests/trainer/test_checkpoint.py
Ignore load ignore keys as that should only apply to initial autoresume
=> Ignore load ignore keys

composer/callbacks/activation_monitor.py, composer/callbacks/image_visualizer.py, composer/core/time.py, composer/loggers/console_logger.py, composer/loggers/slack_logger.py, composer/trainer/trainer.py, composer/utils/misc.py, tests/test_time.py
Many of our callbacks handle converting a `str`, `Time` or `int` (with default units) to `Time` .  The `ensure_time` helper does basically this, but isn't as convenient as pulling from the already imported `Time` class. This adds `from_input` method and reduces the number of callbacks where we are reimplementing it. I also added floor division and mod operations to the time object.
=> time to clean up time parsing 😉

docker/Dockerfile, docker/build_matrix.yaml, docker/generate_build_matrix.py
* Add --enable-platform-aws for proper AWS NCCL Topology discovery 
* Bump on the aws-ofi-nccl plugin
=> Bump aws of nccl version and enable aws platform support

tests/trainer/test_fsdp_checkpoint.py
Fix checkpoint validation tests for torch 1.13.
=> Fix checkpoint validation tests for torch 1.13

composer/utils/object_store/uc_object_store.py, setup.py
- The databricks deployed MAPI uses a config file to provide the credentials instead of the environment variables. Use the underlying `databricks-sdk` to determine if the right configs are set to authenticate instead of forcing users to set the environment variables.
- Also update the sdk to the latest version on pypi to allow for better automatic authentication
- Existing unit tests pass
- Run integration test locally to verify that it passes
```
pytest -m "remote" tests/utils/object_store/test_uc_object_store.py::test_uc_object_store_integration
================================================================== test session starts ===================================================================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: …
```
=> [UCVolumes] Rely on databricks-sdk auth for the right requirements

composer/loggers/mlflow_logger.py, setup.py, tests/loggers/test_mlflow_logger.py
Enable system metrics in mosaic mlflow logger. The default mode is on.
Please see the screenshot:
The order is a bit strange when there are multiple GPUs, we should fix it on the mlflow side. But it does not affect this PR.
=> Enable system metrics in mosaic mlflow logger

composer/profiler/profiler.py, composer/profiler/torch_profiler.py
This PR changes the default behavior from enabling memorytimeline with a default name to not enabling  memory timeline generation if users do not specify torch_profiler_memory_filename. Thus users don't get a ValueError the first time they run the profiler without the three required flags on (torch_prof_with_stack, torch_prof_record_shapes, and torch_prof_profile_memory).
=> default to no torch profiler memory timeline

composer/utils/checkpoint.py, tests/trainer/test_checkpoint.py
Fix load_ignore_keys with rng. Previously, if rng was ignored, this would result in a missing key error. Additionally adds unit tests for load_ignore_Keys
=> Fix load_ignore_keys with rng

composer/loggers/mosaicml_logger.py, tests/loggers/test_mosaicml_logger.py
Error traces often are masked by a second error raised by mosaicml logger on close where it attempts to schedule a future while python interpreter is shutting down (results in error). This PR makes the last metadata upload on close a non-future. It also adds a wait call for all existing futures
Manually tested on run I was debugging where this kept happening
=> Avoid futures on close for MosaicML logger

composer/trainer/dist_strategy.py
Require sync module states with HSDP or otherwise different replicas will have different initialization points
=> Require sync module states with HSDP

composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py
This PR patches torch to get better communication/computation overlap. Instead of using just one stream to unshard (all-gather) both attention params and FFN params, this uses a separate unshard stream for each. Computation now does not have to unnecessarily wait on communication from unrelated parts of the network.
Testing shows similar convergence with and without patching. Training instabilities, mainly due to load-balancing loss and not shuffling, were observed both with and without patching, which impacted convergence nondeterministically.
MFU improves by ~1-2% at small scales (first image) and ~25% at large scales, where without the patch, MFU is ~31% - (second image).
See this PR to PyTorch for more context: https://github.com/pytorch/pytorch/pull/116611
=> Better communication computation overlap

composer/callbacks/speed_monitor.py
Improve error message for speed monitor. Clean up missing spaces and preserve device name.
=> Improve error message for speed monitor

composer/profiler/torch_profiler.py
Fix torch profiler error on close. Avoids:
```
2024-01-04 20:48:13,231: rank7[1408][MainThread]: ERROR: composer.core.engine: Error running TorchProfiler.close(). Skipping TorchProfiler.post_close().
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 527, in _close
callback.close(state, logger)
File "/usr/lib/python3/dist-packages/composer/profiler/torch_profiler.py", line 346, in close
log.info(self.profiler.key_averages().table(sort_by='cpu_time_total', row_limit=20))
File "/usr/lib/python3/dist-packages/torch/profiler/profiler.py", line 209, in key_averages
assert self.profiler
AssertionError
Stack (most recent call last):
File "/usr/lib/python3/dist-packages/composer/core/engine.py", line 529, in _close
log.error(
```
when an error …
=> Fix torch profiler error on close

composer/core/state.py, composer/trainer/dist_strategy.py, composer/trainer/trainer.py, composer/utils/reproducibility.py
Fix seed for FSDP wrap. Enables deterministic init which is needed for HSDP
=> Fix seed for FSDP wrap

composer/trainer/mosaic_fsdp.py
Allow hsdp. Adds missing patch
=> Allow hsdp

composer/callbacks/checkpoint_saver.py, composer/core/state.py, composer/trainer/trainer.py, composer/utils/checkpoint.py, tests/trainer/test_checkpoint.py, tests/utils/test_autolog_hparams.py
=> Add save_ignore_keys

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Adds a new field to the MLflow logger to disable certain metrics from being logged. 
note: covered by parameter docs https://mosaicml-docsite--2869.com.readthedocs.build/projects/composer/en/2869/api_reference/generated/composer.loggers.MLFlowLogger.html#composer.loggers.MLFlowLogger
=> Add ignore_metrics field to the MLflow logger

composer/trainer/dist_strategy.py
Fixes prints as log.info. Manually tested to verify it looks fine
```
2024-01-17 21:12:09,495: rank0[125][MainThread]: INFO: composer.trainer.dist_strategy: FSDP: Wrapped Model:
2024-01-17 21:12:09,495: rank0[125][MainThread]: INFO: composer.trainer.dist_strategy: ComposerMPTCausalLM(
(model): FullyShardedDataParallel(
...
```
=> Convert print to log.info

composer/trainer/trainer.py
**TLDR**
Fixes the trainer eval loop for MPS devices when the model output is a list of tensors rather than a `torch.Tensor` or `Mapping`.
**Related**
Similar issue but with dict: #2632 
PR for above issue: #2706
**Details**
In the trainer evaluation loop, model outputs (`self.state.outputs`) are moved to the CPU if they are on an MPS device (to avoid torchvision numerical errors on MPS devices). Currently this works fine if `self.state.outputs` is a Mapping or a torch.Tensor. However, it fails for Sequence types (e.g. a list of torch.Tensors).
According to the State class, `outputs` is expected to be of type `torch.Tensor | Sequence[torch.Tensor]`. So Sequence types should be supported in this process in the eval loop. Strictly, `outputs` should not be a `Mapping`, despite the eval …
=> Fix MPS with sequence loss 

composer/core/state.py, composer/trainer/mosaic_fsdp.py, composer/trainer/trainer.py, composer/utils/checkpoint.py
Remove monkeypatch and new state dict APIs (which also always require dist init) for torch 2.2. We will delay to 2.3.
=> Remove monkeypatch and new state dict APIs for torch 2.2

composer/utils/checkpoint.py, tests/trainer/test_fsdp_checkpoint.py
Only load RNG keys that exist. This was broken in https://github.com/mosaicml/composer/pull/2897 but was not caught in manual tests for some reason 🤔
=> Only load RNG keys that exist

composer/core/precision.py
Before this PR checkpoint resumption on fp8 MPT's did not work since checkpoints serialized extra fp8 buffers in bytes which is incompatible with torch's `load_sharded_optimizers`
After this PR checkpoint resumption from fp8 serializes out extra fp8 buffers in tensors in onnx mode. 
**Torch 2.1**
- Failed run w/out this PR: `mpt-125m-sharded-regression-fp8-ignore-td0frt` 🔴  
- Working run w/this PR: `mpt-125m-sharded-regression-fp8-ignore-6DD62n` ✅
**Torch 2.3**
- Run w/out this PR: `mpt-125m-sharded-regression-fp8-ignore-tAGCla` ✅ 
- Working run w/this PR: `mpt-125m-sharded-regression-fp8-ignore-8bZirC` ✅
=> Fix FP8 checkpoint resumption with onnx export flag

tests/loggers/test_mlflow_logger.py
`test_mlflow_ignore_hyperparameters` is flakey--it passed tests on PR submission but later failed:
```
expected_params_list = [
'node_name',
'rank_zero_seed',
'composer_version',
'composer_commit_hash',
'mlflow_experiment_id',
]
>       assert set(expected_params_list) == set(actual_params_list)
E       AssertionError: assert {'composer_co...nk_zero_seed'} == {'composer_version'}
E         Extra items in the left set:
E         'node_name'
E         'composer_commit_hash'
E         'mlflow_experiment_id'
E         'rank_zero_seed'
E         Full diff:
E           {
E         +  'composer_commit_hash',
E            'composer_version',
E         +  'mlflow_experiment_id',
E         +  'node_name',
E         +  'rank_zero_seed',
E           }
```
This test was copied almost directly from …
=> Fix MLFlowLogger test

tests/models/test_hf_model.py
On torch 2.0, fsdp wrapped modules can not have both frozen and unfrozen params. On 2.1+, if you have `use_orig_params=True`, they can. So we need a special case for the tests here.
=> Fix daily tests for peft + fsdp

composer/models/huggingface.py, tests/models/test_hf_model.py
The dailys surfaced an error with peft + fsdp that I haven't seen before
```
def __setstate__(self, state):
super().__setstate__(state)
for group in self.param_groups:
group.setdefault('amsgrad', False)
group.setdefault('maximize', False)
group.setdefault('foreach', None)
group.setdefault('capturable', False)
state_values = list(self.state.values())
>       step_is_tensor = (len(state_values) != 0) and torch.is_tensor(state_values[0]['step'])
E       KeyError: 'step'
```
Given that (a) we will not support 1.13 for much longer anyway, as everyone should be using torch 2+, and (b) there is no clean way to _only_ prevent peft usage on 1.13 when used in conjunction with FSDP, I decided to just gate peft usage on torch 2+.
=> Fix daily tests for peft on 1.13

composer/core/types.py, composer/utils/object_store/oci_object_store.py, tests/utils/object_store/test_oci_object_store.py
OCI got rid of `e.code`, breaking our autoresume logic. Let's just always raise.
https://github.com/oracle/oci-cli/blob/b03b3b1f2b05f00bcbfeed84b7fcf6e0d091478e/services/dts/src/oci_cli_dts/base_client.py#L88
Along for ride, fixes docs with types PR
=> Fix OCI reraising errors.

composer/algorithms/low_precision_layernorm/low_precision_layernorm.py
Fixes LP layernorm weight attribute.
=> Fix lp layernorm weight

tests/algorithms/test_required_on_load.py, tests/trainer/test_checkpoint.py
Fix test torch pins. This matches the changes we made in state to delay switching to new API until torch 2.3
=> Fix torch pins in tests

.github/CODEOWNERS
We still require reviews from @dakinggg and @eracah for loggers. This doesn't seem necessary and for some reason composer-team-eng approval w existing codeowners file is not enough.
Given it's not that big of a project code-wise, let's just strip bespoke codeowners.
=> Remove bespoke codeowners

composer/algorithms/low_precision_groupnorm/low_precision_groupnorm.py, composer/algorithms/low_precision_layernorm/low_precision_layernorm.py, composer/core/callback.py, composer/core/engine.py, composer/core/event.py, composer/trainer/trainer.py, docs/source/getting_started/welcome_tour.rst, docs/source/trainer/algorithms.rst, tests/test_events.py
Adds a BEFORE_LOAD event that callbacks can use, that happens right before the checkpoint gets loaded. This more easily enables different functions like saving checkpoints from a fully initialized model + optimizer immediately, or changing the dataset state once the dataloader has been passed to the `State` object.
=> Add a BEFORE_LOAD event

composer/utils/checkpoint.py, composer/utils/file_helpers.py, tests/trainer/test_checkpoint.py
Format load_path with name. This way if I specify run_name as a format var in a load_path, like we frequently do with save_folder, it will automatically format it. Eg `oci://ckpts/mihir/{run_name}/ep0-ba50` will be formatted correctly.
Also adds unit test.
I like to test resumption by keeping a yaml that explicitly formats name into save/load path, but that doesn't work currently.
=> Format load_path with name

composer/utils/object_store/uc_object_store.py, tests/utils/object_store/test_uc_object_store.py
To unblock Databricks Finetuning PrPr launch, we need to modify the `get_object_size` function, which is currently used to check object existence. The UC team is working on a long-term fix to support `files.get_status` endpoint, but it is not available yet. The workaround we were recommended to use is to call HEAD on the files api endpoint to fetch metadata on the UC resource.
Manually tested in r1z2 by pulling my branch and verifying that this works with my Databricks staging UC object.
```
>>> from composer.utils.object_store.uc_object_store import UCObjectStore as US
>>> o = US('Volumes/main/nancyhung/ift')
>>> o.get_object_size('train.jsonl')
1000000
```
-------
Testing by Jerry with a dogfood volume (but functionally should be same):
```
>>> from composer.utils.object_store import …
```
=> Fix UC object store bugfix

composer/utils/object_store/uc_object_store.py
In previous change, https://github.com/mosaicml/composer/pull/2982 I dropped using the full object path `self._get_object_path(object_name)`. This PR adds it back.
Works when modified the code in long-living pod in prod. 
```
>>> llmfoundry.data.finetuning.dataloader._download_remote_hf_dataset('dbfs:/Volumes/finetuning/ift/train_vol', 'train')
'/usr/lib/python3/dist-packages/llmfoundry/.downloaded_finetuning/train'
```
confirmed file is downloaded in the directory
```
{"prompt": "<|im_start|>system\nA conversation between a user and an LLM-based AI assistant.
...
```
=> [Bugfix][UC] Add back the full object path

composer/utils/object_store/uc_object_store.py, tests/utils/object_store/test_uc_object_store.py
Also adds a unit test
Manual test still good
```
In [4]: uc.get_object_size('train.jsonl')
Out[4]: 1000000
```
=> Minor cleanup of UC get_object_size

composer/utils/checkpoint.py, tests/utils/eval_client/test_local_eval_client.py
Removes planner validation. This should be done by Torch.
The planners let an end-user arbitrarily modify state dict before loading/saving. It's an optional argument to customize things further.
@b-chu I didn't get where type hints are supposed to validate -- can you clarify the comment?
=> Remove planner validation

composer/utils/checkpoint.py
Currently, we only download on rank 0 if using FSDP + device mesh
=> Fix load for non-HSDP device mesh

composer/algorithms/low_precision_layernorm/low_precision_layernorm.py
Add bias argument to LPLN and forward to LayerNorm parent class
=> Add bias argument to LPLN

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Add Torch 2.3 image for aws cluster to support diagnostic runs.
=> Add torch 2.3 image for aws cluster

composer/trainer/trainer.py
Streaming often takes a while to start first batch. This changes last seen debug message from user to starting training loop. This avoids confusion with users thinking spinning dataloaders is taking a really long time.
=> Add debug log before training loop starts

composer/loggers/console_logger.py
composer prints the console logging for 1st batch and every `self.log_interval` batches. but when resuming training, we probably want to print the 1st batch no matter if `cur_batch % self.log_interval == 0`. This PR just forces to print console logging for 1st batch after resumption. 
1. firstly save checkpoint after training 3 batches.
2. load checkpoint and set `console_log_interval=7ba` `composer train/train.py train/yamls/pretrain/mpt-125m.yaml train_loader.dataset.split=train_small  max_duration=10ba eval_interval=0 console_log_interval=7ba load_path=./125m/checkpoints/ep0-ba3-rank0.pt`
first logged batch is 7 
first logged batch is 4, then 7
=> [EASY] Always log 1st batch when resuming training 

composer/cli/launcher.py
Re conversation at the end of here: https://github.com/mosaicml/composer/pull/3018
Checking for presence of the gpu prefix env var so we can default to normal logging behavior if we fail to provide a value.
=> Fall back to normal logging when gpu prefix is not present

composer/utils/checkpoint.py
Add sorted to log line for checkpoint broadcast. This ensures it prints consistently with pre-broadcast debug log, making it easier to verify transfer.
=> Add sorted to logs for checkpoint broadcast

composer/trainer/dist_strategy.py, tests/trainer/test_fsdp.py
Torch gives a nasty error if device mesh size doesn't properly match parallelism strat (FSDP vs. HSDP). This gives a friendlier error in this scenario.
=> Friendlier device mesh error

composer/trainer/trainer.py
Currently, all ranks download symlink. Only global rank 0 should download and instead broadcast to all ranks
manual test:
=> Download symlink once

composer/utils/object_store/oci_object_store.py
Adds minimum size to OCI download parts to avoid multi-part downloading small files (eg symlink)
Manual test:
Also printed number of parts and verified works correctly.
=> Add min size to OCI download

.pre-commit-config.yaml, composer/cli/launcher.py, composer/profiler/utils.py, pyproject.toml
Add a PLE code for the PyLint Error Codes (Python code that is very likely to be wrong). I also updated ruff to the latest version and updated the config as well.
=> Update ruff. Fix PLE & LOG lints

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Rename `composer_run_name` tag in MLflow to just `run_name`
=> Rename composer_run_name tag to run_name when logging to MLflow

composer/callbacks/memory_monitor.py, tests/callbacks/test_memory_monitor.py
Enables memory monitor to aggregate stats across GPUs.
With dynamic graph execution, some GPUs may have more memory usage than others; this update allows the user to aggregate memory stats across GPUs.
Discussed offline
Local testing via: https://github.com/mosaicml/llm-foundry-private/pull/153
=> enable aggregate mem monitoring

composer/trainer/dist_strategy.py, tests/trainer/test_fsdp.py
Add SHARD_GRAD_OP to device mesh error check. Avoids nasty torch error if user incorrectly specifies mesh shard combo
=> Add SHARD_GRAD_OP to device mesh error check

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bump version to 0.20.1 ahead of patch release for torch 2.2.1
=> Bump version to 0.20.1

.github/workflows/daily.yaml, .github/workflows/pytest-cpu.yaml, tests/conftest.py, tests/fixtures/fixtures.py
Removes the s3_bucket flag in pytest and adds it to the fixture. This makes the pytest cicd more generalizable.
=> Remove s3_bucket pytest cli flag

.github/mcli/mcli_pytest.py
Removes the s3_bucket flag from gpu test
=> Remove s3_bucket flag from gpu test

composer/core/callback.py, composer/core/engine.py, composer/core/event.py, composer/core/state.py, composer/trainer/trainer.py, tests/test_events.py, tests/trainer/test_trainer.py
Adds ITERATION_START, ITERATION_END, and ITERATION_CHECKPOINT to Event, Engine, and Callback. Increments iteration during training based on iteration length defined in State. Iteration length is a private variable in State and should have no effect by default.
commit-id:bdbe33f2
---
**Stack**:
- #3087
- #3076 ⬅
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> Add Iteration related Events

composer/core/state.py
Adds a docstring to _iteration_length in state to clarify how an iteration is defined and where it's used in the training loop.
=> Add docstring to _iteration_length

composer/loggers/mlflow_logger.py, setup.py, tests/loggers/test_mlflow_logger.py
Enforce async logging flush in mlflow logger at `post_close` call so that there is no left over logging data.
=> Enforce async logging flush in mlflow logger at `post_close` call

composer/datasets/utils.py
Removes slash in docstring for better formatting
=> Remove slash

composer/core/__init__.py, composer/core/evaluator.py, composer/trainer/trainer.py
Replace errors with warnings for eval args. 
Along for the ride, cleans up some of the seq parallel stuff by centralizing validation
=> Replace errors with warnings for eval args

setup.py
There was an issue with mlflow 2.11 related to serving models that was fixed in 2.11.1
=> Bump mlflow min pin

composer/callbacks/eval_output_logging_callback.py, composer/models/huggingface.py, composer/utils/misc.py, composer/utils/object_store/oci_object_store.py, docs/source/trainer/file_uploading.rst, tests/utils/test_misc.py
Previously we were implicitly rounding down in the interval calculation because we were multiplying a decimal with a `Time`. The subsequent `math.ceil` therefore did not have the intended effect. This PR remedies that by using `.value` on the time, so the `math.ceil` properly applies to the unrounded decimal. Note: this will slightly change the exact pattern of when the interval scheduler returns true, but it will bring the implementation into line whether your max duration is in epochs or batches. Previously they were different.
The impetus for this is that it resolves a div by zero error if you only have one batch and have a `0.XXdur` interval. Manually tested it is resolved in addition to unit tests.
Along for the ride, fixes some typing that was complaining locally.
=> Fix rounding issue in interval calculation

composer/core/state.py, composer/core/time.py, composer/metrics/nlp.py, composer/models/huggingface.py, composer/utils/__init__.py, composer/utils/warnings.py, tests/utils/test_warnings.py
This allows us to track deprecations and know immediately when they should be removed.
=> Add versioned deprecation warning

composer/core/data_spec.py, composer/datasets/in_context_learning_evaluation.py, tests/test_split_batch.py
This PR makes the _default_split_batch public. It is already being used outside the file it is defined in (see composer/datasets/in_context_learning_evaluation.py) and it also has unit tests (see tests/test_split_batch.py). This function can be used as a base function to write other batch splitting functions.
=> Making default_split_batch public

composer/optim/scheduler.py, tests/optim/test_scheduler.py
Changes the error checking in scheduler to check
1. if max_duration is greater than t_max
2. if t_warmup and t_max are different units
Previously it only checked if t_warmup and max_duration were different units which is incorrect because a valid schedule can have t_warmup and max_duration as different units.
=> Add checks to schedulers

composer/loggers/mosaicml_logger.py
`test_exception_to_json` was failing because we left the exception attributes in the default Exception class in the attributes value. Created a copy of a generic Exception and it's default attributes to filter them out.
Test is now fixed.
=> Removed default attrs from exception class in the attrs dict

composer/utils/checkpoint.py, composer/utils/object_store/oci_object_store.py
PyTorch will hold any exception raised during this [read_data](https://github.com/mosaicml/composer/blob/ee13deadef1935b6054d1458f340971e5af4a635/composer/utils/checkpoint.py#L227), torch code pointer: https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/utils.py#L246-L255
PyTorch only raise the exception after communicate the exception across ranks https://github.com/pytorch/pytorch/blob/main/torch/distributed/checkpoint/utils.py#L251, but issue is that communication iteself might fail because comms mis-match across ranks. In this case, it raised NCCL error, and hide the real read_data exceptioin. 
This PR print the exception immediately. It still raise NCCL error, but at least, it prints the checkpoint downloading error. 
on 8-gpu checkpoint load test, i manually …
=> Explicitly print checkpoint downloading exception

composer/utils/dist.py
Allows for passing `rank` and `num_replicas` to `dist.get_sampler`
=> Passing rank and num_replicas to dist.get_sampler

CONTRIBUTING.md, composer/utils/compression.py, docker/Dockerfile, tests/utils/test_compression.py
Fixes the issue encountered here https://github.com/mosaicml/composer/pull/3118#issuecomment-2014108923 where `lzma` is refusing to decompress a file in the docker container.
The version of lzma provided by the lzma package has a bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700681
where it refuses to decompress if the file extension does not match, causing the test to fail. This could be worked around but the `xz-utils` package already provides a version of `lzma` that does not have this issue, so that can be used instead.
=> Compressor fixes

composer/models/huggingface.py, composer/trainer/trainer.py, tests/models/test_hf_model.py
This PR fixes an issue when using MPS device and composer's classifier. When computing metrics, `outputs` is copied to the cpu but not `batch` which creates some downstream error.
Fixes https://github.com/mosaicml/composer/issues/3094
=> In case of MPS device also copy batch to CPU

composer/utils/checkpoint.py, composer/utils/retrying.py
add object_store checkpoint downloading retry
bigning-debug-cp-loading-2-J6z0wB  **ConnectionError**
in the logging, there is one rank succeeded at 2nd attempt. 
another run: bigning-debug-cp-loading-2-9Lq8am **ChunkedEncodingError**
=> Composer object store download retry

composer/core/data_spec.py, composer/core/state.py, composer/datasets/in_context_learning_evaluation.py, composer/trainer/trainer.py
Fixes sequence parallel error conditions and adds type float for microbatch_size in typehints
=> Fixing sequence parallel error conditions and adding type float for microbatch_size in typehints

composer/core/engine.py, tests/test_engine.py
This is a workaround for https://github.com/mosaicml/composer/issues/3151 that at least prevents the import from crashing. A better long term solution may be possible.
- [] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
=> Prevent crash if signal handler cannot be set

composer/algorithms/utils/augmentation_primitives.py, setup.py
Seems they deprecated the old imports at some point and we didn't notice. Now they are gone. The code quality workflow was continuously upgrading pil even though we have the expected version pinned in dockerfile.
=> Pin pillow for code quality workflow

composer/trainer/mosaic_fsdp.py
```
In [2]: version.parse('2.3.0.dev20240110+cu121') < version.parse('2.3.0')
Out[2]: True
```
=> Fix torch version check

composer/utils/checkpoint.py
When run diagnostic on r15z1, we found OCI download error in other two places. Adding the retry to those object store downloading. 
bigning-debug-cp-loading-2-Cv5Bsh
=> add more retry to checkpoint downloading

composer/cli/launcher.py
For runs that call composer commands twice, we would error on creating a new log file because an existing log file had already been created on the first composer command. This changes the behavior to append to the existing or write a new file if doesn't exist already.
Ran a yaml that calls composer twice, verified that logs append
=> Append to gpu rank log files instead of throwing error

composer/callbacks/memory_snapshot.py
Fix memory snapshot naming with the defaults. 
https://github.com/mosaicml/composer/issues/3170
=> fix remote file naming

composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py
issue: https://github.com/pytorch/pytorch/issues/123272
4-1-ift-debug-DIBjG6
=> [fix] DTensor + SHARD_GRAD_OP + use_orig_params

composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py, composer/trainer/trainer.py
Fix the `FSDP.optim_state_dict_to_load` OOM, it's already in pytorch>=2.3.0 https://github.com/pytorch/pytorch/pull/117261
1. **before** the change, it oom in the first forward dbrx-dense-20b-debug-autoresume-AdiVZi
here is the memory before the forward:
2. **after** the change, it can train `dbrx-dense-20b-debug-autoresume-3QVblX`
=> Fix the FSDP.optim_state_dict_to_load OOM

docs/source/trainer/file_uploading.rst
PR https://github.com/mosaicml/composer/pull/3165 introduced flakey warnings when running doctests.
now skipping and disabling
=> Filter neptune warning in doctests

composer/trainer/trainer.py
This PR removes the deep copy of the `metrics: Dict[str, Metric]` object in the function `_compute_and_log_metrics`.
This function does the following:
- Copy of the metrics (using `copy.deepcopy`)
- Computation of the values of the metrics on the copy
It is called 3 times in `composer.trainer.Trainer`:
- [At every batch in the training loop](https://github.com/mosaicml/composer/blob/dev/composer/trainer/trainer.py#L2454) to compute the metrics on this batch, and [at the end of the epoch](https://github.com/mosaicml/composer/blob/dev/composer/trainer/trainer.py#L2490)
- [At the end of the evaluation loop](https://github.com/mosaicml/composer/blob/dev/composer/trainer/trainer.py#L3417) to compute the metrics on the evaluation dataset
I don't see the need for copying the metrics before …
=> Removal of metrics deepcopy before computing the metrics

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
https://databricks.atlassian.net/browse/GRT-2836
=> Fix MLFlow Tag Name for Resumption

composer/datasets/in_context_learning_evaluation.py, composer/datasets/utils.py, composer/metrics/nlp.py
We are migrating ICL tasks from composer to foundry and need to deprecate the existing composer implementations. The migration PR is here: https://github.com/mosaicml/llm-foundry/pull/936
=> Add deprecation warnings for ICL datasets/helper functions/metrics

composer/trainer/trainer.py
Fix token logging. Previously, if max duration was set in epochs, the previous timestamp would also be set to have the same token value as current timestamp (it has a different epoch value). This meant the final token value would not be logged.
Instead, we just log the token value as long as non-zero number of tokens have been logged, as is consistent with logging in batch loop
Before: 0-8gpu-baseline-1zCALJ
```
mosaicml/time/batch                            1
mosaicml/time/batch_in_epoch                   0
mosaicml/time/epoch                            1
mosaicml/time/remaining_estimate_unit          hours
mosaicml/time/sample                           8
mosaicml/time/sample_in_epoch                  0
mosaicml/time/token                            0
mosaicml/time/token_in_epoch …
```
=> Fix token logging

.github/workflows/daily.yaml, docker/Dockerfile
=> Fix daily test images

docker/Dockerfile
Uses the latest flash attention version and installs with no build isolation (as they [recommend](https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features)) in docker images, rather than building from source.
=> Use flash-attn 2.5.8 with no build isolation in docker images

composer/callbacks/checkpoint_saver.py, composer/utils/checkpoint.py
Adds a empty_cache() to clear the cache right before checkpointing. Some amount of memory is used by NCCL during checkpointing and if we are operating near the total memory of the GPU, empty_cache() can help clear unused memory and allow checkpointing to succeed.
=> Add a torch.cuda.empty_cache() in utils.save_checkpoint

composer/utils/checkpoint.py
Trainer has an argument `load_strict_model_weights` which defaults to `True`. However, the same argument in `load_checkpoint` defaults to `False`, whereas it should be consistent with the Trainer argument.
=> load_checkpoint defaults to strict weight match

tests/utils/object_store/test_gs_object_store.py
Require 2 steps for GS object store. Ensures optimizer step in case of all NaN on first step
=> Require 2 steps for GS object store 

tests/utils/object_store/test_gs_object_store.py
Change precision for daily tests
=> Change precision for daily tests

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Create new Mlflow run by default and introduce `run_group`. Currently the default behavior is to resume the Mlflow run by searching for existing run with the same name. As we discussed we should make the default behavior start a new run. Additionally to mirror the `group` in wandb, we are introducing the `run_group` tag.
=> Create new Mlflow run by default and introduce `run_group`

.github/workflows/daily.yaml
Torch 2.3 daily tests take a long time. Going to raise the timeout for now.
=> Raise the daily test timeout

composer/utils/checkpoint.py, tests/trainer/test_fsdp_checkpoint.py, tests/utils/object_store/test_gs_object_store.py
Loads metadata before loading sharded checkpoint state to check if 'optimizers' is a root-level key. This is for backwards compatability with older torch/composer versions, where the recommended sharded checkpoint loading/saving required us to put 'optimizers' as a top-level key. With newer torch (>=2.3.0), we don't do this anymore, but we still need checkpoints to be backwards compatible.
=> Make sharded checkpoint loading backwards-compatible

composer/core/state.py
Remove CPU offload for DDP/single-gpu. With the unified API, we added this in, but it is not needed / does not exist in prior versions. This really slows down GPU tests.
=> Remove CPU offload for DDP/single-gpu

tests/trainer/test_fsdp_checkpoint.py
Adds backwards compatability tests for versions 0.19, 0.20, 0.21, and recently-released 0.22.
=> Adding more checkpoint backwards compatability tests

composer/core/engine.py
Currently produces duplicate print statements cause it may close both when you call `.close()` and `atexit`
=> Don't close the engine if its already closed

composer/trainer/trainer.py
Uses `evaluator.device_eval_microbatch_size` instead of `evaluator.dataloader.device_eval_batch_size`, now that it is set correctly (see https://github.com/mosaicml/llm-foundry/pull/1100/files).
=> Replace `evaluator.dataloader.device_eval_batch_size` with `evaluator.device_eval_microbatch_size`

composer/utils/checkpoint.py, tests/trainer/test_fsdp_checkpoint.py
Fixes FSDP checkpoint backwards compatibility tests, and raises a helpful error for likely torch version mismatch on checkpoint load. For context, the test that was failing was when trying to load a checkpoint written with torch 2.3.0 when using torch < 2.3.0, since the older torch versions could not correctly read the new metadata file.
=> Fix backwards compatibility tests, raise error for torch version mismatch

composer/algorithms/sam/sam.py, tests/algorithms/test_sam.py
I'm tracing this bug back to Composer coming from using LLMFoundry after we noticed that our models didn't learn anything when running distributed training with FSDP alongside SAM and a LR scheduler. If running the same setup but w/o distributed training (on a single GPU), everything works fine.
Just checkout the source branch at the commit `d882d8f4`, which contains only the tests (without the fix), and run:
```bash
make test-dist-gpu WORLD_SIZE=1 EXTRA_ARGS="tests/algorithms/test_sam.py::TestSAMParamGroups"
make test-dist-gpu WORLD_SIZE=2 EXTRA_ARGS="tests/algorithms/test_sam.py::TestSAMParamGroups"
```
- When using SAM with a LR scheduler that resets the starting `param_groups[0]['lr']` to `0.0` (such as  `CosineAnnealingWithWarmupScheduler`),  it varies the learning rate at …
=> Fix: SAM not working with FSDP/DeepSpeed and LR scheduler.

composer/utils/object_store/mlflow_object_store.py
We are fixing an occasional hang during artifact upload by patching mlflow to pass a request timeout along, and to set the default socket timeout in the upload worker function. This will be fixed upstream by mlflow in the next release, at which point we can remove the patch.
Manual tests:
- upload without the timeout flag set: `upload-timeout-test-without-2-xlw9bk`
- upload with the timeout flag set: `upload-timeout-test-3-UzoDmx`
- upload with the timeout flag set (and seemingly did something, as this run took longer to complete than the others): `upload-timeout-test-2-sVfbkw`
=> Add upload timeout patch to mlflow on azure

composer/loggers/remote_uploader_downloader.py
This PR adds support for adding a stagger based on local rank to the upload workers (i.e. the upload worker will wait by local rank * stagger). We are only exposing this via environment variable, as this is not something most users should be setting themselves.
Manual test:
- `stagger-upload-test-2-IggDEG` (note that each ranks file was uploaded 1 minute apart)
=> Add option to stagger uploads based on local rank

composer/utils/object_store/mlflow_object_store.py
Add an explicit close to the mlflow upload patch. Should've been included in the first patch.
Manual test:
- `explicit-close-1-zQiMjq`
=> explicit close

composer/cli/launcher.py
The environment variable `NCCL_ASYNC_ERROR_HANDLING` is deprecated and it is suggested to use `TORCH_NCCL_ASYNC_ERROR_HANDLING` instead.
Applies #3266
=> Update NCCL_ASYNC_ERROR_HANDLING env variable

composer/trainer/mosaic_fsdp_utils.py, composer/utils/checkpoint.py
PyTorch Issue: https://github.com/pytorch/pytorch/issues/125740
When pytorch 2.3 saves checkpoint files, if there are duplicated tensors, it will do dedup. In the dedup, it tries to balance the storage needed for each rank, so the duplicated tensors are saved on different ranks. The consequest is that, when loading checkpoint, each rank needs to read files saved by different ranks even without resharding. Ideally, each rank_k only needs to download rank_k and rank_0 files. 
we save the duplicated tensors to the smallest rank only. This is how torch2.1 and torch2.2 do the dedup. 
Tested  on 512 GPUs. Save and load both work.
=>  new dist_cp save planner to fix issue that each rank needs to download all checkpoint files 

composer/utils/object_store/uc_object_store.py, tests/utils/object_store/test_uc_object_store.py
Previously, the databricks SDK did not have `ls` built in, and we discovered a bug where we were not properly handling the truncation of the `ls` results (truncated to 999 elements). This PR fixes that bug by switching over to the built in `ls` in the databricks SDK.
Manual test, ran the convert to MDS script before and after, before it returns 999 elements, after it returns the full correct number (1350 from the directory I was testing)
=> Fix UCObjectStore.list_objects

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Return PyTorch Latest to docker list. The latest python version was not updated from 3.10 -> 3.11. This PR corrects the python version and ensures pytorch latest will actually build
=> Return PyTorch Latest

tests/trainer/test_fsdp_checkpoint.py
Fix daily tests by filtering a warning. https://github.com/mosaicml/composer/pull/3288 this PR fixed a test issue, ensuring the right code path runs. However, this code path causes a warning on older torch versions which we need to filter.
=> Fix daily tests by filtering a warning

composer/utils/compression.py, tests/utils/test_compression.py
Skip compression check with symlink files. Add unit tests.
Fixes an issue where some previous checkpoints where `.pt.symlink`
=> Skip compression check with symlink files

composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py
Monkeypatch Device Mesh ND Slicing. This allows us to create child meshes of multiple dimensions. 
We patch in this PR from Torch https://github.com/pytorch/pytorch/pull/119752 which will not be released until PyTorch 2.4
Toy script that now works which did not work before this PR:
```
from torch.distributed._tensor.device_mesh import DeviceMesh, init_device_mesh
from composer.utils import dist
from composer.trainer.mosaic_fsdp import patch_pytorch
dist.initialize_dist('gpu', timeout=10.0)
patch_pytorch()
child_mesh_dim_names = ("PP", "DP")
mesh_dim_names = ("PP", "DP", "TP")
mesh = init_device_mesh(
'cuda', (2, 2, 2), mesh_dim_names=mesh_dim_names
)
child_mesh = mesh[child_mesh_dim_names]
print(child_mesh)
```
=> Monkeypatch Device Mesh ND Slicing

composer/loggers/remote_uploader_downloader.py, composer/utils/retrying.py, tests/loggers/test_remote_uploader_downloader.py
Allows overwrite on upload retries.
If an upload fails and results in a partial upload, we should allow overwriting.
=> Allow overwrite on upload retry in remote uploader downloader

README.md, composer/cli/launcher.py, composer/loggers/mosaicml_logger.py, docs/source/index.rst, examples/checkpoint_autoresume.ipynb
Updates outdated doc links & naming
=> Update platform references

composer/utils/checkpoint.py, composer/utils/dist.py
@j316chuck found HSDP with 1 node 2X4 device mesh run can't resume. rank 0 failed [this checkpoint files broadcast](https://github.com/mosaicml/composer/blob/dev/composer/utils/checkpoint.py#L314-L318) . It's because rank 4 (which is in the same replica pg group as rank 0) doesn't join this collective call because of [this if condition](https://github.com/mosaicml/composer/blob/dev/composer/utils/checkpoint.py#L307). 
So the fix is to let all the first rank of shard pg group joins the broadcast , but only local rank 0 writes to file
before:
[nccl timeout] mpt-125m-hybrid-resumption-1-node-tYv2bB
after:
mpt-125m-hybrid-resumption-1-node-pzWqX1
mpt-125m-hybrid-resumption-1-node-RV4ovO
mpt-125m-hybrid-resumption-1-node-NlOtP5
mpt-125m-hybrid-resumption-1-node-ajvSHb
checked the logging, rank …
=> Fix HSDP with ShardDegree < 8 

composer/checkpoint/state_dict.py
Turns out it's empty dict for nonzero ranks for unsharded state dicts because for torch 2.1.2 we set the `FullStateDictConfig` `rank0_only` flag to `True` and for torch >2.1.2, the `dcp.get_model_state_dict` function always has empty dict for nonzero ranks for unsharded state dicts
=> Update docstring for get_model_state_dict

composer/core/state.py, composer/trainer/trainer.py, composer/utils/checkpoint.py
Fixes:
Save: `0-16gpu-save-NTsI27`
Load: `0-16gpu-save-AVhYVg`
=> Bugfixes to FSDP + TP

composer/loggers/mosaicml_logger.py, composer/loggers/remote_uploader_downloader.py
Adds metadata logging to mosaicml logger for when checkpoint upload starts when a checkpoint is done loading. The information logged is the timestamp and the training duration of the checkpoint.
Tested in `events-test-8ReCjx`
=> Add checkpoint events to mosaicml logger

docker/generate_build_matrix.py, tests/trainer/test_fsdp_checkpoint.py
Fix FSDP ckpt by filtering User Warning
Fix failing dailies
https://github.com/mosaicml/composer/actions/runs/9231304954
=> Fix FSDP ckpt by filtering User Waring

composer/callbacks/memory_snapshot.py
This PR uses `_record_memory_history_impl` instead of `_record_memory_history_legacy` (previous) to capture memory snapshot. See https://github.com/pytorch/pytorch/blob/main/torch/cuda/memory.py#L698-L738. With `enabled =all`, this captures all (c++ and python) alloc/free events and gives better memory timeline and stack trace information. 
`_record_memory_history_impl` exists for pytorch 2.1, 2.2, 2.0, no version gating is needed.
=> Improving memory snapshot 

composer/models/base.py
This PR changes the output type of the `ComposerModel`. As long as the output type is a tensor, a tensor list, a dictionary of tensors or has a method `cpu()` (to satisfy [this](https://github.com/mosaicml/composer/blob/dev/composer/trainer/trainer.py#L3357), note that if you return a list of non-tensors it will not break the pipeline) we should be able to return any type.
No issue has been opened yet.
cc: @JAEarly
=> change ComposerModel output type

composer/core/state.py
We don't use eval state at all -- currently we simply set the eval dataloader state only if the dataset is a StreamingDataset, and we also simply set the current sample to 0 (meaning that we start from the beginning). This is not needed at all and is causing some errors when resuming training on various numbers of GPUs. Since we iterate through the entire eval loader every single time we do eval, there is no notion of state that has to be preserved for eval datasets. This PR removes that functionality completely.
Specifically, this caused errors with resuming on various numbers of GPUs and setting `device_eval_batch_size`. When going from 24 to 32 gpus, with both runs specifying `device_eval_batch_size` of 2, Streaming would try to resume using a global eval batch size of 64 samples, but …
=> Remove evaluator state

composer/algorithms/channels_last/channels_last.py, composer/algorithms/no_op_model/no_op_model.py, composer/devices/device_mps.py, composer/devices/device_neuron.py, composer/devices/device_tpu.py, composer/utils/dist.py, tests/common/models.py, tests/trainer/test_ddp_sync_strategy.py, tests/trainer/test_trainer_eval.py, tests/utils/test_autolog_hparams.py, tests/utils/test_fx_utils.py, tests/utils/test_inference.py, tests/utils/test_module_surgery.py
According to [mypy documentation](https://mypy.readthedocs.io/en/stable/class_basics.html#annotating-init-methods):
> if `__init__` has no annotated arguments and no return type annotation, it is considered an untyped method
=> Add return type annotation when __init__ doesn't take any argument

composer/trainer/trainer.py
Resolves type issue with device train microbatch size. See https://github.com/mosaicml/composer/issues/3348
=> Fix type check issue with device train microbatch size

composer/trainer/trainer.py, tests/trainer/test_checkpoint.py
By making the instantiation of the `CheckpointSaver` optional inside the `Trainer`, the user can provide a (custom) callback used for saving, loading and resumption.
- Fixes https://github.com/mosaicml/composer/issues/3317
=> Optional `CheckpointSaver` instantiation inside the `Trainer`

composer/loggers/mlflow_logger.py, setup.py
When running on MAIT or with a databricks secret, default to the databricks workspace. This lets the user skip specifying `tracking_uri`. 
Similarly, if specifying databricks secret, we now autopopulate `/Users/<username>` to experiment id, simplifying user experience.
Exmaple run name: ft-llama-3-8b-r4z14-v0-4roAvl
=> MLFlow better experiment defaults

composer/checkpoint/state_dict.py, composer/utils/collect_env.py, tests/checkpoint/test_state_dict.py, tests/test_state.py
Renames keys in `get_composer_env_dict`, following up on naming discussion in https://github.com/mosaicml/composer/pull/3311. Also cleans up code, removing a NamedTuple class which is immediately converted to a dictionary
=> Rename metadata keys

docker/Dockerfile, docker/build_matrix.yaml, docker/generate_build_matrix.py
This PR changes the install methodology to utilize the mellanox debian package for installation vs the installer script. This should make it easier to both pin on the latest if we choose, or to ensure that the system can install the packages appropriately.
=> Upgrade Mofed with apt

composer/trainer/trainer.py, tests/trainer/test_checkpoint.py
Additional checks based on https://github.com/mosaicml/composer/issues/3357:
- Autoresume requires max_duration be specified on init and cannot accept `duration` in `fit`. Otherwise, Composer will autoresume from last checkpoint, and then the specified value of `max_duration` from `fit` will be incremented to the loaded max duration. In short, `fit(duration=...)` is not idempotent with autoresume.
- `reset_time` in `fit` does not work with autoresume as it will force a restart in training. Instead, time should be ignored on load, which is used in initial load and not on autoresume load
- Implicitly prevents multiple calls to fit -- if you cannot increment duration in fit or reset time, it is not possible to call fit twice.
=> Autoresume Validation with Max Duration

composer/_version.py, composer/loggers/neptune_logger.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Deprecate and bump verstion to 0.23.0
Daily test: https://github.com/mosaicml/composer/actions/runs/9371911640
=> Deprecate and bump verstion to 0.23.0

composer/core/evaluator.py
For python 3.9 and up, the old type checking shouldn't work -- this is the same fix as #3349 #3348
=> Proper type checking for `device_eval_microbatch_size`

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps composer version to 0.23.1. This will mainly include torch 2.3.1 compatability.
=> Composer version bump to v0.23.1

tests/test_engine.py
To prevent other logs from polluting the logs captured in `test_logging`, calls `caplog.clear()` and uses it as a context manager instead.
=> Clear caplog and use as context manager in test_logging

composer/loggers/mlflow_logger.py
We would like to use MLFlow outside of the databricks platform. For such scenario, the package `databricks-sdk` don't have to be installed. With this contribution the import of the `databricks.sdk` is gated by the presence of the `DATABRICKS_TOKEN` environment variable, making it possible to reduce the dependency chain.
=> Only requires `databricks-sdk` when inside the Databricks platform

composer/distributed/dist_strategy.py
Remove FSDP restriction from PyTorch 1.13. We added this to give a friendlier error for users when PyTorch had a bug, but the corresponding issue is closed and fixed and has been patched for a while since PyTorch 2.
=> Remove FSDP restriction from PyTorch 1.13

composer/trainer/trainer.py
See https://github.com/mosaicml/composer/issues/3397.
=> Check for 'CUDA error: out of memory' when auto-microbatching

composer/utils/dist.py, tests/utils/test_dist.py
This PR adds additional utils for busy waiting on a node using a signal file lock. The main difference between the added utils and the current approach used is that the signal file has a randomly generated identified appended to it, to better support use cases that include multiple runs using a shared file system that may interfere with each other. Future PRs will replace the signal file uses in Composer (and after release Foundry) with these utils, but just want to start with the util implementation to keep PRs small.
Related to https://github.com/mosaicml/llm-foundry/pull/1253
=> Busy wait utils in dist

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Add buffering time to mlflow logger, tested with unit test along with manual testing.
=> Add buffering time to mlflow logger

composer/trainer/_patch_pytorch.py
Add missing import for PyTorch 2.3.1 device mesh slicing
=> Add missing import for PyTorch 2.3.1 device mesh slicing

setup.py
If pynvml is not installed, mlflow will not record GPU system metrics.
Test run with GPU metrics: https://dbc-559ffd80-2bfc.cloud.databricks.com/ml/experiments/1021774554687852/runs/9cbe6daa2cb64297bf6b3b649312f462/system-metrics?o=7395834863327820
=> Add pynvml to mlflow dep group

composer/cli/launcher.py
Simplify launcher world size parsing. Now, `composer -n` correctly enables running on fewer GPUs when iterating on a single machine.
=> Simplify launcher world size parsing

.github/workflows/pr-cpu.yaml, composer/devices/device_gpu.py, composer/metrics/nlp.py, tests/checkpoint/test_state_dict.py, tests/metrics/test_nlp_metrics.py
This reverts commit 2cf9262e988c7cc4ee107259b98efec0298c5017. #3394
=> Revert "Optionally use `flash-attn`'s CE loss for metrics (#3394)"

composer/core/time.py, tests/test_time.py
This allows the user to set the epoch in the iteration. This is needed for PPO to signal to early break out of an iteration by setting the epoch to the max number of epochs in an iteration.
=> Add setter for epoch in iteration

docker/Dockerfile, setup.py
Move pillow dep as required. Previously, we had pillow as only under `dev`, but it is required for the import tree as several algorithms use it.
=> Move pillow dep as required

composer/loggers/mlflow_logger.py
In mlflow logging, users that wanted to log into the "/Shared/" file directory had an extra slash in their modified experiment names, leading to Mlflow not recognizing existing experiments, trying to create them, and then claiming they already exist.
This PR accounts for that edge case and removes the extra slash added.
Prior to this PR, there was a bug where users who directly wanted to mlflow-log to the `/Shared/` workspace would be able to do so after the first run of an experiment name, but would not be able to for following runs of the same experiment name. We found that an extra '/' was prepended to the experiment name (yielding an experiment name of `//Shared/...` after `'/' + os.path.join('Users', databricks_username, experiment_name)`), leading to `get_experiment_by_name` not …
=> fixing mlflow logging to Databricks workspace file paths with /Shared/ prefix

composer/callbacks/eval_output_logging_callback.py, composer/core/evaluator.py, composer/loggers/mlflow_logger.py
Fixes a few typing issues that local pyright/external code was complaining about.
=> Fixes some typing issues

setup.py
Bumping MLflow version to 2.14.1 to incorporate correct buffering logic for logging to MLflow during runtime.
=> Bumping MLflow version to 2.14.1

tests/trainer/test_fsdp_checkpoint.py
Some pytests require torch >= 2.3.0 but were not properly skipping. This pr simply checks the torch version to determine if the test should run
=> Skip HSDP + TP pytests that require torch 2.3 or above

docs/source/notes/distributed_training.rst
Fixes a few typos / mistakes in TP docs.
Manual docs build succeeded:
Modifications to docs are correctly reflected:
=> Fixes to TP Docs

composer/loggers/mlflow_logger.py
Lower the system metrics logging frequency to reduce MLflow server's load. System metrics logging is using a different async logging queue from normal metrics, so the time buffering doesn't apply to system metrics. This design was by intention so that MLflow can terminate system metrics separately. 30s is the logging frequency of wandb, so there should be no user experience regression.
=> Lower the system metrics logging frequency to reduce MLflow server's load

composer/core/event.py
Fix docstring for EVAL_AFTER_ALL/EVAL_BEFORE_ALL. Previously was named as AFTER_EVAL_ALL/BEFORE_EVAL_ALL incorrectly. 
Partially resolves https://github.com/mosaicml/composer/issues/3443
=> Fix docstring for EVAL_AFTER_ALL/EVAL_BEFORE_ALL

composer/loggers/mosaicml_logger.py
Remove close flush for mosaicml logger. All data is force flushed on fit/predict/eval_end. Attempting to log on close may result in an error as it tries to schedule a future while the python interpreter is shutting down. Instead, we should only wait on existing futures already scheduled.
While we attempt to not schedule futures and do a blocking op currently, under the hood mcli still uses asyncio which uses futures.
=> Remove close flush for mosaicml logger

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bump version to v0.23.5
Daily test
https://github.com/mosaicml/composer/actions/runs/9756188949/job/26933121108
A key rotation issue needs to be figured out with infra team. Ignoring it for now.
=> bump version v0.23.5

composer/loggers/mosaicml_logger.py
- removes log exception from mosaicmllogger because we are no longer using it to record exceptions.
Dependent on foundry pr to merge first: https://github.com/mosaicml/llm-foundry/pull/1292
=> Remove Log Exception

composer/callbacks/speed_monitor.py
Corrected definition of `throughput/device/mfu` from "`throughput/device/flops_per_sec` divided by world size"  to "`throughput/device/flops_per_sec` divided by flops available on the GPU device."
=> Corrected docs for MFU in SpeedMonitor

composer/callbacks/checkpoint_saver.py, composer/loggers/remote_uploader_downloader.py
Move checkpoint event to emit a run event when the symlink is uploaded. This means that the run event will accurately track when a checkpoint upload finishes.
A previous approximation was merged in #3316 
e2e test `checkpoint-events-test-rd9zih`
=> Fix checkpoint events

composer/loggers/mosaicml_logger.py, tests/loggers/test_mosaicml_logger.py
Goal is to add new TRAIN_START run event outlined in this doc:
https://docs.google.com/document/d/1Rk43aTNFXIUULs0OvTMQGXrV8bJkITmjICyGmMrF2Zc/edit
This will correspond to the FIT_START composer event
=> Add fit start to mosaicmllogger

composer/trainer/trainer.py, composer/utils/checkpoint.py, composer/utils/dist.py
Use the previously added utils to get a signal file name that is safe on shared file systems. Previously the name would clash.
Tested simple train and load (don't have a multinode shared fs to actually test that part on):
train: `dist-utils-train-1-UExzEF`
load: `dist-utils-load-2-Uoq35b`
=> Get a shared file system safe signal file name

tests/checkpoint/test_download.py
The composer get_model_state_dict is torch version-proof, so it won't cause any errors with older versions of torch
=> [fix-daily] Use composer get_model_state_dict instead of torch's

composer/checkpoint/__init__.py, composer/checkpoint/upload.py, tests/checkpoint/test_upload.py
Adding upload API, [design doc](https://docs.google.com/document/d/14ruvosCcVgqDMJGPPmi6HRm6YvJO3BKUiZFN0KhBGR4/edit#bookmark=id.qzhhpmitypba). This API uploads the input files to remote object store, interface design:
```
def upload_file(
dest_dir: str,
source_path: Optional[str]=None,
symlink_granularity: Optional[str]=None, # file, dir, or None
symlink_name: Optional[str]='latest.symlink',
async_upload: bool = True,
state: Optional[State] = None,
overwrite: bool = False,
):
"""Standalone function for uploading a checkpoint file.
This function does not actually upload the checkpoint; it initiates the RemoteUploader's uploading of it
Args:
source_path (str): The path to the file to upload.
dest_dir (str): The directory/uri to upload the file to.
symlink_granularity (Optional[str]): The …
```
=> [Checkpoint V2] Upload API

docs/source/conf.py
Patch conf.py for readthedocs sphinx injection deprecation. As build time injection is deprecated, we apply the patch recommended by readthedocs.
=> Patch conf.py for readthedocs sphinx injection deprecation.

composer/distributed/dist_strategy.py, composer/trainer/trainer.py, tests/checkpoint/test_download.py, tests/trainer/test_fsdp.py, tests/trainer/test_fsdp_param_groups.py, tests/trainer/test_tp.py
This PR addresses https://github.com/mosaicml/composer/issues/3493, where we were adding all model parameters into the optimizer state after FSDP wrapping. This change uses the previous flow for param_groups > 1, where we:
1. Get the mapping between params in the optimizer group and their names by using the pointers (found with `id`) of the tensors
2. Store the extra param group info, such as LR, wd, etc. in a separate dict
3. Iterate over the fsdp wrapped parameters, and populates the param_groups based on the names of the fsdp wrapped tensor and the mapping from before.
This change relies on `use_orig_params=True`, so an error is thrown if a subset of parameters is passed into the param_groups.
**NOTE**: at the moment, tensor parallelism breaks with multiple param_groups (as the ptrs of …
=> Fix bug when subset of model parameters is passed into optimizer with FSDP

tests/utils/object_store/test_azure_object_store.py, tests/utils/object_store/test_gs_object_store.py
For GCS key, we're waiting for the request https://databricks.atlassian.net/browse/SOPS-719?focusedCommentId=5299281
For Azure, @j316chuck  will start the request once we go through the GCS request process. 
https://github.com/mosaicml/composer/actions/runs/10207147591
[gpu tests still running] https://github.com/mosaicml/composer/actions/runs/10207236494
=> Disable gcs azure daily test

composer/trainer/trainer.py, pyproject.toml
This PR deprecates the usage of DeepSpeed in Composer. We have not updated DeepSpeed in a long time and do not actively maintain the integration. Composer is tightly coupled to PyTorch FSDP which provides similar functionality, and we are developing all new functionality on top of FSDP and PyTorch native, not DeepSpeed, for parallelism. Before removal we will provide a migration guide for anyone still using DeepSpeed. In the meantime, users are welcome to open a GitHub issue if they have any trouble.
=> Deprecate deepspeed

composer/devices/device_gpu.py, tests/checkpoint/test_state_dict.py
This reverts commit cccc8a7c02a8bab52263365cec1da87a7e2c9bdc.
Seeing errors with creating gloo PG on specific clusters. Will root cause and try to get this merged again. Props to @JackZ-db for first reporting!
=> Revert "Use gloo as part of DeviceGPU's process group backend (#3509)"

composer/checkpoint/load.py, composer/core/state.py, composer/trainer/trainer.py, tests/checkpoint/test_load.py
Eval'ing after resuming from checkpointing broke since calls to `prepare_fsdp_module` in `state.py` didn't modify the handles and FSDP modules in modules. We fix this by moving `automicrobatch_fsdp_hook_handles` and `fsdp_modules` into `State` instance variables instead of `Trainer` instance variables.
Fixed regression test that previously broken: `mpt-7b-composer-eval-regression-KkY29t`
=> Move hooks and fsdp modules onto state rather than trainer

composer/trainer/trainer.py
save_overwrite is no longer required to be false for autoresume
=> Fix autoresume docstring (save_overwrite)

composer/core/state.py, tests/trainer/test_fsdp.py
Add FSDP input validation for `use_orig_params` and `activation_cpu_offload` flag
https://databricks.atlassian.net/browse/GRT-3143 
- Added unit test
- Before error log: `iteration-23-qXpOcN`
```
[rank0]: │ /usr/lib/python3/dist-packages/composer/core/engine.py:493 in _run_callbacks │
[rank0]: │                                                                              │
[rank0]: │   490 │   │   │   ctx = cast(ContextManager, contextlib.nullcontext()) if ma │
[rank0]: │   491 │   │   │   with ctx:                                                  │
[rank0]: │   492 │   │   │   │   self._debug_log(event, f'Running callback {type(cb).__ │
[rank0]: │ ❱ 493 │   │   │   │   cb.run_event(event, self.state, self.logger)           │
[rank0]: │   494 │ …
```
=> Add FSDP input validation for use_orig_params and activation_cpu_offload flag

.github/workflows/daily.yaml, composer/loggers/wandb_logger.py
Wandb 0.17.6 changed disabled mode in this PR: https://github.com/wandb/wandb/pull/8037, which breaks wandb logger when running with disabled mode as certain attributes (entity, project) are not set. This wraps these attributes in a check to see if they exist.
This should not break any internal workflows as we have churned from WandB completely in favor of MLFlow, but it may affect open source users so we should prioritize including in patch release.
=> hasattr check for Wandb 0.17.6

composer/core/state.py
Previously, FSDP config validation only checked the state dict type if FSDP was enabled. As FSDP can be enabled later on after this validation check, e.g. via load_monolith_rank0_only=True or by manual wrapping in a callback, we should instead check the true value of state dict type in the config.
=> Fix FSDP Config Validation

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/code-quality.yaml, .github/workflows/daily.yaml, .github/workflows/pr-docker.yaml, .github/workflows/smoketest.yaml
Remove dev on github workflows. We now have `main`
=> Remove dev on github workflows

tests/utils/object_store/test_gs_object_store.py
We've got the new google cloud project, service account and keys with help from security team, now we can restore the google cloud object store test. 
daily test: https://github.com/mosaicml/composer/actions/runs/10310134721
=> restore google cloud object store test

composer/utils/object_store/s3_object_store.py, tests/utils/object_store/test_gs_object_store.py
use adaptive retry as default retry mode.  user reported uploading error `boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/tmpn7sa44l2/26aecfcf-aa70-4385-951a-0ab28f00bf8c to data-force-one-datasets/mosaicml-internal-checkpoints/jacob/lora/atnmlp-r16-lr0.0001-mlp-ep-4-a-32-sd-17/ep1-ba193-rank0.pt: An error occurred (SlowDown) when calling the CreateMultipartUpload operation (reached max retries: 4): Please reduce your request rate. `
adaptive retry also introduces client-side rate limiting https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html, 
Thanks @snarayan21  for testing:
`1b-bf16-baseline-lr-0-00042-wd-0-0008-dRoKZX`
=> use s3 boto3 Adaptive retry as default retry mode

.github/workflows/daily.yaml, .github/workflows/pr-gpu.yaml
I set `python-version` to `3.11` in the pr-gpu GA and daily GA.
The pr-gpu GA and daily GA both used an image with python 3.11 `mosaicml/pytorch:2.2.1_cu121-python3.11-ubuntu20.04` but had `python-version: 3.9`. This PR makes the image and python-version consistent by setting the python-version to 3.11.
=> Use python 3.11 in GAs

.github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, composer/core/precision.py, composer/core/state.py, composer/trainer/trainer.py, docs/source/doctest_fixtures.py, docs/source/trainer/checkpointing.rst, pyproject.toml, tests/algorithms/test_required_on_load.py, tests/trainer/test_checkpoint.py, tests/trainer/test_ddp_sync_strategy.py
Add Torch 2.4 Tests. Includes
- Updating error messages to latest versions in PyTorch 2.4
- Zero grad must be now called at end of fit w new ckpting API for stateless optimizers, https://github.com/pytorch/pytorch/issues/133415
=> Add Torch 2.4 Tests

composer/trainer/trainer.py, examples/TPU_Training_in_composer.ipynb, examples/exporting_for_inference.ipynb, examples/migrate_from_ptl.ipynb
`torch.optim.SGD` breaks with PyTorch 2.4.
https://github.com/pytorch/pytorch/issues/133415
Changes optimizer in notebook examples which are failing daily tests
=> Update Optim to DecoupledSGD in Notebooks

pyproject.toml, tests/utils/object_store/test_azure_object_store.py
Restore Azure tests. Key is re-enabled.
Along for the ride, ignores new warnings raised by latest Neptune Logger release.
=> Restore Azure Tests

composer/trainer/trainer.py
When an old checkpoint is loaded, any timestamp attributes associated with iteration are 0. This means those attributes are inaccurate and can't be correctly used. This fixes old checkpoints the first time they're loaded to set those attributes to the correct value.
=> Change iteration timestamp for old checkpoints

composer/utils/collect_env.py, tests/test_cli.py
Previous PR introduced a typo into `composer_collect_env` that caused it to crash. This PR fixes that and adds a simple test that makes sure it runs without error.
=> Fix typo in `composer_collect_env`

composer/utils/device.py
Adds a default `None` value to `get_device()` such that `get_device()` works as the docstring implies.
=> Add default value to get_device()

tests/trainer/test_fsdp_checkpoint.py
Adds backwards compatibility tests for v0.24.0
Daily tests pass: https://github.com/mosaicml/composer/actions/runs/10567933467
=> Checkpoint backwards compatibility tests for v0.24.0

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps version to 0.24.1. Doing a patch release so that we explicitly error when setting `device_mesh` in FSDPConfig -- this prevents users from accidentally running unintended parallelism styles (ex: FSDP when they wanted HSDP)
Dailies succeeded: https://github.com/mosaicml/composer/actions/runs/10584178277
=> Bump version to 0.24.1.

composer/utils/dist.py
Defaults `dist.initialize_dist` to `device=None`, which lets `get_device` autodetect hardware.
=> Init Dist Default None

.github/workflows/code-quality.yaml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/smoketest.yaml, setup.py
Updates the ci-testing to 0.2.2, which includes the switch to uv from pip. It also adds a numpy<2 pin to our deepspeed dependency group, as the version of deepspeed we have pinned requires numpy<2
=> Update ci-testing to 0.2.2

docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump Mellanox Tools

.github/workflows/daily.yaml, .github/workflows/pr-gpu.yaml
Dailies are broken with `uv` due to mellanox versioning. Rolls back to older version with `pip` for now.
=> Roll back ci-testing for daillies

composer/loggers/mlflow_logger.py
Removes step in key. Mirrors https://github.com/mosaicml/composer/pull/3587 with passing CI/CD
=> Remove step in log_image for MLFlow

composer/loggers/mlflow_logger.py
Reduce system metrics logging frequency to every 30s.
=> Reduce system metrics logging frequency

composer/trainer/_patch_pytorch.py
Fix the torch 2.4.1 2-gpu tests. It missed a auto-microbatch torch patch.
=> fix 2.4.1 test

composer/loggers/mlflow_logger.py
Makes it able to pass MLFlowLogger to a child process with `export PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True"`
Addresses the error:
```
RuntimeError: Tensors allocated with expandable_segments:True cannot be shared between processes. Consider using expandable_segments:False in data loading workers via torch.cuda.memory._set_allocator_settings('expandable_segments:False')
```
Run with fix: test-hf-checkpoint-fix-Vknjzg
Run without fix: test-hf-checkpoint-baseline-5ZGdqG
=> Remove tensor option for _global_exception_occured

composer/utils/checkpoint.py, tests/trainer/test_checkpoint.py
Likely with pytorch 2.4, the keys in the state dict include lots of things, and they end up in the planner.
This means that the keys that include the string "rng" in a checkpoint can be like this
```
['state.integrations.huggingface.tokenizer.tokenizer.json.content.model.vocab.Ġrng',
'state.integrations.huggingface.tokenizer.tokenizer.json.content.model.vocab._rng',
'state.integrations.huggingface.tokenizer.tokenizer.json.content.model.vocab.rng',
'state.integrations.huggingface.tokenizer.tokenizer.json.content.model.vocab.(rng',
'rng.0.python',
'rng.0.numpy',
'rng.0.torch',
'rng.0.cuda',
'rng.1.python',
'rng.1.numpy',
'rng.1.torch',
'rng.1.cuda',
'rng.2.python',
'rng.2.numpy',
'rng.2.torch',
'rng.2.cuda',
'rng.3.python',
'rng.3.numpy',
'rng.3.torch',
'rng.3.cuda',
'rng.4.python', …
```
=> Fix RNG key checking

composer/loggers/mlflow_logger.py, tests/callbacks/callback_settings.py
Fix CPU dailies. Runs wandb in offline mode
=> Fix CPU dailies

composer/trainer/_patch_pytorch.py, composer/utils/checkpoint.py
daily test is broken: https://github.com/mosaicml/composer/actions/runs/10969280313/job/30461744791
We thought 2.4.1 included the checkpointing backward compatibility fix, but it turned out not. So we add the patch to 2.4.1 in this PR. 
daily test: https://github.com/mosaicml/composer/actions/runs/11000779231
=> fix 2.4.1ckpt

composer/_version.py, docker/Dockerfile, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps Composer version in preparation for 0.25.0 release.
=> Bump version 25

tests/trainer/test_fsdp_checkpoint.py
As title
Daily test run: https://github.com/mosaicml/composer/actions/runs/11024942307
=> Add backward compatibility checkpoint tests for v0.25.0

composer/core/state.py, tests/trainer/test_tp.py
Disables tensor parallelism when the `tensor_parallelism_degree` is 1. 
This is a cleaner version of #3437 that passes all the tests.
=> Don't use TP when `tensor_parallel_degree` is 1

composer/utils/object_store/uc_object_store.py
Surfaces the Databricks PermissionDenied error instead of wrapping it in ObjectStoreTransientError
=> Surface UC permission error

composer/utils/reproducibility.py, tests/callbacks/callback_settings.py
Switch to `log.info` as this isn't something going wrong that requires user intervention. If a user intentionally sets this, it should not result in a warning.
Most frequently, this results in spurious warnings in our Ci/CD
=> Switch to log.info for deterministic mode

composer/callbacks/__init__.py, composer/callbacks/load_checkpoint.py, pyproject.toml, tests/callbacks/callback_settings.py, tests/callbacks/test_callbacks.py, tests/callbacks/test_load_checkpoint.py, tests/callbacks/test_loggers_across_callbacks.py, tests/fixtures/fixtures.py, tests/loggers/test_mosaicml_logger.py, tests/loggers/test_wandb_logger.py, tests/models/test_hf_model.py
Adds a new callback to load a checkpoint at a specified event. This enables use cases like loading model base weights with peft.
Ran two lora finetuning runs.
`test-load-checkpoint-callback-baseline-K0m4fq`: Initialized from Huggingface checkpoint and ran for 100 batches
`test-load-checkpoint-callback-resume-GS8oWj`: Initialized using this callback and the baseline checkpoint at ba50.
We see that the losses match up.
Also confirmed that the adapter-only checkpoint is smaller than a full checkpoint as expected.
=> Create callback to load checkpoint

composer/utils/checkpoint.py, tests/trainer/test_checkpoint.py
Previously, all rank's 1 - N would return a File not Found Error when local rank 0 failed to download the monolithic checkpoint resulting in a confusing debugging experience. 
This new logic changes the exception on non global rank 0's to raise an Error that points users to look at the local rank 0 for better debugging experience.
https://databricks.atlassian.net/browse/GRT-3308
`EXTRA_ARGS='-vv -k test_load_incorrect_path' WORLD_SIZE=2  make test-dist-gpu`
=> Add better error handling for non-rank 0 during Monolithic Checkpoint Loading 

composer/loggers/mlflow_logger.py
The [previous PR](https://github.com/mosaicml/composer/pull/3449) that added exception hook handling to mlflow just blindly overwrites the existing excepthook. This PR changes that to _use_ the existing excepthook and just _add_ what the mlflow logger needs.
Before: `llama-7b-commits-6-D3ipHw` (exception is not rich formatted, because systemwide excepthook is not triggered)
After: `llama-7b-commits-11-3KdS8L` (exception is rich formatted, because systemwide excepthook is triggered)
Note: this is the same as https://github.com/mosaicml/composer/pull/3672, but off a branch instead of a fork.
=> Don't overwrite sys.excepthook in mlflow logger

composer/core/data_spec.py, composer/trainer/trainer.py, tests/test_simple_nlp.py, tests/trainer/test_dataspec.py
This PR allows differentiation between loss generating tokens and total tokens, by allowing `get_num_tokens_in_batch` to return a dict with `total` and `loss_generating` keys. This will only have an impact if you are using the `accumulate_batch_on_tokens` flag. This does not break or change any existing functionality, as by default, if you are just returning a single number from `get_num_tokens_in_batch`, we will accumulate using that value. Things will only change if the user adjusts their `get_num_tokens_in_batch` to be a dictionary.
Related PR in LLM Foundry: https://github.com/mosaicml/llm-foundry/pull/1610
Manual testing (using Foundry draft PR):
Before with all tokens loss generating, microbatching is deterministic:
Before with not all tokens loss generating, microbatching is not …
=> Loss gen tokens

composer/utils/file_helpers.py
Refactors `maybe_create_object_store_from_uri` to use a dictionary, which maps backend strings to object store factory functions.
=> Refactor `maybe_create_object_store_from_uri`

composer/trainer/trainer.py
Allow microbatches to have 0 loss generating tokens
=> Don't error if some batch slice has no loss generating tokens

composer/_version.py, composer/trainer/trainer.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py, tests/trainer/test_fsdp.py, tests/utils/test_autolog_hparams.py
Bump version to 0.27.0.dev0.
Removes `fsdp_config` and `fsdp_auto_wrap` `Trainer` parameters.
=> Bump version to 0.27.0.dev0

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Context: MLflow has receiving lots of data... so we want to save some budget.
In this PR, if we detect that a metric has the same value as the previous step, we don't log it unless it meets one of the following 2 criteria:
- There has been `log_duplicated_metric_every_n_steps` skipped since last step logging, default to 100.
- There has been `log_duplicated_metric_every_n_millis` passed since last step logging, default to 600000 (10 minutes).
We put this exception for sampling purpose, otherwise it will be challenging to capture the duplicated values during sampling, despite the duplicated value occupies a significant portion of the metric history.
Tested with LLM foundry quickstart, and 3 setup: 1) no dedupping 2) log duplicated steps per 2 steps 3) log duplicated steps per 10 steps. No …
=> Metrics dedup for MLflow logger

setup.py
Lower min torchmetrics version. https://github.com/mosaicml/composer/pull/3460/ raised it and we instead intend to stay no >1.0
=> Lower min torchmetrics version

composer/utils/object_store/mlflow_object_store.py
Throw permission error if swallowed in mlflow exception stacktrace.
=> Private link error handling

composer/utils/checkpoint.py
Pytorch fixed this in 2.5 so the patch is no longer needed
https://github.com/mosaicml/composer/actions/runs/11666678682
=> Pin checkpoint state dict flattening patch

composer/core/data_spec.py, composer/trainer/trainer.py, tests/trainer/test_trainer.py
https://github.com/mosaicml/composer/pull/3566 moved device transfers into the microbatch loop. This results in device transformations occurring on CPU, which can be slow as pointed out in https://github.com/mosaicml/composer/issues/3699.
To remedy this, we deprecate `device_transforms` (which was poorly named anyways) and instead add `batch_transforms` and `microbatch_transforms` to dataspec. Batch transforms happens on CPU, and microbatch transforms happens on GPU after the device transfer.
Additionally, if users want to do batch level transforms on GPU, they can add a transform that moves to device.
=> Add batch/microbatch transforms

.github/workflows/code-quality.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/release.yaml, .github/workflows/smoketest.yaml, .readthedocs.yaml
Bumps all images in composer to now use 22.04, follow up for https://github.com/mosaicml/composer/pull/3716
https://databricks.atlassian.net/jira/software/c/projects/GRT/boards/4746?selectedIssue=GRT-3195
=> Bump mosaicml/pytorch images to use new mosaicml/pytorch images with updated ubuntu 22.04

composer/utils/dist.py
This way, it becomes easier to randomly vary the order of the data.
Exposes the `DistributedSampler`'s `seed` argument in the `get_sampler` utility function. Since the default value is already `seed=0`, https://github.com/mosaicml/composer/issues/3723. 
Fixes #3723
@mvpatel2000
=> Expose `DistributedSampler` RNG seed argument

tests/trainer/test_fsdp_checkpoint.py
As title. Adds for 0.27.0 as well since this was not done upon release.
Daily tests passed: https://github.com/mosaicml/composer/actions/runs/12184347841
=> Add checkpoint BC tests for 0.27.0 and 0.28.0

.github/workflows/coverage.yaml, .github/workflows/pr-cpu.yaml, setup.py, tests/loggers/test_mlflow_logger.py
Fix MLFlow logger CI error by ignoring UserWarning
=> Fix MLFlow logger CI error by ignoring UserWarning

docs/source/trainer/using_the_trainer.rst
Fixes `loss(batch, outputs)` to `loss(outputs, batch)` at one point in `docs/source/trainer/using_the_trainer.rst`.
=> Fix order of arguments to `loss`

composer/profiler/json_trace_handler.py
This PR makes the profiler's trace merging behavior robust to the trace destination path being on a different mount to the system's tmpdir. 
Currently the `os.rename` is not robust to this and you get an "Invalid cross-device link" error. For example:
```
[rank16]: OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpk3h5r9q9' -> '/profiling/composer_profiler/merged_trace.json'
```
https://docs.python.org/3/library/shutil.html#shutil.move does exactly what we want here: status quo behavior if tmpdir and dest are on the same filesystem; if not, does a copy. 
This is not related to an existing issue. I checked. I'm going straight to opening a fix 🙂. 
- **No, but** it's a trivial fix.
- **No, but** this diff does not require it.
-  **No, but** `make test EXTRA_ARGS='-k …
=> fix: make JSONTraceHandler.batch_end robust to /tmp/ being on diff mount to dest

docker/Dockerfile, setup.py
Updates the docker image to have FA==2.7.1.post1 in sync with this [pr](https://github.com/mosaicml/llm-foundry/pull/1728)
testing:
torch 2.6 fa 2.7.1.post1:
torch 2.5 fa 2.7.1.post1:
torch 2.4 fa 2.7.1.post1:
cpu (fa should not install):
=> Update docker to have FA==2.7.4.post1

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Remove legacy save_model support for mlflow peft mode and associated unit test
NA
Ran `make test` inside image `mosaicml/composer:latest_cpu` however got one CUDA failure though it should be purely cpu test and git regression passed? `ERROR tests/algorithms/test_gradient_clipping.py - UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)`
=> [GRT-3415] Remove dead code for peft logging

setup.py, tests/callbacks/callback_settings.py, tests/callbacks/test_callbacks.py
Aiming to patch https://github.com/mosaicml/composer/actions/runs/13708442344, seems like Mlflow is trying to access its trash directory but is having permission issues or the directory structure doesn't exist. We have to mock this call.
=> Patch Mflow .trash directories

composer/core/precision.py
Enables Transformer Engine's FusedAttention optimization on AMD hardware by removing an unnecessary TE ONNX export context from FP8 precision handling, improving performance with AMD's Composable Kernel backend.
This PR removes the TE ONNX export tracing from the FP8 precision context that was added in [commit 2c6a390](https://github.com/mosaicml/composer/commit/2c6a39052dbeca8db270a5e7f070c35e52455a91) to address [checkpoint resumption issues with FP8 in PyTorch 2.1](https://github.com/mosaicml/composer/pull/2907). The workaround is no longer needed with PyTorch 2.3+, and the minimum supported version is torch 2.4.0 currently.
The ONNX export context forces AMD's Composable Kernel backend to disable its optimized FusedAttention implementation, falling back to the slower …
=> Remove TE ONNX Export Context to Enable TE FusedAttention on AMD Hardware

Makefile
With this change, we no longer need to explicitly set the WORLD_SIZE when running `make test` on machines with >1 GPUs
=> Update Makefile to use WORLD_SIZE

.github/workflows/release.yaml
This bumps ci-testing ref in `release` to be what is used in `code-quality` so that code quality passes
https://github.com/mosaicml/composer/actions/runs/14253613586
Running Release Workflow on this branch no longer fails on `code-quality`
https://github.com/mosaicml/composer/actions/runs/14254749363/job/39955231384
=> Bump Release Ref 0.3.3

.github/workflows/release-docker.yaml
3.10 is parsed as 3.1 if not explicitly set as string
N/A
=> Fix release docker with 3.10

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
This PR adds an entry in the container build matrix to also build a pytorch2.6+cu126 variant on top of whatever is already being built.
=> Extend docker build matrix to add an entry for pytorch2.6+cu126

docker/Dockerfile, setup.py
wheel released a new version, that no longer has bdist_wheel in it (https://github.com/pypa/wheel/releases/tag/0.46.0), relying on the fact that is now in setuptools, but we pin an old setuptools.
This PR updates setuptools to use the latest version, 78.1.0, in our docker image.
`composer-mpt-125m-chinchilla-kFetCc`
Run is working with the new docker image
=> Update setuptools version

composer/distributed/fsdp2.py, tests/trainer/test_fsdp2.py, tests/trainer/test_fsdp2_gradscaler.py
PR to update optimizer params to point to dtensors instead of regular model tensors. This should work fine for checkpointing as well since we fully shard before updating the optimizer's state (which is referenced in `update_optimizer_modules`)
=> Update optimizer params for fsdp2

tests/loggers/test_mlflow_logger.py
Latest mlflow release results in a UserWarning from this test, which causes a test failure so we ignore it in the test.
=> Ignore mlflow warning in test

composer/cli/launcher.py, composer/core/state.py, composer/trainer/_scaler.py, composer/trainer/trainer.py, composer/utils/checkpoint.py
Remove dead code which is only effective before torch 2.4, which we don't support anymore.
1. Pave the way to support and release torch 2.7 and deprecate torch 2.4/2.5
2. Test Cursor on trivial SDE task
Most changes are created by Cursor, yet reviewed by myself. Workflow:
Codebase wise one shot change is still hard for Cursor, so current flow is:
```
1. Use agent mode in Cursor
2. Use Claude 3.7 non-thinking
3. 
For file in target_files:
prompt("currently we support torch versions between 2.4 and 2.6, can you help me apply necessary changes to remove or clean up code related to torch version less than 2.4 in this @file? Please don't modify other comments or docstrings. When you need to delete a function please consider if it is used by other files in @composer as well.")
```
=> Eliminate dead code before torch version 2.4  

composer/distributed/activation_checkpointing.py, composer/distributed/fsdp2.py, composer/distributed/prepare_distributed.py, composer/utils/parallelism.py, tests/common/__init__.py, tests/common/models.py, tests/trainer/fsdp2_context.py, tests/trainer/test_activation_checkpointing.py, tests/trainer/test_fsdp2.py
Adding activation checkpointing and activation cpu offloading using the same method as TorchTitan in their examples (which aligns with our previous approach using `checkpoint_wrapper`)
Added tests to check if checkpointing and cpu offloading is working as expected.
=> Activation Checkpointing and Offloading for FSDP2

composer/distributed/fsdp2.py, composer/distributed/prepare_distributed.py, composer/utils/parallelism.py
Support logging of FSDP2 execution time, wrapped model and verbose config
Tested manually, see: mpt-7b-fsdp2-G2eJiP
=> FSDP2 time and verbose logging

.github/workflows/pr-docker.yaml, .github/workflows/release-docker.yaml
Previous PR to upgrade EFA installer version switched which ARG we use to determine whether to install EFA, but this was not propagated to the build args in the github actions, so all images were built with EFA, which causes issues for RDMA on non AWS clusters.
Current image (broken): `rdma-broken-1-pWWCyG`
New image from this PR (fixed): `rdma-fixed-1-ecrVG0`
For the broken run, you can see a bunch of warnings in the logs
```
libibverbs: Warning: couldn't load driver 'librxe-rdmav34.so': librxe-rdmav34.so: cannot open shared object file: No such file or directory
libibverbs: Warning: couldn't load driver 'libbnxt_re-rdmav34.so': libbnxt_re-rdmav34.so: cannot open shared object file: No such file or directory
libibverbs: Warning: couldn't load driver 'liberdma-rdmav34.so': …
```
=> Fix RDMA installation

composer/utils/reproducibility.py, tests/fixtures/fixtures.py, tests/test_notebooks.py, tests/trainer/test_checkpoint.py, tests/trainer/test_fsdp_checkpoint.py
Essentially, all usages of `s3_bucket` has been removed outside of `test_object_store.py` and `test_s3_object_store.py` since we have the ephemeral and read_only paths in UC Volumes now.
=> Removed most s3 bucket based tests (replaced with UC Volumes)

composer/distributed/fsdp2.py, composer/distributed/prepare_distributed.py, composer/distributed/shared_utils.py, composer/utils/parallelism.py, tests/common/models.py, tests/trainer/test_fsdp2.py, tests/trainer/test_fsdp2_config.py
Supporting mixed init on FSDP2.
=> Supporting Mixed Init on FSDP2

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Moves the mlflow logger metrics cache to not keep CUDA tensors around since it doesn't need to. In particular, this allows the logger to be sent to a subprocess, which previously was an issue on some systems when expandable_segments was set to True.
Before (model registration fails): `ipc-register-before-1-ilQ0bO`
After (model registration succeeds): `ipc-register-after-1-WSlNIv`
Metrics and throughput are the same, in case somehow they were affected:
=> Mlflow move to cpu

composer/callbacks/activation_monitor.py, composer/callbacks/mlperf.py
Description:  
This pull request corrects minor typographical errors in comments within two files:
- composer/callbacks/activation_monitor.py: Fixes the spelling of "Because" in a comment explaining the need to prevent infinite recursion.
- composer/callbacks/mlperf.py: Fixes the spelling of "requires" in a comment about setup requirements for rank access.
No functional code changes are included; only comment text has been updated for clarity and correctness.
=> Fix Typos in Comments for activation_monitor.py and mlperf.py

composer/core/state.py, composer/distributed/fsdp2.py, composer/distributed/prepare_distributed.py, composer/utils/parallelism.py, tests/trainer/test_fsdp2.py
Added mixed precision for FSDP2. It is a bit hard to test the `reduce_dtype` so I added a workaround for that test, but the regular `param_dtype` validation is as expected.
=> Mixed Precision for FSDP2

composer/callbacks/speed_monitor.py
As title. Assumes SXM because I didn't see an easy way to differentiate between SXM and PCIe variants - it is no longer specified in the device name. afaict we would have to check bandwidth, power limits, bus ids, or something like that. I also don't have an H200 PCIe to check against.
Tested manually what device name is returned.
=> Add h200 to flops dict

composer/trainer/trainer.py, composer/utils/parallelism.py, tests/trainer/test_fsdp2_config.py
If `init_device=mixed` in `llm-foundry`, `fsdp_config` automatically sets `sync_module_states` to `True`, but it also sets `load_monolith_rank0_only` to `True` as well even if we're not loading a model with `load_path`. In situations like this, it is fine if we have `state_dict_type=sharded` with a `save_folder` since we 1) aren't loading a model at all and 2) saving the model in a sharded checkpoint. This is at odds with our current implementation so to support that code path, we are removing the assertion here that requires `state_dict_type` to equal `full` when `load_monolith_rank0_only=True`
=> updated fsdp2 config

composer/distributed/prepare_distributed.py, tests/trainer/test_fsdp2.py
FSDP2 mixed init requires the full state dict and peft models, when `should_save_peft_only: true` has an updated `state_dict` function that only returns the lora modules instead of the full modules. Therefore, when we encounter this, we use a context manager to switch the variable to get the full state dict.
Ran a full test on `dpo-rl-fsdp2-ESou5r`.
=> Supporting peft for FSDP2

composer/distributed/shared_utils.py, composer/trainer/trainer.py
We removed usage of `fsdp_config.load_monolith_rank0_only` since that is unreliable as llm-foundry can just set the value for that to `True` for no reason...
=> Removed extraneous usage of `fsdp_config.load_monolith_rank0_only` since that's unreliable

setup.py, tests/loggers/test_mlflow_logger.py
This PR reverts mlflow to not use version 3+ as it would have slowdowns for certain model training cases
This was tested via various different runs, showing that with mlflow 3, certain model training would be 90% slower.
=> reverted mlflow upgrade due to slowdowns
