.gitignore, composer/cli/launcher.py
Renamed to `runs` from `.runs`
=> Renamed run directory

composer/loggers/logger_hparams.py, composer/loggers/wandb_logger.py
Added a log_artifacts (default is False) hparam to control whether artifacts are logged to WandB.
=> Add option to disable artifact logging in WandB

composer/trainer/trainer.py
Need to add to `total_loss` before call to `scaler.scale()`.
=> Fix loss reporting

composer/trainer/trainer.py
Batches is not a validation option, we moved to iterations.
=> Update Trainer checkpointing documentation

composer/trainer/checkpoint.py
Resolves #149 .
The issue was that checkpointing stored `state.state_dict()` before checking if the process was Rank 0. Certain loggers (such as WandB) are only stored on Rank 0 processes, so it would cause a crash on other ranks since the loggers don't exist.
I have verified this works.
Some points of discussion:
=> Address crashes with DDP + Checkpointing

docker/pytorch/Dockerfile
Installed and configured sudo in the docker image. Makes it possible to install apt packages in the container that are not included in the image.
=> Sudo in the dockerimage

composer/models/resnet101/resnet101.yaml, composer/models/resnet101/resnet101_synthetic.yaml, composer/models/resnet18/resnet18.yaml, composer/models/resnet18/resnet18_synthetic.yaml, composer/models/resnet50/resnet50.yaml, composer/models/resnet50/resnet50_synthetic.yaml, composer/models/resnet56_cifar10/resnet56_cifar10.yaml, composer/models/resnet56_cifar10/resnet56_cifar10_synthetic.yaml
All model yaml files are in composer/yamls/models.
Closes #34
=> Remove broken symlinks

composer/trainer/deepspeed.py, tests/callbacks/test_memory_monitor.py, tests/test_amp.py, tests/trainer/test_ddp.py, tests/trainer/test_trainer.py, tests/utils/trainer_fit.py
Fixed the broken GPU tests
Manually ran on cota (2x 3090)
=> Fix broken gpu tests

.github/workflows/pr-gate-cpu.yaml, tests/test_pillow_simd.py, tests/trainer/test_checkpoint.py
* Added checkpointing tests for resnet50 and gpt2 
* Added test to ensure that pillow-simd is installed
=> Additional Tests

composer/trainer/checkpoint.py, composer/trainer/trainer.py
=> Adding checkpointing at the end of training

composer/datasets/lm_datasets.py
BERT broke the GPT-2 models, because the GPT-2 tokenizer doesn't have a padding token. We need to conditionally branch on this to determine which data collator to use.
=> Adding conditional branching on data_collator

composer/datasets/ade20k.py
I made a mistake with calculating the padding fill during the final DeepLabV3 refactor. This should be the correct calculation.
=> Fix ade20k padding fill calculation

composer/utils/_time_conversion.py
The time abstraction broke learning rates for BERT, this adds a fix
=> Adding fix for NLP learning rates

.ci/Jenkinsfile
Fix jenkins to work on PRs from forks
=> Fix Jenkins to work on PRs from Forks

composer/trainer/trainer.py
Fixes something from #223 that was causing SAM to crash.
=> Add kwargs back to the closure

composer/optim/scheduler.py
=> Scheduler defaults to step-wise instead of epoch-wise

composer/trainer/checkpoint.py, composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, examples/run_composer_trainer.py, tests/trainer/test_checkpoint.py
1. Remove config from trainer; fixes #358
2. Add save_compression to trainer_hparams; fixes #355. Fixed checkpointing test.
=> Fix Checkpoints

STYLE_GUIDE.md
=> Quick style guide typo fix

composer/trainer/trainer.py
I believe we need train metrics here, this should be returning val metrics
=> bug in train metrics

composer/__init__.py
=> allow `from composer import ComposerModel`

composer/callbacks/run_directory_uploader.py
This adds some extra exception handling to harden the run directory uploader against network failures
=> Adding network fixes for the Run Directory Uploader

composer/algorithms/seq_length_warmup/seq_length_warmup.py
Removed an offending assert that is not needed for sequence length warmup. Also moved the check for `train_dataloader.batch_size is not None` to the `INIT` event to fail faster.
=> [v0.4rc] Allow for batch sizes not divisible by grad accum in sequence length warmup

composer/algorithms/alibi/alibi.py
=> [v0.4rc] remove unused embeddings from optimizer for Alibi

composer/loggers/tqdm_logger.py
No I'm not writing a test for this
=> [XS] Fix a TQDM deserialization bug

composer/datasets/__init__.py, composer/datasets/ade20k.py, composer/datasets/brats.py, composer/datasets/c4.py, composer/datasets/cifar.py, composer/datasets/coco.py, composer/datasets/dataloader.py, composer/datasets/dataset_registry.py, composer/datasets/imagenet.py, tests/test_dataset_registry.py
For __init__, ade20k, brats, c4, cifar10, coco, dataloader, dataset_registry and imagenet.
=> docstrings improvements for composer.datasets

.github/workflows/codeql-analysis.yml
Didn't realize it was running on dev PRs
Should included this ASAP so we don't eat minutes
=> Less CodeQL

README.md
* updates the algorithms link 
* removes the functional column
=> Additional README fixes

docs/source/functional_api.rst, docs/source/trainer/algorithms.rst
Still working on functional API. Will update this PR when finished.
=> Proofreading for speedup methods section

composer/datasets/ffcv_utils.py, composer/datasets/imagenet.py
These are fixes we need based on full model test + performance 
Distributed flag for ffcv loader and fix the performance issue of ffcv __len__ function. 
~~WIP: Not ready for review yet.~~
=> Fixes for ffcv integration

composer/models/unet/unet_hparams.py
Removes `asdict` in Unet instantiation for quick fix
=> Remove asdict in unet

examples/run_composer_trainer.py
Add a missing f-string to the entrypoint
=> Cherry Pick #906

composer/loggers/logger_destination.py, composer/trainer/trainer.py
You know something's wrong if it's not 42.
=> Log the rank zero seed via the logger

tests/trainer/test_trainer.py
Adding an end-to-end test for ffcv dataloders. 
Writes ffcv datasets from dummy image dataset, create ffcv dataloaders (train and val) and runs trainer. 
Test:
`python   -m pytest -m gpu    --duration all -k "TestFFCVDataloaders"`
=> add e2e test for ffcv

meta.yaml, pyproject.toml
Exclude daily tests from the conda build
=> Exclude daily tests from the conda build

composer/algorithms/colout/colout.py, composer/models/base.py, composer/trainer/trainer.py, tests/algorithms/test_colout.py, tests/models/test_model_access_to_logger.py
- Bind the `Logger` to `ComposerModel`
- Added test case
=> Bind the `Logger` to `ComposerModel`

README.md
We just uploaded a v2 of the paper and the README linked to v1.
=> Updated ALiBi link in README

composer/datasets/imagenet.py
Use resize_size hyperparameter in ffcv val loader.
=> Fix use of resize_size in ffcv val dataloader

composer/algorithms/ema/ema.py, tests/algorithms/test_algorithm_resumption.py
This PR fixes a bug in resuming training with EMA on GPUs, and un-xfails it in the algorithms resumption test.
=> Fix EMA GPU resumption issue

composer/core/state.py
Added docstrings for State attributes that were undocumented.
=> [xs] Fixed missing docstrings on the State

tests/trainer/test_checkpoint.py
Basic refactoring of checkpointing tests. Will add transitioning to functional on backlog, but lowest priority item right now for me.
=> Simplify checkpointing tests

tests/datasets/test_synthetic_lm_data.py
=> closes #996 - `generate_parameter_configs` adding `use_masked_lm` and `drop_last`

composer/core/time.py, tests/test_time.py
Fixes https://github.com/mosaicml/composer/issues/907
=> Raise type error for bad timestrings

docs/source/trainer/using_the_trainer.rst
self-explanatory, it's a tiny PR
=> [XS] Change capitalization on DeepSpeed

docs/source/getting_started/notebooks.rst, notebooks/composer_with_ffcv_dataloaders.ipynb
=> Notebook for using ffcv dataloaders with composer

composer/__init__.py, composer/utils/collect_env.py, meta.yaml, setup.py
Upgrade version of Composer to 0.7.0
=> Bump version to 0.7.0

composer/optim/__init__.py, composer/optim/scheduler.py, composer/optim/scheduler_hparams.py, composer/trainer/trainer_hparams.py, docs/source/method_cards/scale_schedule.md, docs/source/trainer/schedulers.rst, tests/trainer/test_scheduler.py
Adds PolynomialWithWarmupScheduler and PolynomialWithWarmupSchedulerHparams
This decays learning rate multiplier according to a polynomial of given power. A warmup period can be specified. 
Corresponding docs are updated and added a test.
=> Add PolynomialWithWarmupScheduler

composer/models/deeplabv3/README.md, docs/source/index.rst, docs/source/model_cards/deeplabv3.md
=> DeepLabv3+ README

composer/algorithms/layer_freezing/README.md, composer/algorithms/progressive_resizing/README.md
Adds some missing example code snippets to the method cards.
=> Update code examples for progressive resizing and layer freezing

composer/loggers/wandb_logger.py, examples/run_composer_trainer.py
Add in the timestamp attributes as wandb artifact metadata
Example artifact: https://wandb.ai/mosaic-ml/ravi-composer-examples/artifacts/ep2-ba58-rank0/1654289178-tuscan-hummingbird.checkpoints.ep2-ba58-rank0/d72a67bc4f0ea580764c/metadata
=> Add in the timestamp attributes as wandb artifact metadata

composer/utils/libcloud_object_store.py, composer/utils/object_store.py
Abstract class for implementing object_store utilities like Libcloud, s3, sftp.
=> Abstract Object Store Class

composer/datasets/__init__.py, composer/datasets/cifar.py, composer/datasets/cifar_hparams.py, composer/datasets/dataset_hparams_registry.py, composer/datasets/imagenet.py, composer/datasets/streaming/__init__.py, composer/datasets/streaming/dataset.py, composer/yamls/models/resnet56_streaming_cifar10.yaml, scripts/ffcv/create_ffcv_datasets.py, scripts/mds/cifar10.py, tests/datasets/test_dataset_registry.py, tests/datasets/test_streaming_remote.py
Add an implementation of the classic `CIFAR10` dataset using the MosaicML `StreamingDataset`.
=> (a) StreamingCIFAR10, (b) remove StreamingImageClassDataset.

.pre-commit-config.yaml, composer/optim/decoupled_weight_decay.py, examples/custom_speedup_methods.ipynb, examples/ffcv_dataloaders.ipynb, examples/functional_api.ipynb, examples/getting_started.ipynb, examples/huggingface_models.ipynb, examples/medical_image_segmentation.ipynb, examples/migrate_from_ptl.ipynb, examples/nlp_models.ipynb, tests/test_notebooks.py
Fix some of the notebook tests that were failing as part of the daily test runs
1. Fix notebooks to run on both cpu and gpu
2. Fix monkeypatching of the trainer when running tests to do only 1 epoch, and 1 batch per epoch
5. Fix any errors in the tests
3. Stripping all metadata from the notebooks
4. Using `%pip` rather than `!pip` for better portability
=> Notebook cleanup

examples/getting_started.ipynb
Stores training data in InMemoryLogger instances and plots the results to compare speed updates
=> Adding InMemoryLogger to the Getting Started Notebook

.ci/Jenkinsfile, composer/datasets/c4.py, composer/datasets/streaming/download.py, meta.yaml, setup.py
Add simple SFTP support via the `StreamingDataset`'s download handlers.
=> SFTP handler for Streaming Datasets

composer/datasets/imagenet_hparams.py
with `ffcv_cpu_only` option for imagenet dataset, one can force all ffcv transformations to run only on cpu. 
@florescl requested for AMD GPUs. BTW @florescl only problematic part is the use of cupy in [NormalizeImage](https://github.com/libffcv/ffcv/blob/main/ffcv/transforms/normalize.py#L61) transform. If you install a [ROCm supported version of cupy](https://docs.cupy.dev/en/v8.6.0/install_rocm.html#building-cupy-for-rocm) in your environment, this change is not needed. Also I think cpu-only version of NormalizeImage relies on compiler for vectorization and may be slow if vectorization doesn't happen.
=> Add an option to run all ffcv transformations only on cpu

composer/utils/fx_utils.py, tests/utils/test_fx_utils.py
This is an initial implementation of graph transformation related utilities using FX. Currently it includes the following functions and tests for them. 
- ~~trace_with_fx~~
- count_op_instances
- replace_op
Part 2 will implement the following functions:
-  replace_pattern
- fuse_parallel_linears
Part 3 will have a way to automatically detect residual blocks and automatically insert stochastic counterpart. 
-  detect_residual_pattern
- replace_residual_with_stochastic
=> [Part 1] Initial commit for FX-related graph transformation utils

composer/algorithms/gradient_clipping/gradient_clipping.py, composer/core/state.py, composer/trainer/trainer.py, tests/algorithms/test_gradient_clipping.py
* clean up checking for existing gradient clipping
* deepspeed config passed to State constructor
* add doctring to `deepspeed_enabled`
=> Gradient Clipping Part 2: A Little Cleanup

README.md
Updates the README numbers with the latest science 🚀 
Blocked by @nqn updating the figure as well 🙏
=> Update README numbers

STYLE_GUIDE.md
* Unifies internal and repo docs
* Fix section numbering
=> Update STYLE_GUIDE with details on Documentation

docs/source/notes/auto_grad_accum.rst
Adds warning about using auto GA with models that have batch norm layers
=> Add caveats about automatic gradient accumulation

composer/models/deeplabv3/deeplabv3_hparams.py
@A-Jacobson you had too much faith in me
=> Hotfix deeplabv3

composer/utils/__init__.py
Adds S3ObjectStore import to util __init__.py so that S3ObjectStore closure is constant with LibCloudObjectStore
=> Adds S3ObjectStore import to util __init__.py 

composer/utils/object_store/s3_object_store.py
The previous PR (#1278) didn't actually solve the prefix problem, it only made the URI correct. Surprisingly, it still passed all `test_object_store` tests... because both upload/download were using the non-prefixed paths. StreamingDataset also passed because it does not use the `prefix` at all.
This PR should fix the situation and I've tested E2E with a run that checkpoints to S3 with prefix.
=> Fix S3 prefix upload/download

composer/loggers/progress_bar_logger.py
Patch to the previous PR on backwards compatibilty. Verified that it works by @jzf2101
=> Actual fix to backwards compatibility

examples/getting_started.ipynb
There seem to be several bugs in `getting_started.ipynb`. Most of them are due to changes in keywords.
=> Bugs in getting_started.ipynb

composer/trainer/trainer.py, composer/utils/dist.py
Resolves this [jira](https://mosaicml.atlassian.net/jira/software/c/projects/CO/boards/12?modal=detail&selectedIssue=CO-676&assignee=61fc1878aab3620070f699bf), which means users now get an error and a helpful message if a deadlock is encountered with auto grad accum
=> Add monitored barrier for autograd accum

.pre-commit-config.yaml, examples/checkpoint_autoresume.ipynb, examples/migrate_from_ptl.ipynb, examples/nlp_models.ipynb, tests/algorithms/algorithm_settings.py
1. Fix the formatting in the Migrating from PTL notebook, where bullets were not showing up on their own lines, and imports were missing.
2. Fix the Checkpoint Autoresume notebook to use the `%pip` magic, and place the install command before the title.
Closes https://mosaicml.atlassian.net/browse/CO-659
=> [xs] Notebook Fixes

composer/__init__.py, composer/_version.py, composer/utils/collect_env.py, examples/run_composer_trainer.py, meta.yaml, setup.py
This PR places the composer version number in just one place -- `composer._version`.
Closes https://mosaicml.atlassian.net/browse/CO-556
=> [xs] Store the Composer version in one place.

composer/callbacks/checkpoint_saver.py, composer/core/state.py, composer/trainer/trainer.py, composer/utils/__init__.py, composer/utils/checkpoint.py, composer/utils/inference.py, composer/utils/misc.py, tests/common/state.py, tests/trainer/test_trainer.py, tests/utils/test_inference.py
Functional version of model export for inference API
~~Todo: loading from checkpoint part.~~ Done
=> model export for inference. Functional API

.ci/Jenkinsfile, .ci/test.sh, tests/conftest.py, tests/datasets/test_streaming_remote.py, tests/utils/object_store/test_s3_object_store.py
Run integration tests (those marked with `@pytest.mark.remote` on each PR)
Closes https://mosaicml.atlassian.net/browse/CO-627
=> Integration Testing

composer/trainer/trainer.py, composer/trainer/trainer_hparams.py, composer/utils/dist.py, tests/fixtures/new_fixtures.py
Disable monitored barrier when gloo fails to initialize
=> Revert monitored barrier

composer/utils/inference.py, tests/utils/test_inference.py
=> [Minor] Inference API parameter name change

composer/utils/dist.py
Looks like its not initializing on all ranks with multinode...
=> revert gloo

composer/trainer/trainer.py
Resolves [JIRA](https://mosaicml.atlassian.net/browse/CO-799), raising auto grad accum warning level.
=> Auto Grad Accum Change to Warning

composer/trainer/trainer.py, tests/test_precision.py
As title. Was causing problems with methods which require certain precisions.
=> Add Precision Contexts

composer/algorithms/gated_linear_units/gated_linear_units.py
The GLU logging string mentions FusedLayerNorm instead of GLU 🙈
=> Update GLU logging strings

composer/callbacks/checkpoint_saver.py, composer/trainer/trainer.py, tests/trainer/test_checkpoint.py
Changes default name to have `.pt`.  Fixes CO-850.
=> add filename extension

composer/core/types.py, composer/trainer/trainer.py
As title. Diff is large, but I just removed the exception and unindented. We can add this back if we want to use it, but I'm pro simplifying code and not leaving in dead snippets. Fixes CO-864
=> Clean up unused exception

composer/core/types.py, composer/trainer/trainer.py
Reverts mosaicml/composer#1368
Reverting the PR due to comments on it -- didn't realize that automerge was enabled.
=> Revert "Clean up unused exception"

composer/core/types.py, composer/trainer/trainer.py
Reopening since the last got automerged. As title. Diff is large, but I just removed the exception and unindented. We can add this back if we want to use it, but I'm pro simplifying code and not leaving in dead snippets. Fixes CO-864
From last PR:
> Hmm I believe we needed this for the Benchmarker code to work, cc: @abhi-mosaic ? Is that still used for data collection?
=> Remove Unused Exception

composer/core/types.py, composer/trainer/trainer.py
Reverts https://github.com/mosaicml/composer/pull/1379 which won't autorevert.
Turns out I found a use for it in agent
=> Add break epoch exception

composer/trainer/trainer.py
Use state algos, so engine changes to algos can adjust these variables as needed. Needed for agent
=> Use state algos

CODEOWNERS, examples/custom_speedup_methods.ipynb
* Minimize single approver bottlenecks
* Reduce PR noise
=> Relax codeowners 

composer/datasets/glue_hparams.py, composer/datasets/lm_dataset_hparams.py, setup.py
Fixes [CO-883](https://mosaicml.atlassian.net/browse/CO-883) using a `type: ignore` as suggested by @hanlint.
=> Fix pre-commit checks failing on fresh checkout of dev

composer/algorithms/gated_linear_units/gated_linear_units.py, composer/trainer/trainer.py
Fixes attribute error. Quick stamp, should be same change as in performance. Throwing on a comment change for the ride
=> Fix attribute

docker/Dockerfile
Not intended for merge, just using this to build a Docker container using Jenkins, had a lot of trouble doing so on my laptop.
=> Docker image with Flash Attention

composer/models/huggingface.py
tell me if I need to add any tests for this. Closes #1492
=> update model token embeddings according to tokenizer len

composer/models/bert/model.py
This simply adds some logic to `composer.models.create_bert_classifier` to reflect that `num_labels=1` is a regression case and requires different metrics. As part of this change, regression models use MSE and SpearmanCorrCoef, whereas classification models (when `num_labels > 1`) use Accuracy, MatthewsCorrCoef, and (if appropriate) BinaryF1Score.
The docstring is updated with a note to explain this.
Closes CO-1007.
=> BERT classifier metrics depend on num_labels

.gitignore
Unsure how `datasets/` got into `gitignore`...
=> remove datasets from gitignore

composer/yamls/models/bert-base.yaml, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml, composer/yamls/models/resnet50_streaming.yaml, composer/yamls/models/resnet56_streaming_cifar10.yaml
- Removed streaming version 2 from yaml since version 1 is default
=> Removed streaming version 2 from yaml since version 1 is default

composer/utils/dist.py, tests/utils/test_dist.py
Context now raises error if dist is not initialized instead of silently being skipped. Resolves https://mosaicml.atlassian.net/browse/CO-1107
=> Update context to raise errror

composer/metrics/metrics.py
@mvpatel2000 Could you try this branch out with DeepLabV3 and let me know if it fixes the issue you were seeing?
=> Fix MIoU metric when `self.total_union==0`

tests/callbacks/test_image_visualizer.py, tests/fixtures/new_fixtures.py
Unxfails an `ImageVisualizer` test and adds a test to make sure that `ImageVisualizer` + W&B doesn't cause problems.
Fixes CO-1181
Tests for the fix to the bug in CO-1169
=> Image viz test

docs/source/functional_api.rst, docs/source/trainer/algorithms.rst
Fixes incorrect calls to randaugment functional API
=> Fixes RandAugment API

composer/datasets/enwiki_hparams.py
https://github.com/mosaicml/streaming/pull/28 created a new version of enwiki dataset. These changes are needed to make hparams class work with new enwiki.
=> Fixes enwiki for the newly processed wiki dataset

CONTRIBUTING.md
Changes install recommendation to all.
N/A -- pyright doesn't work with dev
=> Change install to all

.github/workflows/codeql-analysis.yml
- Upgrade CodeQL Action to version 2 since the version 1 will be going to deprecated in Dec 2022. Reference [link](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/).
- Update the cron job schedule to run at the start of the week to have more time to fix the security issues if any rather than running late in the week.
- Version Upgrade
=> Upgrade CodeQL Action to version 2

composer/datasets/ade20k_hparams.py, composer/datasets/c4_hparams.py, composer/datasets/cifar_hparams.py, composer/datasets/coco_hparams.py, composer/datasets/imagenet_hparams.py, composer/yamls/models/bert-base.yaml, composer/yamls/models/deeplabv3_streaming_ade20k_optimized.yaml, composer/yamls/models/resnet50_streaming.yaml, composer/yamls/models/resnet56_streaming_cifar10.yaml, setup.py
- Defaulting streaming dataset version to 2
Fixes: CO-1244
=> Defaulting streaming dataset version to 2

composer/cli/launcher.py
Removes an unused import introduced by #1629
=> Remove unused import

composer/core/callback.py, composer/core/engine.py, composer/core/event.py, composer/trainer/trainer.py, docs/source/getting_started/welcome_tour.rst, docs/source/trainer/algorithms.rst
Adds a new event. This is required for weight-preserving surgery algorithms.
[CO-1151](https://mosaicml.atlassian.net/browse/CO-1151)
=> Add Event.AFTER_LOAD

composer/callbacks/memory_monitor.py, tests/callbacks/test_memory_monitor.py
=> Fix todo in memory monitor

.github/ISSUE_TEMPLATE/---bug-report.md
Adds composer version to the requested environment information in a bug report.
=> Add composer version to issue template

composer/algorithms/alibi/attention_surgery_functions/_gpt2.py, composer/algorithms/gated_linear_units/gated_linear_units.py, composer/datasets/synthetic_lm.py, setup.py
- Update installation constraints for streaming in setup.py
=> Update installation constraints for streaming

composer/core/state.py
Fixes backwards compatibility for checkpoints.
[CO-1350](https://mosaicml.atlassian.net/browse/CO-1350)
=> fix backwards compatability

composer/core/engine.py, tests/test_passes.py
Fixes edge case with types for registering passes
=> Fix engine pass registration

docs/source/notes/distributed_training.rst
Includes information on distributed sampler
[CO-1196](https://mosaicml.atlassian.net/browse/CO-1196)
=> Update distributed docs

composer/devices/__init__.py
=> remove as in device

composer/devices/device.py, composer/devices/device_cpu.py, composer/devices/device_gpu.py, composer/devices/device_tpu.py, composer/utils/device.py, composer/utils/dist.py
=> Fix device imports

.ci/Jenkinsfile, .ci/run_doctests.sh, .ci/test_docs.py, .ci/test_lint_doctests.py, .github/workflows/code-quality.yaml
Adds a GitHub Actions workflow for code quality checks (pre-commit hooks).
Removes these checks from Jenkins pipelines.
Resolve CO-1397.
=> GHA workflow for code quality checks

composer/algorithms/no_op_model/no_op_model.py, composer/core/state.py, tests/trainer/test_checkpoint.py
Fixes backwards compatibility support if algorithm API changes.
[CO-1435](https://mosaicml.atlassian.net/browse/CO-1435)
=> Protect backwards compatability

composer/models/huggingface.py, docs/source/doctest_fixtures.py, tests/common/datasets.py, tests/models/test_hf_model.py
This PR adds support for loading a huggingface model and tokenizer from the information saved in the the composer checkpoint that is added by #1744.
Design here: https://www.notion.so/Autoload-Huggingface-models-for-finetuning-59dda720b7ae4bee90d3594a5ab731d9
Closes: [CO-1109](https://mosaicml.atlassian.net/browse/CO-1109) and [CO-1110](https://mosaicml.atlassian.net/browse/CO-1110)
=> Autoload HuggingFace model/tokenizer

composer/core/data_spec.py, composer/trainer/trainer.py, tests/test_split_batch.py
=> Decrease microbatch size if batch size is smaller

composer/core/engine.py, composer/trainer/trainer.py, tests/trainer/test_trainer_eval.py
1. removes deprecated code which has been dead for 3+ months
2. sets deprecation timeline for old eval api
=> remove deprecated code

composer/trainer/trainer.py
=> Minor docs fix for deepspeed typo

composer/trainer/trainer.py, examples/auto_microbatching.ipynb, tests/trainer/test_trainer.py
- Fixes bug in auto microbatching
- Adds unit test
[CO-1473](https://mosaicml.atlassian.net/browse/CO-1473)
=> Update Auto Microbatching

composer/trainer/trainer.py
As title. Will help address https://github.com/mosaicml/composer/issues/1788 in the future
=> Update error msgs

composer/core/data_spec.py, tests/test_split_batch.py
As title
Closes [CO-1523](https://mosaicml.atlassian.net/browse/CO-1523)
=> match list batch splitting and tensor batch splitting

tests/algorithms/test_torch_export.py
New onnx release seems to have broken linter
=> Add type ignore for onnx import

composer/core/evaluator.py, composer/trainer/trainer.py, tests/trainer/test_trainer_eval.py
=> fix inf eval

examples/exporting_for_inference.ipynb
As title
[CO-1553](https://mosaicml.atlassian.net/browse/CO-1553)
=> Fix Export Docs

docs/source/getting_started/installation.rst
=> Add pip targets to installation.rst docs

composer/models/deeplabv3/README.md, composer/models/resnet/README.md, docs/source/notes/tensorboard_logger.md
Removes any references to YAHP from documentation.
Fixes [CO-1413](https://mosaicml.atlassian.net/browse/CO-1413)
=> Removed YAHP references from Docs

.github/workflows/pytest-daily.yaml
Minor typo in PR not caught by static validation has broken daily tests
=> fix fail fast in daily

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Changes vision image to build on 3.10 / torch 1.13.
=> Change vision image

composer/models/base.py, composer/models/tasks/classification.py
=> Fix eval_forward in the ComposerModel ABC

.github/workflows/pytest-daily.yaml, .github/workflows/pytest.yaml
Update vision image in pytest GHA to Torch 1.13
[CO-1651](https://mosaicml.atlassian.net/browse/CO-1651)
[CO-1651]: https://mosaicml.atlassian.net/browse/CO-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Vision Image in Pytest

.github/workflows/pytest-daily.yaml, tests/datasets/test_streaming_datasets_train.py, tests/test_notebooks.py
=> Getting daily tests passing

docker/Dockerfile, tests/common/models.py, tests/conftest.py
Docker image breaks with setuptools. This pins the docker image. Also fixes a misplaced pytest skip in conftest. Also adds some nice utility fns to docker for abhi. 
[CO-1657](https://mosaicml.atlassian.net/browse/CO-1657)
[CO-1657]: https://mosaicml.atlassian.net/browse/CO-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix docker image

.ci/Jenkinsfile, .github/mcp/mcp_pytest.py, .github/workflows/pytest-gpu.yaml
As title -- these should not have been removed yet
=> Restore GPU tests

.github/workflows/pytest-daily.yaml
As title. This completes all non-docker migrations off Jenkins.
[CO-1697](https://mosaicml.atlassian.net/browse/CO-1697)
[CO-1697]: https://mosaicml.atlassian.net/browse/CO-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Enable daily gpu tests

.github/workflows/pytest-daily.yaml
Typo in command for GPU daily tests
=> Tweak daily GPU tests

.github/mcp/mcp_pytest.py, .github/workflows/pytest-daily.yaml
Misunderstood git integration in mcloud -- used wrong parameter. Along for the ride, a few safety improvements in None checks
=> Daily GPU Tests -- Change to Git Commit

tests/callbacks/test_memory_monitor.py
As title. Test is broken by this PR: https://github.com/mosaicml/composer/pull/1940
=> Fix memory monitor test

tests/callbacks/test_optimizer_monitor.py
Fix optimizer monitor test gating with FSDP. Requires torch 1.13 for FSDP
=> Fix optimizer monitor test gating with FSDP

examples/medical_image_segmentation.ipynb
As title. The medical segmentation tutorial has a typo in the metrics code
=> Medical Segmentation Example Typo

setup.py
- Bump streaming version to less than 0.4.0
=> Bump streaming version to less than 0.4.0

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps Composer version to v0.13.0.
N/A, part of release.
=> Bump version to v0.13.0

docs/source/index.rst, docs/source/notes/distributed_training.rst
Answers the common question about how to access the stdout and stderr of non-rank zero processes.
=> Update docs with non-rank zero logs instructions

setup.py
It seems the newest torchmetrics causes backwards compatibility issues. Pinning and we will fix in following major release
[CO-1916](https://mosaicml.atlassian.net/browse/CO-1916)
[CO-1916]: https://mosaicml.atlassian.net/browse/CO-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Pin torchmetrics

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps release version to v0.13.2.
N/A
=> Bump version to v0.13.2

composer/loggers/wandb_logger.py
Update Wandb docs with incorrect default
=> Update Wandb docs with incorrect default

composer/datasets/in_context_learning_evaluation.py, tests/datasets/test_in_context_learning_datasets.py
This PR seeds the random selection of fewshot examples for ICL tasks, which was previously unseeded
Closes [CO-1864](https://mosaicml.atlassian.net/browse/CO-1864)
[CO-1864]: https://mosaicml.atlassian.net/browse/CO-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Seed the fewshot sampling in the ICL datasets

composer/metrics/nlp.py, composer/models/huggingface.py
Adjusts the decoding in `HuggingFaceModel.eval_forward` for a generate batch to get the right output length even if the generation does not reach max new tokens. Confirmed the same number relative to https://github.com/mosaicml/composer/pull/2045 for gpt neo 2.7b
N/A
=> adjust decoding for eval forward

tests/common/models.py, tests/models/test_hf_model.py, tests/trainer/test_checkpoint.py
Patch a missing import for our patch release `v0.13.3`.
=> add missing import

setup.py, tests/models/test_hf_model.py
Updates the transformers pin to the latest version. This includes an xfail due to https://github.com/huggingface/transformers/issues/22482
Closes [CO-1942](https://mosaicml.atlassian.net/browse/CO-1942)
[CO-1942]: https://mosaicml.atlassian.net/browse/CO-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update transformers to latest version

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Updates Composer version to v0.13.3.
=> Bump version to 0.13.3

setup.py
- Relax streaming package version check to major version (<1.0)
=> Relax streaming package version check to major version

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump to 13.4

.github/workflows/pytest-gpu.yaml
Removes MCLI pin with bugfix in latest release.
[CO-1975](https://mosaicml.atlassian.net/browse/CO-1975)
[CO-1975]: https://mosaicml.atlassian.net/browse/CO-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removes MCLI pin

composer/trainer/trainer.py, setup.py, tests/trainer/test_sharded_checkpoint.py
Adds support for sharded grad scaler when using FSDP.
Manually testing it with a print statement:
Also to make sure we're not using closures. 
[CO-2009](https://mosaicml.atlassian.net/browse/CO-2009)
[CO-2009]: https://mosaicml.atlassian.net/browse/CO-2009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding sharded grad scaler

setup.py, tests/models/test_hf_model.py
Upgrade to transformers 4.28
Closes [CO-2024](https://mosaicml.atlassian.net/browse/CO-2024)
[CO-2024]: https://mosaicml.atlassian.net/browse/CO-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade to transformers 4.28

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to v0.13.5

tests/trainer/test_checkpoint.py
Fix bad path in previous attempt to fix daily tests.
=> Fix remote path in daily test

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Updates Composer version to 0.14.0.
N/A
=> Bump version to 0.14.0

composer/datasets/in_context_learning_evaluation.py, tests/datasets/test_in_context_learning_datasets.py
Schema task wasn't properly handling spacing with sentence piece tokenizers. Now test that there isn't an extra space added
=> bugfix sentpiece (#2198)

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to v0.14.1

setup.py
Pins protobuf, which is required by sentencepiece, or it will break on some tokenizers.
=> Pin protobuf

docs/source/trainer/checkpointing.rst
Add docs explaining how to save checkpoints to R2
fix CO-1079
=> Add docs for Checkpointing with Cloudflare R2

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Upgrades to latest torch
[CO-2097](https://mosaicml.atlassian.net/browse/CO-2097)
[CO-2097]: https://mosaicml.atlassian.net/browse/CO-2097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump to torch 2.0.1

.github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml
Forgot to update workflows to new image. This repoints workflows.
=> Update torch 2.0.1 workflows

composer/loggers/mosaicml_logger.py, composer/loggers/wandb_logger.py, tests/loggers/test_mosaicml_logger.py
Logs wandb URL to metadata.
Manual test (last line)
[CO-2008](https://mosaicml.atlassian.net/browse/CO-2008)
[CO-2008]: https://mosaicml.atlassian.net/browse/CO-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Log wandb URL to metadata

.github/mcli/mcli_pytest.py, .github/workflows/daily.yaml, .github/workflows/pytest-gpu.yaml, tests/fixtures/fixtures.py
=> Typo in s3_prefix: epemeral -> ephemeral 🤦‍♂️

composer/callbacks/speed_monitor.py
Updates torch device naming convention for h100 gpus
=> Update torch device naming convention for h100 gpus

composer/trainer/dist_strategy.py
=> Fix typo depricated -> deprecated

tests/test_notebooks.py
FFCV notebook is flaky failing on CIFAR 10 download. Skipping for now
=> Skip ffcv notebook

composer/callbacks/speed_monitor.py, docs/source/trainer/checkpointing.rst
Tiny fix in the docs for a link of working with sharded checkpointing with FSDP.
[CO-1914](https://mosaicml.atlassian.net/browse/CO-1914
)
[CO-1914]: https://mosaicml.atlassian.net/browse/CO-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Checkpointing Docs Link

README.md, docs/source/index.rst
Currently changing the public facing community slack links to :
https://mosaicml.me/slack
We used a URL shortener so that if the Slack link dies on us we don't have to change all the slack links everywhere. Please check if this works (in incognito)
- [X ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
=> Update Slack link in README.md 

composer/_version.py, docker/Dockerfile, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Update version to 0.15

.github/workflows/codeql-analysis.yml, setup.py
Turns on CodeQL on Dev / Dev PRs
=> CodeQL on PRs

docs/source/notes/resumption.rst
Fix autoresume docs link. Verified link works
=> Fix autoresume docs link

composer/loggers/mosaicml_logger.py, composer/trainer/trainer.py, tests/loggers/test_mosaicml_logger.py
Auto enables MosaicML logger when running on our platform.
Waiting for platform to auto-inject credentials
[CO-2183](https://mosaicml.atlassian.net/browse/CO-2183)
[CO-2183]: https://mosaicml.atlassian.net/browse/CO-2183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Auto add mosaicml logger

.github/workflows/pytest-gpu.yaml, setup.py, tests/trainer/test_fsdp_checkpoint.py
Fixes daily test failures with respect to autoadd mosaicml logger
Also moves channel for notifications
=> Fixes daily test failures with respect to autoadd mosaicml logger

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Update version to 15.1

composer/datasets/ade20k.py, composer/datasets/c4.py, composer/datasets/cifar.py, composer/datasets/imagenet.py
Fixes a few types in streaming usage. Not sure why this just started failing for my locally.
=> Fix typing for args in streaming

.github/workflows/docker-configure-build-push.yaml, .github/workflows/release-docker.yaml
Add extra steps in release docker workflow to free space.
=> Add extra steps for space free up

composer/callbacks/checkpoint_saver.py, tests/trainer/test_fsdp_checkpoint.py
=> add dist.barrier to rotate_checkpoints

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to 0.16

.github/mcli/mcli_pytest.py
Fix max duration scheduling. There is an extra : in key name
=> Fix max duration scheduling

composer/callbacks/__init__.py, composer/callbacks/checkpoint_saver.py, composer/callbacks/generate.py, composer/callbacks/utils.py, tests/callbacks/callback_settings.py, tests/callbacks/test_callbacks.py, tests/callbacks/test_generate.py, tests/callbacks/test_loggers_across_callbacks.py, tests/loggers/test_mosaicml_logger.py, tests/loggers/test_wandb_logger.py
Upstreams the callback that logs generations to wandb from foundry to composer. https://github.com/mosaicml/llm-foundry/blob/main/llmfoundry/callbacks/generate_callback.py 
The upstreaming should include a few things beyond just copy pasting the code into composer:
- support all logger destinations that implement a log_text method (or log_table?).
- use the HuggingFaceModel.generate function in composer rather than calling the underyling hf model directly
- support composer’s time abstraction instead of just batch_log_interval
- support a batch size argument so that the maximum number of prompts that can be used is greater
- tests
Using llm foundry quickstart example with wandb logging
cli:
```
cd llm-foundry/scripts
python data_prep/convert_dataset_hf.py \
--dataset c4 --data_subset en \ …
```
=> Upstream Generate Callback 

setup.py, tests/datasets/test_in_context_learning_datasets.py
Upgrades to support transformers 4.32
=> Transformers upgrade

composer/trainer/dist_strategy.py, docs/source/notes/distributed_training.rst, docs/source/trainer/using_the_trainer.rst, tests/models/test_hf_model.py, tests/test_events.py, tests/trainer/test_ddp.py, tests/trainer/test_fsdp_checkpoint.py, tests/trainer/test_trainer.py
=> Removing min_params

tests/trainer/test_fsdp_checkpoint.py
=> Remove PR curve metrics from backward compatibility test and skip torch 1.13

composer/core/state.py, tests/trainer/test_fsdp_checkpoint.py
Skips empty fields in state dict
=> Skip metrics in state dict

composer/callbacks/memory_monitor.py, tests/callbacks/test_memory_monitor.py
=> Add peak memory stats

setup.py
Update pre-commit version to fix go error.
GRT-2402
=> Update pre-commit in setup.py

tests/datasets/test_cifar.py
Disable cifar daily test as it is flaky and not needed
=> Disable cifar daily test

composer/loggers/mosaicml_logger.py, composer/trainer/trainer.py
Mosaicml logger robustness improvements
[CO-2408](https://databricks.atlassian.net/browse/GRT-2408)
=> Mosaicml logger robustness improvements

.github/workflows/daily.yaml, .github/workflows/pytest-cpu.yaml, tests/utils/object_store/test_gs_object_store.py
Keys were not properly setup for GCS integration testing
=> Fix github actions for GCS integration testing

composer/trainer/trainer.py, tests/loggers/test_mosaicml_logger.py
Change cast for mosaicml logger. Also fixes test which should have caught this but was also buggy.
=> Change cast for mosaicml logger

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump Version to 0.16.2

setup.py
=> Remove pin

.github/workflows/pytest-cpu.yaml, .github/workflows/pytest-gpu.yaml
Event name should be pull_request_target as well
=> Change filter to include pull_request_target

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps version ahead of release
=> Bump version to 0.16.3

tests/trainer/test_fsdp_checkpoint.py
=> Add 0.16 checkpoint to backwards compatibility tests

composer/trainer/dist_strategy.py, composer/trainer/mosaic_fsdp_utils.py
Changes monkeypatch to fix `_or_policy` and also fix a typo in monkeypatch.
=> Updating FSDP monkeypatch

.github/workflows/code-quality.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/smoketest.yaml
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #2576
=> Run CI/CD on all pull requests

composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/trainer/trainer.py
As title. Or statement did not have parentheses
=> Missing () fo or in auto microbatching gate

.devcontainer/devcontainer.json, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, docker/README.md
Upgrade pr cpu and pr gpu test docker images.
Along for the ride:
- Clean up README for docker images
Passing daily tests: https://github.com/mosaicml/composer/actions/runs/6423994142 
Passing pr tests: https://github.com/mosaicml/composer/actions/runs/6424001481
=> Change pr cpu and pr gpu test docker images 

composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py, composer/utils/checkpoint.py
commit-id:2a2cae33
---
**Stack**:
- #2637 ⬅
- #2636
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> Add partial state dict functionality for FSDP

composer/callbacks/checkpoint_saver.py
Remove checkpoint on close. Often causes issues and low benefit
=> Remove checkpoint on close

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Update latest to 2.1 

.github/workflows/daily.yaml
Updates credentials for daily tests
=> Daily API key

tests/utils/object_store/test_gs_object_store.py
=> Fix GCP tests

composer/metrics/nlp.py, composer/utils/eval_client/mosaicml_lambda_eval_client.py, tests/datasets/test_in_context_learning_datasets.py
1. Raise error if unauthorized from MAPI
2. Do not default an implementation and instead require user to explicitly set eval method
=> Secure Code Eval changes

composer/metrics/nlp.py, tests/datasets/test_in_context_learning_datasets.py
Lazy validation of code eval metric
=> Lazy validation of code eval metric

composer/callbacks/nan_monitor.py, composer/core/state.py
Also fixes typing in `state.py`.
=> Fix NaN monitor for loss dicts.

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to 0.17

tests/trainer/test_fsdp_checkpoint.py
Adds v0.17 checkpoints to list of checkpoints to check bwds compatibility
=> add 0.17 to bcompat tests

composer/loggers/mlflow_logger.py, composer/loggers/mosaicml_logger.py
Check serialization for JSON in mosaicml logger. I can't add a unit test because if we had a way to cause it to not serialize, we would patch it...
=> Check serialization for JSON in mosaicml logger

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version 0.17.1

.github/mcli/mcli_pytest.py
=> Fix GPU tests

.github/mcli/mcli_pytest.py
=> Fix GPU v2

composer/loggers/mlflow_logger.py, setup.py, tests/loggers/test_mlflow_logger.py
Use async logging in MLflowLogger
Benchmarking results available in, will need Databricks account to access:
- [benchmark stats](https://docs.google.com/spreadsheets/d/1H1p7JSFuzQvwEMsQVu_i9e7erb4FizPXtcwNbTi0J5c/edit?usp=sharing)
- [mlflow experiment view](https://dbc-04ac0685-8857.staging.cloud.databricks.com/ml/experiments/1668629222228935/runs/53315d26013346c08bc83893843e1610?o=3360802220363900)
=> Use async logging in MLflowLogger

composer/utils/object_store/uc_object_store.py, tests/utils/object_store/test_uc_object_store.py
- Add support for uc volumes list API in uc object store
- Tested by locally initializing UCObjectStore in a python REPL
```
from composer.utils.object_store import UCObjectStore
uc = UCObjectStore(path="Volumes/ml/harsh/mosaicml/")
res = uc.list_objects(prefix="Volumes/ml/harsh/mosaicml/checkpoints/ift-mpt-7b-zn4bkc/checkpoints/huggingface/ba1")
for r in res:
print(r)
print('-'*50)
res = uc.list_objects(prefix="Volumes/ml/harsh/mosaicml")
for r in res:
print(r)
###
DATABRICKS_HOST=https://e2-dogfood.staging.cloud.databricks.com/ DATABRICKS_TOKEN=<REDACTED> python3 test_uc_volume_list.py
comet_ml is installed but `COMET_API_KEY` is not set.
/Volumes/ml/harsh/mosaicml/checkpoints/ift-mpt-7b-zn4bkc/checkpoints/huggingface/ba1/config.json …
```
=> [UCVolumes] Add support for list API

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to 0.17.2

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Add nightly image for torch 2.2.0-12-20-23
=> Add nightly image for torch 2.2.0-12-20-23

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Fix nightly image to torch 12-13, the last 2.2.0 image
=> Add torch nightly 12-13

composer/trainer/dist_strategy.py, composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py, docs/source/notes/distributed_training.rst, tests/trainer/test_fsdp.py
Add process group as arg to FSDP
=> Add process group as arg to FSDP

composer/loggers/mosaicml_logger.py
Wait futures should be gated behind enabled check
=> Fix mosaicml logger on close 

.github/workflows/code-quality.yaml
Timed out after 10 minutes here https://github.com/mosaicml/composer/actions/runs/7465107219/job/20313553654?pr=2819 
Bumps runtime up to 15min
=> code-quality timeout update

composer/trainer/mosaic_fsdp.py
Remove fsdp patch for comm overlap
=> Remove fsdp patch for comm overlap

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump torch 2.1.2

composer/core/state.py, composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py, composer/trainer/trainer.py, composer/utils/checkpoint.py, tests/trainer/test_checkpoint.py
Rewrite to use individual state functions. Splits out model and optimizer state dict functions
=> Rewrite to use individual state functions

composer/loggers/mosaicml_logger.py
Remome log debug. This really pollutes logs a lot and isnt a super useful log
=> Remome log debug

setup.py
The package `toml` in setup.py isn't used.
=> Remove toml

.github/workflows/code-quality.yaml, .github/workflows/pr-code-quality.yaml
Refactors code quality workflow to take in python version and pip install as inputs.
=> Make code quality workflow reusable

setup.py
=> Bump torchmetrics

.github/workflows/daily.yaml, tests/test_notebooks.py
Fix daily tests. Throttle starting batch size as auto fails with uncatchable cublas error on CI/CD
Commit 1 shows all daily tests running and passing. Commit 2 removes running daily tests on PRs
=> Fix daily tests

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to 0.18.1

.pre-commit-config.yaml, .yamllint.yaml
Adds yamllint to pre-commit and changes config to be consistent with foundry
=> Add yamllint to pre commit

composer/loggers/mlflow_logger.py, tests/loggers/test_mlflow_logger.py
Allows users to skip logging certain hyperparameters specified by input patterns.
=> Add ignore_hyperparameters to MLFlowLogger

tests/trainer/test_fsdp_checkpoint.py
Add checkpoint BC test for 0.18.1
=> Add checkpoint test for 0.18.1

.github/workflows/release.yaml
Add inputs when calling the code quality workflow
=> Fix release yaml for code quality workflow

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bump composer version to 0.19.0
=> Release v0.19.0

composer/trainer/mosaic_fsdp.py, composer/trainer/mosaic_fsdp_utils.py, composer/trainer/trainer.py, composer/utils/fx_utils.py, tests/datasets/test_in_context_learning_datasets.py
Adds torch 2.2 support
- Gates imports
- Fixes lint
=> Torch 2.2 Support

.github/workflows/pr-code-quality.yaml, .github/workflows/release.yaml, .github/workflows/smoketest.yaml, .readthedocs.yaml, setup.py
Deprecate python3.8
https://databricks.atlassian.net/browse/GRT-2659
=> Deprecate python3.8

.github/dependabot.yml, .github/workflows/code-quality.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/docker-configure-build-push.yaml, .github/workflows/pr-code-quality.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-docker.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/pytest-cpu.yaml, .github/workflows/pytest-gpu.yaml, .github/workflows/release-docker.yaml, .github/workflows/release.yaml, .github/workflows/smoketest.yaml, .pre-commit-config.yaml, .readthedocs.yaml, .yamllint.yaml
=> Lint yamls

.github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml
Fix dailies by tweaking GPU versions and removing torch 1.13
=> Fix dailies by tweaking GPU versions and removing torch 1.13

.github/workflows/daily.yaml
=> Add Torch 2.2 tests

.github/workflows/daily.yaml, tests/trainer/test_checkpoint.py
Missed a few test fixes in initial PR
=> More torch 2.2 fixes

.github/workflows/pytest-cpu.yaml, .github/workflows/pytest-gpu.yaml, pyproject.toml
Ignoring deprecation warnings as new API has some hiccups still.
Also removes slack notifications -- I forgot a spot
=> Fix daily tests for torch 2.2

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump to 0.19.1

setup.py
The release last night broke our error handling. Pinning to old version for now as quick fix.
=> Pin UC to earlier version

composer/profiler/profiler.py, composer/profiler/profiler_schedule.py, composer/profiler/torch_profiler.py, tests/profiler/test_profiler.py
Reverts mosaicml/composer#2986
=> Revert "fix skip_first for resumption"

composer/cli/launcher.py
Update NCCL arg since torch deprecated old one
=> Update NCCL arg since torch deprecated old one

composer/algorithms/low_precision_layernorm/low_precision_layernorm.py
Reverts mosaicml/composer#2999
=> Revert "Add bias argument to LPLN"

composer/cli/launcher.py
Reverts mosaicml/composer#3000
=> Revert "Update NCCL arg since torch deprecated old one"

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Patch torch 2.3 aws naming

composer/loggers/mosaicml_logger.py
This log isn't super helpful and is a bit scary. Removing per discussion with @jjanezhang
=> Remove log for mosaicml logger

.github/workflows/code-quality.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-code-quality.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/smoketest.yaml
Reverts mosaicml/composer#2948. PR breaks CI/CD from forks.
=> Revert "Use reusable actions for linting" to fix CI/CD

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Upgrade to python3.11 for torch nightly
=> Upgrade to python3.11 for torch nightly

.github/workflows/code-quality.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-code-quality.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/smoketest.yaml
Reverts mosaicml/composer#3025
This breaks CI/CD by running lint off dev instead of being off tip
=> Revert "Change to pull_request_target "

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump composer version 0.20.0

composer/trainer/mosaic_fsdp.py, docker/Dockerfile, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py, tests/test_passes.py
Adds torch 2.2.1 support which just removes all the monkeypatches since we've upstreamed everything.
=> Add torch 2.2.1 support 

tests/trainer/test_checkpoint.py
Fixed remote test that only runs in daily.
https://github.com/mosaicml/composer/actions/runs/8072300259
=> Fix daily test for iteration

setup.py
=> Bump packaging

composer/metrics/nlp.py
=> Add ICL base class to __all__

composer/callbacks/checkpoint_saver.py, composer/core/callback.py, composer/core/engine.py, composer/core/event.py, composer/core/state.py, composer/loggers/console_logger.py, composer/trainer/trainer.py, composer/utils/misc.py, tests/callbacks/test_checkpoint_saver.py, tests/test_events.py, tests/trainer/test_checkpoint.py, tests/trainer/test_trainer.py
Adds the relevant Iteration Events to callbacks which use time intervals.
commit-id:24dd715c
=> Add Iteration related Events to callbacks

.github/workflows/code-quality.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/smoketest.yaml
Bump CI/CD to v3. No changes for this repo.
=> Bump CI/CD to v3

composer/cli/launcher.py
Thoughts? This log makes it look like something is going wrong
=> Warning log to info log

composer/callbacks/oom_observer.py, composer/loggers/neptune_logger.py, docs/source/doctest_fixtures.py, docs/source/trainer/file_uploading.rst, docs/source/trainer/logging.rst, tests/loggers/test_neptune_logger.py
Reverts mosaicml/composer#3085
There will be a follow-on PR to fix some changes.
=> Revert "Improvements to `NeptuneLogger`"

.github/workflows/code-quality.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/smoketest.yaml
v0.0.4 of ci-testing fixes S3_bucket issue with daily
=> Uses v0.0.4 of ci-testing

docker/Dockerfile
=> Update Flash Attention to 2.5.5

composer/models/initializers.py
Reduce redundant checking for initializing
=> Refactor initialization

composer/utils/object_store/uc_object_store.py, setup.py
Manual test training on data from UC: `daniel-ift-test-save-8-NKEKIP`
=> Bump databricks sdk version

composer/utils/checkpoint.py
if `save_weights_only` is set then don't include rng in checkpoint
=> Remove rng from save_weights_only ckpt

composer/utils/checkpoint.py
Only broadcasts distcp files (sharded checkpoint files) to avoid propagating temp files from download.
=> Only broadcast distcp files

.github/workflows/code-quality.yaml, .github/workflows/release.yaml
=> Change release actions

composer/utils/checkpoint.py
=> Fix broadcast

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump to 0.21

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to 0.21.2

.github/workflows/daily.yaml
Raise daily test timeout. It's timing out.
=> Raise daily test timeout

composer/trainer/mosaic_fsdp_utils.py
Reverts mosaicml/composer#3185
=> Revert "Update mosaic_fsdp_utils.py"

tests/common/models.py, tests/conftest.py, tests/fixtures/fixtures.py, tests/loggers/test_mlflow_logger.py, tests/models/test_hf_model.py
Also fixed a breaking change in mlflow model logging and image logging
=> Fix mistral gating

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Bump version to 0.21.3

.github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, composer/core/state.py, composer/trainer/mosaic_fsdp_utils.py, tests/algorithms/test_required_on_load.py, tests/trainer/test_checkpoint.py, tests/trainer/test_fsdp_checkpoint.py
=> Add torch 2.3 CI/CD

tests/test_notebooks.py, tests/utils/object_store/test_gs_object_store.py
Fix daily test pt 4
Also marks notebook test as skipped as network download is flakey
=> Fix daily test pt 4

tests/test_notebooks.py, tests/utils/object_store/test_gs_object_store.py
=> Fix daily tests v5

tests/utils/object_store/test_gs_object_store.py
=> Fix daily v6

tests/utils/object_store/test_gs_object_store.py
=> fix daily tests v7

tests/algorithms/algorithm_settings.py, tests/algorithms/test_algorithms_train.py
Accelerate GPU tests
- decrease minimum configs for algo tests
=> Accelerate GPU tests

composer/utils/object_store/gcs_object_store.py, tests/utils/object_store/test_gs_object_store.py
Fix daily GCS tests. Changes order in which monkeypatches are applied for test to mirror new format in GS object store
=> Fix daily GCS tests

docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bump to torch 2.2.2. Also switch default to 2.3
=> Bump to torch 2.2.2

setup.py, tests/loggers/test_mlflow_logger.py
Upgrade the peft version to 0.10 so we can use new features.
Manual test: `final-llama-lora-12-B5Usxs`
=> Update peft version

tests/loggers/test_cometml_logger.py
Fix comet ml unit tests
Fix failing unit tests seen in https://github.com/mosaicml/composer/actions/runs/9198261645/job/25301753094?pr=3264
=> Fix cometml unit tests

.github/workflows/daily.yaml
Bump timeout to fix daily tests
Passing daily: https://github.com/mosaicml/composer/actions/runs/9230426742/job/25398642587
=> Bump timeout to fix daily tests

composer/callbacks/speed_monitor.py
=> Add A10 to speed monitor

tests/trainer/test_fsdp_checkpoint.py
Minor cleanup for test_fsdp_checkpoint
=> Minor cleanup for test_fsdp_checkpoint

composer/trainer/_patch_pytorch.py
=> Fix monkeypatch imports

composer/distributed/dist_strategy.py
Updates a docstring to reflect type annotation
=> prepare_fsdp_module documentation fix

.github/workflows/code-quality.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/release.yaml, .github/workflows/smoketest.yaml
Bumps the version of CI to 0.0.8 due to bug in 0.0.7
=> Bump CI from 0.0.7 to 0.0.8

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py, tests/trainer/test_fsdp_checkpoint.py
bump version 0.23.2
Daily: https://github.com/mosaicml/composer/actions/runs/9424917913
=> Bump version v0.23.2

composer/_version.py, tests/trainer/test_fsdp_checkpoint.py
=> Restore dev version

composer/core/callback.py, composer/core/state.py, composer/core/time.py, composer/trainer/trainer.py, tests/checkpoint/test_state_dict.py, tests/test_time.py
Add tracking for number of tokens in an iteration
=> Add tokens to iterations

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
- Bump version v0.23.3
Daily workflow: https://github.com/mosaicml/composer/actions/runs/9575867196
=> Bump version v0.23.3

composer/trainer/_patch_pytorch.py
Patch PyTorch 2.3.1. Fixes missing import
=> Patch PyTorch 2.3.1

.github/workflows/code-quality.yaml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/release.yaml, .github/workflows/smoketest.yaml
=> Bump CI testing version

composer/trainer/trainer.py
Add helpful comment explaining HSDP initialization seeding
=> Add helpful comment explaining HSDP initialization seeding

docker/Dockerfile
Upgrade flash attention to 2.6.1. Manual test run: `flash-2-6-1-f7ri79`
=> Bump flash attention to 2.6.1

docker/Dockerfile
Bumping flash attention version to v2.6.2
=> Bumping flash attention version to v2.6.2

composer/algorithms/selective_backprop/selective_backprop.py, composer/algorithms/seq_length_warmup/seq_length_warmup.py, composer/core/data_spec.py, composer/trainer/trainer.py, tests/trainer/test_trainer.py
Running regression test off of this branch right now -> Saw consistently better loss and higher alloc retries.
=> Revert "Load Microbatches instead of Entire Batches to GPU "

pyproject.toml, setup.py
Bumps transformers version to include 4.43
=> Bump transformers version

composer/_version.py
Restore dev version to 0.24.0.dev0
=> restore version on dev

.github/workflows/code-quality.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/smoketest.yaml
Remove dev branch in GPU workflows
=> Remove dev branch in GPU workflows

.github/workflows/daily.yaml, .github/workflows/pr-gpu.yaml
self descriptive, separates out from #3552
=> Fix torch 2.4 images for tests

.github/workflows/pr-gpu.yaml
=> fix runner linux-ubuntu > ubuntu-latest

composer/_version.py
=> Bump main version to 0.25.0.dev0

composer/_version.py
Sets dev version back to 0.25.0.dev0 on main.
=> Set dev version back to 0.25.0.dev0

composer/utils/device.py
Explicit None Check in get_device
=> Explicit None Check in get_device

composer/utils/remote_uploader.py
Update error message for overwrite to be more user friendly
=> Update error message for overwrite to be more user friendly

composer/trainer/trainer.py, composer/utils/checkpoint.py
=> More checkpoint debug logs

composer/trainer/trainer.py
Lower DeepSpeed deprecation version.
=> Lower DeepSpeed deprecation version

composer/utils/object_store/uc_object_store.py
Fix DB SDK import, which currently has an invalid path.
```ModuleNotFoundError: No module named 'databricks.sdk.errors.mapping'```
=> Fix DB SDK Import

.github/workflows/pr-gpu.yaml
Reverts change to pull request from pull request target which breaks ci/cd.
=> Fix pull request target

tests/trainer/test_fsdp_checkpoint.py
daily tests pass: https://github.com/mosaicml/composer/actions/runs/11601544804
=> Update checkpoint tests to use new version 0.26.0

docs/source/composer_model.rst
=> Fix typo in trainer doc

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bump composer version to 0.28.0.dev0
=> Bump version to 0.28.0.dev0

.github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml
Add torch 2.5.1 composer tests
=> Add torch 2.5.1 composer tests

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
=> Version bump to v0.29.0.dev0

setup.py
Sklearn had a regression with cpu device detection that was causing daily tests to fail for the past month. Since sklearn is only used in testing, we pin sklearn under `dev` dependencies until they release a new version of the package.
See https://github.com/scikit-learn/scikit-learn/issues/29107
=> Address sklearn device issues

composer/_version.py, composer/core/data_spec.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bump composer version in preparation for release
=> Version bump to v0.30.0.dev0

tests/trainer/test_fsdp_checkpoint.py
As title.
Daily test link: https://github.com/mosaicml/composer/actions/runs/13531579215/job/37814775147
=> Updated `test_fsdp_load_old_checkpoint` with 0.29.0

tests/utils/object_store/test_gs_object_store.py
Deprecated our GCS related tests as we deprecated our GCS infra
Fixes our daily tests
=> deprecate gcs test

setup.py, tests/fixtures/fixtures.py, tests/loggers/test_mlflow_logger.py, tests/models/test_hf_model.py
As title. All changes are in test files, as usual.
=> Bump transformers

composer/models/huggingface.py, tests/conftest.py, tests/fixtures/fixtures.py, tests/test_full_nlp.py
Removes some network calls to hf by using fixtures/skipping doc tests.
=> Remove huggyllama fixture

composer/_version.py, docker/README.md, docker/build_matrix.yaml, docker/generate_build_matrix.py
Bumps composer dev and docker docs to reflect 0.30.0 release.
N/A
=> Bump Composer 0.31.0.dev0

tests/trainer/test_fsdp_checkpoint.py
As title suggests, for 0.30.0 release
Daily test run on this branch:
https://github.com/mosaicml/composer/actions/runs/14276311099
N/A
=> Update Checkpoint Back-Compatibility Test

setup.py
=> Bump HF hub version

composer/utils/eval_client/lambda_eval_client.py, composer/utils/eval_client/local_eval_client.py, tests/utils/eval_client/test_local_eval_client.py
=> Deprecate code eval utils

.github/workflows/code-quality.yaml, .github/workflows/coverage.yaml, .github/workflows/daily.yaml, .github/workflows/pr-cpu.yaml, .github/workflows/pr-gpu.yaml, .github/workflows/release.yaml, .github/workflows/smoketest.yaml
=> Update ci-testing version to latest

composer/_version.py, tests/trainer/test_fsdp_checkpoint.py
Update the version number to v0.33.0.dev0
=> version update to v0.33.0.dev
